-- Полный каталог кулинарных продуктов мира (~2200 позиций)
-- Добавляем только те продукты, которых ещё нет в базе (по имени)
-- names: {"ru": "...", "en": "..."}, unit: g/kg/pcs/ml/L

insert into products (id, name, category, names, unit)
select gen_random_uuid(), v.name, v.category, v.names::jsonb, v.unit
from (values

-- ==================== МЯСО ====================
('Говядина (вырезка)','meat','{"ru":"Говядина (вырезка)","en":"Beef tenderloin"}','g'),
('Говядина (лопатка)','meat','{"ru":"Говядина (лопатка)","en":"Beef shoulder"}','g'),
('Говядина (грудинка)','meat','{"ru":"Говядина (грудинка)","en":"Beef brisket"}','g'),
('Говядина (ребра)','meat','{"ru":"Говядина (ребра)","en":"Beef ribs"}','g'),
('Говядина (антрекот)','meat','{"ru":"Говядина (антрекот)","en":"Beef entrecote"}','g'),
('Говядина (стейк рибай)','meat','{"ru":"Говядина (стейк рибай)","en":"Beef ribeye steak"}','g'),
('Говядина (стейк стриплойн)','meat','{"ru":"Говядина (стейк стриплойн)","en":"Beef striploin steak"}','g'),
('Говядина (фарш)','meat','{"ru":"Говядина (фарш)","en":"Ground beef"}','g'),
('Говядина (оковалок)','meat','{"ru":"Говядина (оковалок)","en":"Beef rump"}','g'),
('Говядина (толстый край)','meat','{"ru":"Говядина (толстый край)","en":"Beef chuck roll"}','g'),
('Говядина (тонкий край)','meat','{"ru":"Говядина (тонкий край)","en":"Beef sirloin"}','g'),
('Телятина (вырезка)','meat','{"ru":"Телятина (вырезка)","en":"Veal tenderloin"}','g'),
('Телятина (котлетная часть)','meat','{"ru":"Телятина (котлетная часть)","en":"Veal cutlet"}','g'),
('Телятина (нога)','meat','{"ru":"Телятина (нога)","en":"Veal leg"}','g'),
('Свинина (вырезка)','meat','{"ru":"Свинина (вырезка)","en":"Pork tenderloin"}','g'),
('Свинина (шея)','meat','{"ru":"Свинина (шея)","en":"Pork neck"}','g'),
('Свинина (лопатка)','meat','{"ru":"Свинина (лопатка)","en":"Pork shoulder"}','g'),
('Свинина (грудинка)','meat','{"ru":"Свинина (грудинка)","en":"Pork belly"}','g'),
('Свинина (корейка)','meat','{"ru":"Свинина (корейка)","en":"Pork loin"}','g'),
('Свинина (ребра)','meat','{"ru":"Свинина (ребра)","en":"Pork ribs"}','g'),
('Свинина (окорок)','meat','{"ru":"Свинина (окорок)","en":"Pork ham"}','g'),
('Свинина (фарш)','meat','{"ru":"Свинина (фарш)","en":"Ground pork"}','g'),
('Баранина (нога)','meat','{"ru":"Баранина (нога)","en":"Lamb leg"}','g'),
('Баранина (каре)','meat','{"ru":"Баранина (каре)","en":"Rack of lamb"}','g'),
('Баранина (лопатка)','meat','{"ru":"Баранина (лопатка)","en":"Lamb shoulder"}','g'),
('Баранина (корейка)','meat','{"ru":"Баранина (корейка)","en":"Lamb loin"}','g'),
('Баранина (ребра)','meat','{"ru":"Баранина (ребра)","en":"Lamb ribs"}','g'),
('Баранина (фарш)','meat','{"ru":"Баранина (фарш)","en":"Ground lamb"}','g'),
('Козлятина','meat','{"ru":"Козлятина","en":"Goat meat"}','g'),
('Конина','meat','{"ru":"Конина","en":"Horse meat"}','g'),
('Кролик (тушка)','meat','{"ru":"Кролик (тушка)","en":"Rabbit carcass"}','g'),
('Кролик (задние ноги)','meat','{"ru":"Кролик (задние ноги)","en":"Rabbit hind legs"}','g'),
('Оленина','meat','{"ru":"Оленина","en":"Venison"}','g'),
('Лосятина','meat','{"ru":"Лосятина","en":"Elk meat"}','g'),
('Кабанятина','meat','{"ru":"Кабанятина","en":"Wild boar meat"}','g'),
('Зубрятина','meat','{"ru":"Зубрятина","en":"Bison meat"}','g'),
('Утиная грудка','meat','{"ru":"Утиная грудка","en":"Duck breast"}','g'),
('Утиные ноги (конфи)','meat','{"ru":"Утиные ноги (конфи)","en":"Duck legs (confit)"}','g'),
('Гусятина','meat','{"ru":"Гусятина","en":"Goose meat"}','g'),
('Индейка (грудка)','meat','{"ru":"Индейка (грудка)","en":"Turkey breast"}','g'),
('Индейка (бедро)','meat','{"ru":"Индейка (бедро)","en":"Turkey thigh"}','g'),
('Перепел (тушка)','meat','{"ru":"Перепел (тушка)","en":"Quail carcass"}','g'),
('Голубь (тушка)','meat','{"ru":"Голубь (тушка)","en":"Pigeon carcass"}','g'),
('Фазан (тушка)','meat','{"ru":"Фазан (тушка)","en":"Pheasant carcass"}','g'),
('Страус (стейк)','meat','{"ru":"Страус (стейк)","en":"Ostrich steak"}','g'),
('Бекон копченый','meat','{"ru":"Бекон копченый","en":"Smoked bacon"}','g'),
('Ветчина вареная','meat','{"ru":"Ветчина вареная","en":"Cooked ham"}','g'),
('Карбонат свиной','meat','{"ru":"Карбонат свиной","en":"Pork carbonade"}','g'),
('Мясо смешанный фарш','meat','{"ru":"Мясо смешанный фарш","en":"Mixed ground meat"}','g'),

-- ==================== ПТИЦА ====================
('Курица (тушка)','meat','{"ru":"Курица (тушка)","en":"Whole chicken"}','g'),
('Куриное филе','meat','{"ru":"Куриное филе","en":"Chicken fillet"}','g'),
('Куриное бедро (без кости)','meat','{"ru":"Куриное бедро (без кости)","en":"Boneless chicken thigh"}','g'),
('Куриное бедро (с костью)','meat','{"ru":"Куриное бедро (с костью)","en":"Bone-in chicken thigh"}','g'),
('Куриная голень','meat','{"ru":"Куриная голень","en":"Chicken drumstick"}','g'),
('Куриное крыло','meat','{"ru":"Куриное крыло","en":"Chicken wing"}','g'),
('Куриная грудка (с кожей)','meat','{"ru":"Куриная грудка (с кожей)","en":"Chicken breast with skin"}','g'),
('Куриный фарш','meat','{"ru":"Куриный фарш","en":"Ground chicken"}','g'),
('Куриная спинка','meat','{"ru":"Куриная спинка","en":"Chicken back"}','g'),
('Утка (тушка)','meat','{"ru":"Утка (тушка)","en":"Whole duck"}','g'),
('Гусь (тушка)','meat','{"ru":"Гусь (тушка)","en":"Whole goose"}','g'),
('Индейка (тушка)','meat','{"ru":"Индейка (тушка)","en":"Whole turkey"}','g'),
('Цыпленок корнишон','meat','{"ru":"Цыпленок корнишон","en":"Poussin"}','g'),

-- ==================== СУБПРОДУКТЫ ====================
('Печень говяжья','meat','{"ru":"Печень говяжья","en":"Beef liver"}','g'),
('Печень свиная','meat','{"ru":"Печень свиная","en":"Pork liver"}','g'),
('Печень куриная','meat','{"ru":"Печень куриная","en":"Chicken liver"}','g'),
('Печень утиная','meat','{"ru":"Печень утиная","en":"Duck liver"}','g'),
('Фуа-гра (утиная печень)','meat','{"ru":"Фуа-гра (утиная печень)","en":"Foie gras (duck liver)"}','g'),
('Сердце говяжье','meat','{"ru":"Сердце говяжье","en":"Beef heart"}','g'),
('Сердце куриное','meat','{"ru":"Сердце куриное","en":"Chicken heart"}','g'),
('Язык говяжий','meat','{"ru":"Язык говяжий","en":"Beef tongue"}','g'),
('Язык свиной','meat','{"ru":"Язык свиной","en":"Pork tongue"}','g'),
('Мозги говяжьи','meat','{"ru":"Мозги говяжьи","en":"Beef brains"}','g'),
('Почки говяжьи','meat','{"ru":"Почки говяжьи","en":"Beef kidneys"}','g'),
('Почки свиные','meat','{"ru":"Почки свиные","en":"Pork kidneys"}','g'),
('Рубец говяжий','meat','{"ru":"Рубец говяжий","en":"Beef tripe"}','g'),
('Вымя говяжье','meat','{"ru":"Вымя говяжье","en":"Beef udder"}','g'),
('Хвост говяжий','meat','{"ru":"Хвост говяжий","en":"Oxtail"}','g'),
('Щека свиная','meat','{"ru":"Щека свиная","en":"Pork cheek"}','g'),
('Щека говяжья','meat','{"ru":"Щека говяжья","en":"Beef cheek"}','g'),
('Ноги свиные','meat','{"ru":"Ноги свиные","en":"Pork trotters"}','g'),
('Уши свиные','meat','{"ru":"Уши свиные","en":"Pork ears"}','g'),
('Кишки свиные','meat','{"ru":"Кишки свиные","en":"Pork intestines"}','g'),
('Кровь свиная','meat','{"ru":"Кровь свиная","en":"Pork blood"}','g'),
('Желудок куриный','meat','{"ru":"Желудок куриный","en":"Chicken gizzard"}','g'),
('Шейка куриная','meat','{"ru":"Шейка куриная","en":"Chicken neck"}','g'),
('Лапки куриные','meat','{"ru":"Лапки куриные","en":"Chicken feet"}','g'),

-- ==================== РЫБА ====================
('Лосось (филе)','seafood','{"ru":"Лосось (филе)","en":"Salmon fillet"}','g'),
('Лосось (стейк)','seafood','{"ru":"Лосось (стейк)","en":"Salmon steak"}','g'),
('Форель (филе)','seafood','{"ru":"Форель (филе)","en":"Trout fillet"}','g'),
('Форель (тушка)','seafood','{"ru":"Форель (тушка)","en":"Whole trout"}','g'),
('Тунец (филе)','seafood','{"ru":"Тунец (филе)","en":"Tuna fillet"}','g'),
('Тунец (стейк)','seafood','{"ru":"Тунец (стейк)","en":"Tuna steak"}','g'),
('Треска (филе)','seafood','{"ru":"Треска (филе)","en":"Cod fillet"}','g'),
('Треска (спинка)','seafood','{"ru":"Треска (спинка)","en":"Cod back"}','g'),
('Палтус (филе)','seafood','{"ru":"Палтус (филе)","en":"Halibut fillet"}','g'),
('Палтус (стейк)','seafood','{"ru":"Палтус (стейк)","en":"Halibut steak"}','g'),
('Судак (филе)','seafood','{"ru":"Судак (филе)","en":"Pike perch fillet"}','g'),
('Судак (тушка)','seafood','{"ru":"Судак (тушка)","en":"Whole pike perch"}','g'),
('Щука (тушка)','seafood','{"ru":"Щука (тушка)","en":"Whole pike"}','g'),
('Щука (филе)','seafood','{"ru":"Щука (филе)","en":"Pike fillet"}','g'),
('Карп (тушка)','seafood','{"ru":"Карп (тушка)","en":"Whole carp"}','g'),
('Карп (филе)','seafood','{"ru":"Карп (филе)","en":"Carp fillet"}','g'),
('Окунь (тушка)','seafood','{"ru":"Окунь (тушка)","en":"Whole perch"}','g'),
('Окунь морской (филе)','seafood','{"ru":"Окунь морской (филе)","en":"Sea bass fillet"}','g'),
('Сибас (тушка)','seafood','{"ru":"Сибас (тушка)","en":"Whole sea bass"}','g'),
('Дорада (тушка)','seafood','{"ru":"Дорада (тушка)","en":"Whole sea bream"}','g'),
('Дорада (филе)','seafood','{"ru":"Дорада (филе)","en":"Sea bream fillet"}','g'),
('Сельдь (соленая)','seafood','{"ru":"Сельдь (соленая)","en":"Salted herring"}','g'),
('Сельдь (свежая)','seafood','{"ru":"Сельдь (свежая)","en":"Fresh herring"}','g'),
('Скумбрия (тушка)','seafood','{"ru":"Скумбрия (тушка)","en":"Whole mackerel"}','g'),
('Скумбрия (копченая)','seafood','{"ru":"Скумбрия (копченая)","en":"Smoked mackerel"}','g'),
('Сардины','seafood','{"ru":"Сардины","en":"Sardines"}','g'),
('Анчоусы (соленые)','seafood','{"ru":"Анчоусы (соленые)","en":"Salted anchovies"}','g'),
('Анчоусы (в масле)','seafood','{"ru":"Анчоусы (в масле)","en":"Anchovies in oil"}','g'),
('Угорь речной','seafood','{"ru":"Угорь речной","en":"River eel"}','g'),
('Угорь морской','seafood','{"ru":"Угорь морской","en":"Sea eel"}','g'),
('Угорь копченый','seafood','{"ru":"Угорь копченый","en":"Smoked eel"}','g'),
('Камбала (филе)','seafood','{"ru":"Камбала (филе)","en":"Flounder fillet"}','g'),
('Минтай (филе)','seafood','{"ru":"Минтай (филе)","en":"Pollock fillet"}','g'),
('Хек (филе)','seafood','{"ru":"Хек (филе)","en":"Hake fillet"}','g'),
('Навага','seafood','{"ru":"Навага","en":"Saffron cod"}','g'),
('Пикша (филе)','seafood','{"ru":"Пикша (филе)","en":"Haddock fillet"}','g'),
('Путассу','seafood','{"ru":"Путассу","en":"Blue whiting"}','g'),
('Зубатка (филе)','seafood','{"ru":"Зубатка (филе)","en":"Wolffish fillet"}','g'),
('Нилийский окунь (филе)','seafood','{"ru":"Нилийский окунь (филе)","en":"Nile perch fillet"}','g'),
('Тилапия (филе)','seafood','{"ru":"Тилапия (филе)","en":"Tilapia fillet"}','g'),
('Дорадо (пресноводный)','seafood','{"ru":"Дорадо (пресноводный)","en":"Freshwater dorado"}','g'),
('Снэппер красный (филе)','seafood','{"ru":"Снэппер красный (филе)","en":"Red snapper fillet"}','g'),
('Барабулька','seafood','{"ru":"Барабулька","en":"Red mullet"}','g'),
('Рыба-меч (стейк)','seafood','{"ru":"Рыба-меч (стейк)","en":"Swordfish steak"}','g'),
('Мойва','seafood','{"ru":"Мойва","en":"Capelin"}','g'),
('Корюшка','seafood','{"ru":"Корюшка","en":"Smelt"}','g'),
('Стерлядь','seafood','{"ru":"Стерлядь","en":"Sterlet"}','g'),
('Осетр (филе)','seafood','{"ru":"Осетр (филе)","en":"Sturgeon fillet"}','g'),
('Белуга (филе)','seafood','{"ru":"Белуга (филе)","en":"Beluga fillet"}','g'),
('Кета (филе)','seafood','{"ru":"Кета (филе)","en":"Chum salmon fillet"}','g'),
('Горбуша (филе)','seafood','{"ru":"Горбуша (филе)","en":"Pink salmon fillet"}','g'),
('Нерка (филе)','seafood','{"ru":"Нерка (филе)","en":"Sockeye salmon fillet"}','g'),
('Семга (филе)','seafood','{"ru":"Семга (филе)","en":"Atlantic salmon fillet"}','g'),
('Семга (слабосоленая)','seafood','{"ru":"Семга (слабосоленая)","en":"Lightly salted salmon"}','g'),

-- ==================== МОРЕПРОДУКТЫ ====================
('Креветки тигровые','seafood','{"ru":"Креветки тигровые","en":"Tiger prawns"}','g'),
('Креветки королевские','seafood','{"ru":"Креветки королевские","en":"King prawns"}','g'),
('Креветки мелкие','seafood','{"ru":"Креветки мелкие","en":"Small shrimp"}','g'),
('Лангустин','seafood','{"ru":"Лангустин","en":"Langoustine"}','g'),
('Омар (целый)','seafood','{"ru":"Омар (целый)","en":"Whole lobster"}','g'),
('Омар (хвост)','seafood','{"ru":"Омар (хвост)","en":"Lobster tail"}','g'),
('Краб (клешни)','seafood','{"ru":"Краб (клешни)","en":"Crab claws"}','g'),
('Краб снежный (мясо)','seafood','{"ru":"Краб снежный (мясо)","en":"Snow crab meat"}','g'),
('Краб камчатский (клешни)','seafood','{"ru":"Краб камчатский (клешни)","en":"King crab claws"}','g'),
('Мидии (в ракушке)','seafood','{"ru":"Мидии (в ракушке)","en":"Mussels in shell"}','g'),
('Мидии (мясо)','seafood','{"ru":"Мидии (мясо)","en":"Mussel meat"}','g'),
('Устрицы','seafood','{"ru":"Устрицы","en":"Oysters"}','pcs'),
('Гребешок морской','seafood','{"ru":"Гребешок морской","en":"Sea scallop"}','g'),
('Гребешок (ИКС)','seafood','{"ru":"Гребешок (ИКС)","en":"Scallop roe"}','g'),
('Кальмар (тушка)','seafood','{"ru":"Кальмар (тушка)","en":"Squid tube"}','g'),
('Кальмар (кольца)','seafood','{"ru":"Кальмар (кольца)","en":"Squid rings"}','g'),
('Осьминог','seafood','{"ru":"Осьминог","en":"Octopus"}','g'),
('Каракатица','seafood','{"ru":"Каракатица","en":"Cuttlefish"}','g'),
('Морской ёж (икра)','seafood','{"ru":"Морской ёж (икра)","en":"Sea urchin roe (uni)"}','g'),
('Рапана (мясо)','seafood','{"ru":"Рапана (мясо)","en":"Rapana meat"}','g'),
('Морской гребешок сушеный','seafood','{"ru":"Морской гребешок сушеный","en":"Dried scallop"}','g'),
('Трепанг','seafood','{"ru":"Трепанг","en":"Sea cucumber"}','g'),
('Икра красная (лосось)','seafood','{"ru":"Икра красная (лосось)","en":"Red caviar (salmon)"}','g'),
('Икра черная (осетровая)','seafood','{"ru":"Икра черная (осетровая)","en":"Black caviar (sturgeon)"}','g'),
('Икра трески','seafood','{"ru":"Икра трески","en":"Cod roe"}','g'),
('Тобико (икра летучей рыбы)','seafood','{"ru":"Тобико (икра летучей рыбы)","en":"Tobiko (flying fish roe)"}','g'),
('Масаго (икра мойвы)','seafood','{"ru":"Масаго (икра мойвы)","en":"Masago (capelin roe)"}','g'),
('Авокадо','vegetables','{"ru":"Авокадо","en":"Avocado"}','g'),

-- ==================== ОВОЩИ ====================
('Морковь','vegetables','{"ru":"Морковь","en":"Carrot"}','g'),
('Лук репчатый','vegetables','{"ru":"Лук репчатый","en":"Onion"}','g'),
('Лук красный','vegetables','{"ru":"Лук красный","en":"Red onion"}','g'),
('Лук-порей','vegetables','{"ru":"Лук-порей","en":"Leek"}','g'),
('Лук-шалот','vegetables','{"ru":"Лук-шалот","en":"Shallot"}','g'),
('Лук зеленый','vegetables','{"ru":"Лук зеленый","en":"Green onion"}','g'),
('Чеснок','vegetables','{"ru":"Чеснок","en":"Garlic"}','g'),
('Картофель','vegetables','{"ru":"Картофель","en":"Potato"}','g'),
('Картофель молодой','vegetables','{"ru":"Картофель молодой","en":"New potato"}','g'),
('Батат (сладкий картофель)','vegetables','{"ru":"Батат (сладкий картофель)","en":"Sweet potato"}','g'),
('Топинамбур','vegetables','{"ru":"Топинамбур","en":"Jerusalem artichoke"}','g'),
('Свекла','vegetables','{"ru":"Свекла","en":"Beetroot"}','g'),
('Свекла мини','vegetables','{"ru":"Свекла мини","en":"Baby beetroot"}','g'),
('Капуста белокочанная','vegetables','{"ru":"Капуста белокочанная","en":"White cabbage"}','g'),
('Капуста краснокочанная','vegetables','{"ru":"Капуста краснокочанная","en":"Red cabbage"}','g'),
('Капуста савойская','vegetables','{"ru":"Капуста савойская","en":"Savoy cabbage"}','g'),
('Капуста брюссельская','vegetables','{"ru":"Капуста брюссельская","en":"Brussels sprouts"}','g'),
('Капуста пекинская','vegetables','{"ru":"Капуста пекинская","en":"Chinese cabbage"}','g'),
('Брокколи','vegetables','{"ru":"Брокколи","en":"Broccoli"}','g'),
('Цветная капуста','vegetables','{"ru":"Цветная капуста","en":"Cauliflower"}','g'),
('Кольраби','vegetables','{"ru":"Кольраби","en":"Kohlrabi"}','g'),
('Болгарский перец красный','vegetables','{"ru":"Болгарский перец красный","en":"Red bell pepper"}','g'),
('Болгарский перец желтый','vegetables','{"ru":"Болгарский перец желтый","en":"Yellow bell pepper"}','g'),
('Болгарский перец зеленый','vegetables','{"ru":"Болгарский перец зеленый","en":"Green bell pepper"}','g'),
('Перец чили красный','vegetables','{"ru":"Перец чили красный","en":"Red chili pepper"}','g'),
('Перец чили зеленый','vegetables','{"ru":"Перец чили зеленый","en":"Green chili pepper"}','g'),
('Перец халапеньо','vegetables','{"ru":"Перец халапеньо","en":"Jalapeño pepper"}','g'),
('Перец поблано','vegetables','{"ru":"Перец поблано","en":"Poblano pepper"}','g'),
('Перец серрано','vegetables','{"ru":"Перец серрано","en":"Serrano pepper"}','g'),
('Помидор','vegetables','{"ru":"Помидор","en":"Tomato"}','g'),
('Помидор черри','vegetables','{"ru":"Помидор черри","en":"Cherry tomato"}','g'),
('Помидор черри желтый','vegetables','{"ru":"Помидор черри желтый","en":"Yellow cherry tomato"}','g'),
('Помидор бакинский','vegetables','{"ru":"Помидор бакинский","en":"Baku tomato"}','g'),
('Томаты вяленые','vegetables','{"ru":"Томаты вяленые","en":"Sun-dried tomatoes"}','g'),
('Томаты консервированные','vegetables','{"ru":"Томаты консервированные","en":"Canned tomatoes"}','g'),
('Огурец','vegetables','{"ru":"Огурец","en":"Cucumber"}','g'),
('Огурец мини','vegetables','{"ru":"Огурец мини","en":"Mini cucumber"}','g'),
('Цукини','vegetables','{"ru":"Цукини","en":"Zucchini"}','g'),
('Кабачок','vegetables','{"ru":"Кабачок","en":"Summer squash"}','g'),
('Тыква','vegetables','{"ru":"Тыква","en":"Pumpkin"}','g'),
('Тыква баттернат','vegetables','{"ru":"Тыква баттернат","en":"Butternut squash"}','g'),
('Тыква хоккайдо','vegetables','{"ru":"Тыква хоккайдо","en":"Hokkaido pumpkin"}','g'),
('Баклажан','vegetables','{"ru":"Баклажан","en":"Eggplant"}','g'),
('Сельдерей (стебель)','vegetables','{"ru":"Сельдерей (стебель)","en":"Celery stalk"}','g'),
('Сельдерей (корень)','vegetables','{"ru":"Сельдерей (корень)","en":"Celeriac"}','g'),
('Пастернак','vegetables','{"ru":"Пастернак","en":"Parsnip"}','g'),
('Петрушка (корень)','vegetables','{"ru":"Петрушка (корень)","en":"Parsley root"}','g'),
('Редька','vegetables','{"ru":"Редька","en":"Radish (large)"}','g'),
('Редис','vegetables','{"ru":"Редис","en":"Radish"}','g'),
('Репа','vegetables','{"ru":"Репа","en":"Turnip"}','g'),
('Брюква','vegetables','{"ru":"Брюква","en":"Rutabaga"}','g'),
('Артишок','vegetables','{"ru":"Артишок","en":"Artichoke"}','g'),
('Фенхель','vegetables','{"ru":"Фенхель","en":"Fennel"}','g'),
('Спаржа зеленая','vegetables','{"ru":"Спаржа зеленая","en":"Green asparagus"}','g'),
('Спаржа белая','vegetables','{"ru":"Спаржа белая","en":"White asparagus"}','g'),
('Спаржа фиолетовая','vegetables','{"ru":"Спаржа фиолетовая","en":"Purple asparagus"}','g'),
('Шпинат','vegetables','{"ru":"Шпинат","en":"Spinach"}','g'),
('Мангольд','vegetables','{"ru":"Мангольд","en":"Swiss chard"}','g'),
('Руккола','vegetables','{"ru":"Руккола","en":"Arugula"}','g'),
('Щавель','vegetables','{"ru":"Щавель","en":"Sorrel"}','g'),
('Листья свеклы','vegetables','{"ru":"Листья свеклы","en":"Beet greens"}','g'),
('Пак-чой','vegetables','{"ru":"Пак-чой","en":"Bok choy"}','g'),
('Мизуна','vegetables','{"ru":"Мизуна","en":"Mizuna"}','g'),
('Кейл (кудрявая капуста)','vegetables','{"ru":"Кейл (кудрявая капуста)","en":"Kale"}','g'),
('Эндивий','vegetables','{"ru":"Эндивий","en":"Endive"}','g'),
('Радиккьо','vegetables','{"ru":"Радиккьо","en":"Radicchio"}','g'),
('Цикорий листовой','vegetables','{"ru":"Цикорий листовой","en":"Chicory leaves"}','g'),
('Айсберг (салат)','vegetables','{"ru":"Айсберг (салат)","en":"Iceberg lettuce"}','g'),
('Романо (салат)','vegetables','{"ru":"Романо (салат)","en":"Romaine lettuce"}','g'),
('Батавия (салат)','vegetables','{"ru":"Батавия (салат)","en":"Batavia lettuce"}','g'),
('Лолло-россо (салат)','vegetables','{"ru":"Лолло-россо (салат)","en":"Lollo rosso lettuce"}','g'),
('Корн (салат)','vegetables','{"ru":"Корн (салат)","en":"Corn salad"}','g'),
('Водяной кресс','vegetables','{"ru":"Водяной кресс","en":"Watercress"}','g'),
('Кресс-салат','vegetables','{"ru":"Кресс-салат","en":"Cress"}','g'),
('Горох стручковый','vegetables','{"ru":"Горох стручковый","en":"Snow peas"}','g'),
('Горох сахарный','vegetables','{"ru":"Горох сахарный","en":"Sugar snap peas"}','g'),
('Фасоль стручковая зеленая','vegetables','{"ru":"Фасоль стручковая зеленая","en":"Green beans"}','g'),
('Фасоль стручковая желтая','vegetables','{"ru":"Фасоль стручковая желтая","en":"Yellow wax beans"}','g'),
('Эдамаме','vegetables','{"ru":"Эдамаме","en":"Edamame"}','g'),
('Кукуруза (початок)','vegetables','{"ru":"Кукуруза (початок)","en":"Corn on the cob"}','g'),
('Кукуруза мини (початок)','vegetables','{"ru":"Кукуруза мини (початок)","en":"Baby corn"}','g'),
('Оливки зеленые (б/к)','vegetables','{"ru":"Оливки зеленые (б/к)","en":"Green olives (pitted)"}','g'),
('Оливки черные (б/к)','vegetables','{"ru":"Оливки черные (б/к)","en":"Black olives (pitted)"}','g'),
('Каперсы','vegetables','{"ru":"Каперсы","en":"Capers"}','g'),
('Побеги бамбука','vegetables','{"ru":"Побеги бамбука","en":"Bamboo shoots"}','g'),
('Корень лотоса','vegetables','{"ru":"Корень лотоса","en":"Lotus root"}','g'),
('Дайкон','vegetables','{"ru":"Дайкон","en":"Daikon"}','g'),
('Имбирь (корень)','spices','{"ru":"Имбирь (корень)","en":"Fresh ginger root"}','g'),
('Галангал','spices','{"ru":"Галангал","en":"Galangal"}','g'),
('Куркума (корень)','spices','{"ru":"Куркума (корень)","en":"Fresh turmeric root"}','g'),
('Хрен (корень)','vegetables','{"ru":"Хрен (корень)","en":"Horseradish root"}','g'),
('Васаби (корень)','spices','{"ru":"Васаби (корень)","en":"Wasabi root"}','g'),
('Трюфель черный','vegetables','{"ru":"Трюфель черный","en":"Black truffle"}','g'),
('Трюфель белый','vegetables','{"ru":"Трюфель белый","en":"White truffle"}','g'),

-- ==================== ГРИБЫ ====================
('Шампиньон','vegetables','{"ru":"Шампиньон","en":"Button mushroom"}','g'),
('Шампиньон коричневый (кримини)','vegetables','{"ru":"Шампиньон коричневый (кримини)","en":"Cremini mushroom"}','g'),
('Портобелло','vegetables','{"ru":"Портобелло","en":"Portobello mushroom"}','g'),
('Вешенка','vegetables','{"ru":"Вешенка","en":"Oyster mushroom"}','g'),
('Вешенка розовая','vegetables','{"ru":"Вешенка розовая","en":"Pink oyster mushroom"}','g'),
('Шиитаке','vegetables','{"ru":"Шиитаке","en":"Shiitake mushroom"}','g'),
('Эринги (королевская вешенка)','vegetables','{"ru":"Эринги (королевская вешенка)","en":"King oyster mushroom"}','g'),
('Лисичка','vegetables','{"ru":"Лисичка","en":"Chanterelle"}','g'),
('Белый гриб (боровик)','vegetables','{"ru":"Белый гриб (боровик)","en":"Porcini mushroom"}','g'),
('Опята','vegetables','{"ru":"Опята","en":"Honey mushrooms"}','g'),
('Маслята','vegetables','{"ru":"Маслята","en":"Slippery jack mushrooms"}','g'),
('Подберезовик','vegetables','{"ru":"Подберезовик","en":"Bay bolete"}','g'),
('Подосиновик','vegetables','{"ru":"Подосиновик","en":"Red cap mushroom"}','g'),
('Рыжик','vegetables','{"ru":"Рыжик","en":"Saffron milk cap"}','g'),
('Сморчок','vegetables','{"ru":"Сморчок","en":"Morel mushroom"}','g'),
('Трюфель черный летний','vegetables','{"ru":"Трюфель черный летний","en":"Summer truffle"}','g'),
('Энокитаке','vegetables','{"ru":"Энокитаке","en":"Enoki mushroom"}','g'),
('Намеко','vegetables','{"ru":"Намеко","en":"Nameko mushroom"}','g'),
('Муэр (черный древесный гриб)','vegetables','{"ru":"Муэр (черный древесный гриб)","en":"Black wood ear mushroom"}','g'),
('Снежный гриб (серебряный)','vegetables','{"ru":"Снежный гриб (серебряный)","en":"Silver ear mushroom"}','g'),
('Грибы белые сушеные','vegetables','{"ru":"Грибы белые сушеные","en":"Dried porcini mushrooms"}','g'),
('Грибы шиитаке сушеные','vegetables','{"ru":"Грибы шиитаке сушеные","en":"Dried shiitake mushrooms"}','g'),

-- ==================== ФРУКТЫ ====================
('Яблоко зеленое','fruits','{"ru":"Яблоко зеленое","en":"Green apple"}','g'),
('Яблоко красное','fruits','{"ru":"Яблоко красное","en":"Red apple"}','g'),
('Яблоко голден','fruits','{"ru":"Яблоко голден","en":"Golden apple"}','g'),
('Груша','fruits','{"ru":"Груша","en":"Pear"}','g'),
('Груша конференс','fruits','{"ru":"Груша конференс","en":"Conference pear"}','g'),
('Айва','fruits','{"ru":"Айва","en":"Quince"}','g'),
('Апельсин','fruits','{"ru":"Апельсин","en":"Orange"}','g'),
('Мандарин','fruits','{"ru":"Мандарин","en":"Mandarin"}','g'),
('Клементин','fruits','{"ru":"Клементин","en":"Clementine"}','g'),
('Лимон','fruits','{"ru":"Лимон","en":"Lemon"}','g'),
('Лайм','fruits','{"ru":"Лайм","en":"Lime"}','g'),
('Грейпфрут','fruits','{"ru":"Грейпфрут","en":"Grapefruit"}','g'),
('Помело','fruits','{"ru":"Помело","en":"Pomelo"}','g'),
('Юзу','fruits','{"ru":"Юзу","en":"Yuzu"}','g'),
('Кумкват','fruits','{"ru":"Кумкват","en":"Kumquat"}','g'),
('Банан','fruits','{"ru":"Банан","en":"Banana"}','g'),
('Банан мини (чирилито)','fruits','{"ru":"Банан мини (чирилито)","en":"Mini banana"}','g'),
('Ананас','fruits','{"ru":"Ананас","en":"Pineapple"}','g'),
('Манго (Альфонсо)','fruits','{"ru":"Манго (Альфонсо)","en":"Mango (Alphonso)"}','g'),
('Манго (Кент)','fruits','{"ru":"Манго (Кент)","en":"Mango (Kent)"}','g'),
('Папайя','fruits','{"ru":"Папайя","en":"Papaya"}','g'),
('Маракуйя','fruits','{"ru":"Маракуйя","en":"Passion fruit"}','g'),
('Гуава','fruits','{"ru":"Гуава","en":"Guava"}','g'),
('Питайя (драконий фрукт)','fruits','{"ru":"Питайя (драконий фрукт)","en":"Dragon fruit (pitaya)"}','g'),
('Рамбутан','fruits','{"ru":"Рамбутан","en":"Rambutan"}','g'),
('Личи','fruits','{"ru":"Личи","en":"Lychee"}','g'),
('Лонган','fruits','{"ru":"Лонган","en":"Longan"}','g'),
('Дуриан','fruits','{"ru":"Дуриан","en":"Durian"}','g'),
('Карамбола','fruits','{"ru":"Карамбола","en":"Star fruit"}','g'),
('Тамаринд','fruits','{"ru":"Тамаринд","en":"Tamarind"}','g'),
('Фейхоа','fruits','{"ru":"Фейхоа","en":"Feijoa"}','g'),
('Кокос (мякоть)','fruits','{"ru":"Кокос (мякоть)","en":"Coconut flesh"}','g'),
('Кокосовое молоко','dairy','{"ru":"Кокосовое молоко","en":"Coconut milk"}','ml'),
('Кокосовые сливки','dairy','{"ru":"Кокосовые сливки","en":"Coconut cream"}','ml'),
('Персик','fruits','{"ru":"Персик","en":"Peach"}','g'),
('Нектарин','fruits','{"ru":"Нектарин","en":"Nectarine"}','g'),
('Абрикос','fruits','{"ru":"Абрикос","en":"Apricot"}','g'),
('Слива','fruits','{"ru":"Слива","en":"Plum"}','g'),
('Алыча','fruits','{"ru":"Алыча","en":"Cherry plum"}','g'),
('Вишня','fruits','{"ru":"Вишня","en":"Sour cherry"}','g'),
('Черешня','fruits','{"ru":"Черешня","en":"Sweet cherry"}','g'),
('Инжир','fruits','{"ru":"Инжир","en":"Fig"}','g'),
('Инжир сушеный','fruits','{"ru":"Инжир сушеный","en":"Dried fig"}','g'),
('Хурма','fruits','{"ru":"Хурма","en":"Persimmon"}','g'),
('Гранат','fruits','{"ru":"Гранат","en":"Pomegranate"}','g'),
('Мангостин','fruits','{"ru":"Мангостин","en":"Mangosteen"}','g'),
('Физалис','fruits','{"ru":"Физалис","en":"Physalis"}','g'),
('Крыжовник','fruits','{"ru":"Крыжовник","en":"Gooseberry"}','g'),
('Смородина черная','fruits','{"ru":"Смородина черная","en":"Black currant"}','g'),
('Смородина красная','fruits','{"ru":"Смородина красная","en":"Red currant"}','g'),
('Смородина белая','fruits','{"ru":"Смородина белая","en":"White currant"}','g'),
('Малина','fruits','{"ru":"Малина","en":"Raspberry"}','g'),
('Ежевика','fruits','{"ru":"Ежевика","en":"Blackberry"}','g'),
('Клубника','fruits','{"ru":"Клубника","en":"Strawberry"}','g'),
('Клубника мини','fruits','{"ru":"Клубника мини","en":"Mini strawberry"}','g'),
('Земляника лесная','fruits','{"ru":"Земляника лесная","en":"Wild strawberry"}','g'),
('Черника','fruits','{"ru":"Черника","en":"Blueberry"}','g'),
('Голубика','fruits','{"ru":"Голубика","en":"Blueberry (highbush)"}','g'),
('Брусника','fruits','{"ru":"Брусника","en":"Lingonberry"}','g'),
('Клюква','fruits','{"ru":"Клюква","en":"Cranberry"}','g'),
('Морошка','fruits','{"ru":"Морошка","en":"Cloudberry"}','g'),
('Виноград белый (кишмиш)','fruits','{"ru":"Виноград белый (кишмиш)","en":"White seedless grapes"}','g'),
('Виноград красный','fruits','{"ru":"Виноград красный","en":"Red grapes"}','g'),
('Виноград черный','fruits','{"ru":"Виноград черный","en":"Black grapes"}','g'),
('Арбуз','fruits','{"ru":"Арбуз","en":"Watermelon"}','g'),
('Дыня','fruits','{"ru":"Дыня","en":"Melon"}','g'),
('Дыня торпеда','fruits','{"ru":"Дыня торпеда","en":"Torpedo melon"}','g'),
('Дыня шаренталь','fruits','{"ru":"Дыня шаренталь","en":"Charentais melon"}','g'),

-- ==================== СУХОФРУКТЫ ====================
('Изюм','fruits','{"ru":"Изюм","en":"Raisins"}','g'),
('Курага','fruits','{"ru":"Курага","en":"Dried apricot"}','g'),
('Чернослив','fruits','{"ru":"Чернослив","en":"Prunes"}','g'),
('Финики (Medjool)','fruits','{"ru":"Финики (Medjool)","en":"Medjool dates"}','g'),
('Финики сушеные','fruits','{"ru":"Финики сушеные","en":"Dried dates"}','g'),
('Манго сушеное','fruits','{"ru":"Манго сушеное","en":"Dried mango"}','g'),
('Клюква сушеная','fruits','{"ru":"Клюква сушеная","en":"Dried cranberry"}','g'),
('Черника сушеная','fruits','{"ru":"Черника сушеная","en":"Dried blueberry"}','g'),
('Ананас сушеный','fruits','{"ru":"Ананас сушеный","en":"Dried pineapple"}','g'),
('Папайя сушеная','fruits','{"ru":"Папайя сушеная","en":"Dried papaya"}','g'),
('Банан сушеный','fruits','{"ru":"Банан сушеный","en":"Dried banana"}','g'),

-- ==================== МОЛОЧНЫЕ ПРОДУКТЫ ====================
('Молоко 2.5%','dairy','{"ru":"Молоко 2.5%","en":"Milk 2.5%"}','ml'),
('Молоко 3.2%','dairy','{"ru":"Молоко 3.2%","en":"Milk 3.2%"}','ml'),
('Молоко 3.5%','dairy','{"ru":"Молоко 3.5%","en":"Milk 3.5%"}','ml'),
('Молоко 6%','dairy','{"ru":"Молоко 6%","en":"Milk 6%"}','ml'),
('Молоко обезжиренное','dairy','{"ru":"Молоко обезжиренное","en":"Skim milk"}','ml'),
('Молоко козье','dairy','{"ru":"Молоко козье","en":"Goat milk"}','ml'),
('Молоко овечье','dairy','{"ru":"Молоко овечье","en":"Sheep milk"}','ml'),
('Молоко топленое','dairy','{"ru":"Молоко топленое","en":"Baked milk"}','ml'),
('Молоко сгущенное','dairy','{"ru":"Молоко сгущенное","en":"Condensed milk"}','ml'),
('Молоко сухое','dairy','{"ru":"Молоко сухое","en":"Dry milk powder"}','g'),
('Сливки 10%','dairy','{"ru":"Сливки 10%","en":"Light cream 10%"}','ml'),
('Сливки 20%','dairy','{"ru":"Сливки 20%","en":"Cream 20%"}','ml'),
('Сливки 33%','dairy','{"ru":"Сливки 33%","en":"Heavy cream 33%"}','ml'),
('Сливки 35%','dairy','{"ru":"Сливки 35%","en":"Heavy whipping cream 35%"}','ml'),
('Сливки 38%','dairy','{"ru":"Сливки 38%","en":"Heavy whipping cream 38%"}','ml'),
('Сливки взбитые','dairy','{"ru":"Сливки взбитые","en":"Whipped cream"}','ml'),
('Сливки кокосовые','dairy','{"ru":"Сливки кокосовые","en":"Coconut cream"}','ml'),
('Сметана 10%','dairy','{"ru":"Сметана 10%","en":"Sour cream 10%"}','g'),
('Сметана 15%','dairy','{"ru":"Сметана 15%","en":"Sour cream 15%"}','g'),
('Сметана 20%','dairy','{"ru":"Сметана 20%","en":"Sour cream 20%"}','g'),
('Сметана 25%','dairy','{"ru":"Сметана 25%","en":"Sour cream 25%"}','g'),
('Кефир 1%','dairy','{"ru":"Кефир 1%","en":"Kefir 1%"}','ml'),
('Кефир 2.5%','dairy','{"ru":"Кефир 2.5%","en":"Kefir 2.5%"}','ml'),
('Кефир 3.2%','dairy','{"ru":"Кефир 3.2%","en":"Kefir 3.2%"}','ml'),
('Ряженка','dairy','{"ru":"Ряженка","en":"Ryazhenka (baked milk yogurt)"}','ml'),
('Простокваша','dairy','{"ru":"Простокваша","en":"Clabbered milk"}','ml'),
('Йогурт натуральный','dairy','{"ru":"Йогурт натуральный","en":"Plain yogurt"}','g'),
('Йогурт греческий 0%','dairy','{"ru":"Йогурт греческий 0%","en":"Greek yogurt 0%"}','g'),
('Йогурт греческий 2%','dairy','{"ru":"Йогурт греческий 2%","en":"Greek yogurt 2%"}','g'),
('Йогурт греческий 10%','dairy','{"ru":"Йогурт греческий 10%","en":"Greek yogurt 10%"}','g'),
('Айран','dairy','{"ru":"Айран","en":"Ayran"}','ml'),
('Лабне','dairy','{"ru":"Лабне","en":"Labneh"}','g'),
('Творог 0%','dairy','{"ru":"Творог 0%","en":"Cottage cheese 0%"}','g'),
('Творог 2%','dairy','{"ru":"Творог 2%","en":"Cottage cheese 2%"}','g'),
('Творог 5%','dairy','{"ru":"Творог 5%","en":"Cottage cheese 5%"}','g'),
('Творог 9%','dairy','{"ru":"Творог 9%","en":"Cottage cheese 9%"}','g'),
('Творог 18%','dairy','{"ru":"Творог 18%","en":"Cottage cheese 18%"}','g'),
('Маскарпоне','dairy','{"ru":"Маскарпоне","en":"Mascarpone"}','g'),
('Рикотта','dairy','{"ru":"Рикотта","en":"Ricotta"}','g'),
('Крем-чиз','dairy','{"ru":"Крем-чиз","en":"Cream cheese"}','g'),
('Филадельфия (сыр)','dairy','{"ru":"Филадельфия (сыр)","en":"Philadelphia cream cheese"}','g'),
('Сыр моцарелла (шарики)','dairy','{"ru":"Сыр моцарелла (шарики)","en":"Mozzarella balls"}','g'),
('Сыр моцарелла (буффало)','dairy','{"ru":"Сыр моцарелла (буффало)","en":"Buffalo mozzarella"}','g'),
('Сыр страчателла','dairy','{"ru":"Сыр страчателла","en":"Stracciatella cheese"}','g'),
('Сыр буррата','dairy','{"ru":"Сыр буррата","en":"Burrata cheese"}','g'),
('Сыр фета','dairy','{"ru":"Сыр фета","en":"Feta cheese"}','g'),
('Сыр бри','dairy','{"ru":"Сыр бри","en":"Brie cheese"}','g'),
('Сыр камамбер','dairy','{"ru":"Сыр камамбер","en":"Camembert cheese"}','g'),
('Сыр рокфор','dairy','{"ru":"Сыр рокфор","en":"Roquefort cheese"}','g'),
('Сыр горгонзола','dairy','{"ru":"Сыр горгонзола","en":"Gorgonzola cheese"}','g'),
('Сыр дор блю','dairy','{"ru":"Сыр дор блю","en":"Dor Blue cheese"}','g'),
('Сыр пармезан','dairy','{"ru":"Сыр пармезан","en":"Parmesan cheese"}','g'),
('Сыр грана падано','dairy','{"ru":"Сыр грана падано","en":"Grana Padano cheese"}','g'),
('Сыр пекорино','dairy','{"ru":"Сыр пекорино","en":"Pecorino cheese"}','g'),
('Сыр грюйер','dairy','{"ru":"Сыр грюйер","en":"Gruyère cheese"}','g'),
('Сыр эмменталь','dairy','{"ru":"Сыр эмменталь","en":"Emmental cheese"}','g'),
('Сыр маасдам','dairy','{"ru":"Сыр маасдам","en":"Maasdam cheese"}','g'),
('Сыр гауда','dairy','{"ru":"Сыр гауда","en":"Gouda cheese"}','g'),
('Сыр эдам','dairy','{"ru":"Сыр эдам","en":"Edam cheese"}','g'),
('Сыр чеддер','dairy','{"ru":"Сыр чеддер","en":"Cheddar cheese"}','g'),
('Сыр российский','dairy','{"ru":"Сыр российский","en":"Russian cheese"}','g'),
('Сыр голландский','dairy','{"ru":"Сыр голландский","en":"Dutch cheese"}','g'),
('Сыр адыгейский','dairy','{"ru":"Сыр адыгейский","en":"Adyghe cheese"}','g'),
('Сыр сулугуни','dairy','{"ru":"Сыр сулугуни","en":"Sulguni cheese"}','g'),
('Сыр брынза','dairy','{"ru":"Сыр брынза","en":"Bryndza cheese"}','g'),
('Сыр халуми','dairy','{"ru":"Сыр халуми","en":"Halloumi cheese"}','g'),
('Сыр манчего','dairy','{"ru":"Сыр манчего","en":"Manchego cheese"}','g'),
('Сыр азиаго','dairy','{"ru":"Сыр азиаго","en":"Asiago cheese"}','g'),
('Сыр таледжо','dairy','{"ru":"Сыр таледжо","en":"Taleggio cheese"}','g'),
('Сыр реблошон','dairy','{"ru":"Сыр реблошон","en":"Reblochon cheese"}','g'),
('Сыр раклет','dairy','{"ru":"Сыр раклет","en":"Raclette cheese"}','g'),
('Сыр проволоне','dairy','{"ru":"Сыр проволоне","en":"Provolone cheese"}','g'),
('Сыр страчино','dairy','{"ru":"Сыр страчино","en":"Stracchino cheese"}','g'),
('Масло сливочное 72.5%','dairy','{"ru":"Масло сливочное 72.5%","en":"Butter 72.5%"}','g'),
('Масло сливочное 82.5%','dairy','{"ru":"Масло сливочное 82.5%","en":"Butter 82.5%"}','g'),
('Масло сливочное топленое (ги)','dairy','{"ru":"Масло сливочное топленое (ги)","en":"Ghee (clarified butter)"}','g'),
('Масло козье','dairy','{"ru":"Масло козье","en":"Goat butter"}','g'),
('Яйцо куриное С0','eggs','{"ru":"Яйцо куриное С0","en":"Chicken egg (large)"}','pcs'),
('Яйцо куриное С1','eggs','{"ru":"Яйцо куриное С1","en":"Chicken egg (medium)"}','pcs'),
('Яйцо куриное С2','eggs','{"ru":"Яйцо куриное С2","en":"Chicken egg (small)"}','pcs'),
('Яйцо перепелиное','eggs','{"ru":"Яйцо перепелиное","en":"Quail egg"}','pcs'),
('Яйцо утиное','eggs','{"ru":"Яйцо утиное","en":"Duck egg"}','pcs'),
('Яйцо гусиное','eggs','{"ru":"Яйцо гусиное","en":"Goose egg"}','pcs'),
('Яйцо страусиное','eggs','{"ru":"Яйцо страусиное","en":"Ostrich egg"}','pcs'),
('Белок яичный','eggs','{"ru":"Белок яичный","en":"Egg white"}','g'),
('Желток яичный','eggs','{"ru":"Желток яичный","en":"Egg yolk"}','g'),
('Меланж яичный','eggs','{"ru":"Меланж яичный","en":"Egg melange"}','g'),

-- ==================== КРУПЫ И ЗЕРНОВЫЕ ====================
('Рис белый (длиннозерный)','grains','{"ru":"Рис белый (длиннозерный)","en":"Long grain white rice"}','g'),
('Рис белый (круглозерный)','grains','{"ru":"Рис белый (круглозерный)","en":"Round grain white rice"}','g'),
('Рис басмати','grains','{"ru":"Рис басмати","en":"Basmati rice"}','g'),
('Рис жасмин','grains','{"ru":"Рис жасмин","en":"Jasmine rice"}','g'),
('Рис для суши','grains','{"ru":"Рис для суши","en":"Sushi rice"}','g'),
('Рис арборио (ризотто)','grains','{"ru":"Рис арборио (ризотто)","en":"Arborio rice"}','g'),
('Рис карнароли (ризотто)','grains','{"ru":"Рис карнароли (ризотто)","en":"Carnaroli rice"}','g'),
('Рис черный (запрещенный)','grains','{"ru":"Рис черный (запрещенный)","en":"Black forbidden rice"}','g'),
('Рис коричневый','grains','{"ru":"Рис коричневый","en":"Brown rice"}','g'),
('Рис дикий','grains','{"ru":"Рис дикий","en":"Wild rice"}','g'),
('Рис клейкий','grains','{"ru":"Рис клейкий","en":"Sticky rice"}','g'),
('Рис красный','grains','{"ru":"Рис красный","en":"Red rice"}','g'),
('Гречка ядрица','grains','{"ru":"Гречка ядрица","en":"Buckwheat groats"}','g'),
('Гречка продел','grains','{"ru":"Гречка продел","en":"Buckwheat flakes"}','g'),
('Пшено','grains','{"ru":"Пшено","en":"Millet"}','g'),
('Овсяные хлопья','grains','{"ru":"Овсяные хлопья","en":"Rolled oats"}','g'),
('Овсяные хлопья быстрого приготовления','grains','{"ru":"Овсяные хлопья быстрого приготовления","en":"Instant oats"}','g'),
('Геркулес','grains','{"ru":"Геркулес","en":"Oat flakes (Hercules)"}','g'),
('Овсяная крупа','grains','{"ru":"Овсяная крупа","en":"Oat groats"}','g'),
('Манная крупа','grains','{"ru":"Манная крупа","en":"Semolina"}','g'),
('Кукурузная крупа','grains','{"ru":"Кукурузная крупа","en":"Corn grits"}','g'),
('Полента','grains','{"ru":"Полента","en":"Polenta"}','g'),
('Пшеничная крупа','grains','{"ru":"Пшеничная крупа","en":"Wheat groats"}','g'),
('Булгур','grains','{"ru":"Булгур","en":"Bulgur"}','g'),
('Кускус','grains','{"ru":"Кускус","en":"Couscous"}','g'),
('Киноа белая','grains','{"ru":"Киноа белая","en":"White quinoa"}','g'),
('Киноа красная','grains','{"ru":"Киноа красная","en":"Red quinoa"}','g'),
('Киноа черная','grains','{"ru":"Киноа черная","en":"Black quinoa"}','g'),
('Амарант','grains','{"ru":"Амарант","en":"Amaranth"}','g'),
('Полба','grains','{"ru":"Полба","en":"Spelt"}','g'),
('Камут','grains','{"ru":"Камут","en":"Kamut"}','g'),
('Теф','grains','{"ru":"Теф","en":"Teff"}','g'),
('Перловая крупа','grains','{"ru":"Перловая крупа","en":"Pearl barley"}','g'),
('Ячневая крупа','grains','{"ru":"Ячневая крупа","en":"Barley groats"}','g'),
('Сорго','grains','{"ru":"Сорго","en":"Sorghum"}','g'),
('Фрике (обжаренная пшеница)','grains','{"ru":"Фрике (обжаренная пшеница)","en":"Freekeh"}','g'),

-- ==================== МУКА И ВЫПЕЧКА ====================
('Мука пшеничная в/с','bakery','{"ru":"Мука пшеничная в/с","en":"All-purpose wheat flour"}','g'),
('Мука пшеничная 1 сорт','bakery','{"ru":"Мука пшеничная 1 сорт","en":"Wheat flour type 1"}','g'),
('Мука пшеничная цельнозерновая','bakery','{"ru":"Мука пшеничная цельнозерновая","en":"Whole wheat flour"}','g'),
('Мука ржаная','bakery','{"ru":"Мука ржаная","en":"Rye flour"}','g'),
('Мука ржаная обдирная','bakery','{"ru":"Мука ржаная обдирная","en":"Peeled rye flour"}','g'),
('Мука кукурузная','bakery','{"ru":"Мука кукурузная","en":"Corn flour"}','g'),
('Мука рисовая','bakery','{"ru":"Мука рисовая","en":"Rice flour"}','g'),
('Мука гречневая','bakery','{"ru":"Мука гречневая","en":"Buckwheat flour"}','g'),
('Мука нутовая','bakery','{"ru":"Мука нутовая","en":"Chickpea flour"}','g'),
('Мука миндальная','bakery','{"ru":"Мука миндальная","en":"Almond flour"}','g'),
('Мука кокосовая','bakery','{"ru":"Мука кокосовая","en":"Coconut flour"}','g'),
('Мука тапиоковая','bakery','{"ru":"Мука тапиоковая","en":"Tapioca flour"}','g'),
('Мука полбяная','bakery','{"ru":"Мука полбяная","en":"Spelt flour"}','g'),
('Мука овсяная','bakery','{"ru":"Мука овсяная","en":"Oat flour"}','g'),
('Крахмал картофельный','bakery','{"ru":"Крахмал картофельный","en":"Potato starch"}','g'),
('Крахмал кукурузный','bakery','{"ru":"Крахмал кукурузный","en":"Corn starch"}','g'),
('Крахмал тапиоковый','bakery','{"ru":"Крахмал тапиоковый","en":"Tapioca starch"}','g'),
('Крахмал рисовый','bakery','{"ru":"Крахмал рисовый","en":"Rice starch"}','g'),
('Дрожжи сухие','bakery','{"ru":"Дрожжи сухие","en":"Dry yeast"}','g'),
('Дрожжи прессованные','bakery','{"ru":"Дрожжи прессованные","en":"Fresh pressed yeast"}','g'),
('Разрыхлитель','bakery','{"ru":"Разрыхлитель","en":"Baking powder"}','g'),
('Сода пищевая','bakery','{"ru":"Сода пищевая","en":"Baking soda"}','g'),
('Ваниль (стручок)','spices','{"ru":"Ваниль (стручок)","en":"Vanilla bean"}','g'),
('Ванилин','spices','{"ru":"Ванилин","en":"Vanillin"}','g'),
('Ванильный сахар','bakery','{"ru":"Ванильный сахар","en":"Vanilla sugar"}','g'),
('Ванильный экстракт','bakery','{"ru":"Ванильный экстракт","en":"Vanilla extract"}','ml'),
('Желатин листовой','bakery','{"ru":"Желатин листовой","en":"Sheet gelatin"}','g'),
('Желатин порошковый','bakery','{"ru":"Желатин порошковый","en":"Powdered gelatin"}','g'),
('Агар-агар','bakery','{"ru":"Агар-агар","en":"Agar-agar"}','g'),
('Пектин','bakery','{"ru":"Пектин","en":"Pectin"}','g'),
('Ксантановая камедь','bakery','{"ru":"Ксантановая камедь","en":"Xanthan gum"}','g'),
('Панировочные сухари','bakery','{"ru":"Панировочные сухари","en":"Breadcrumbs"}','g'),
('Панко (японские сухари)','bakery','{"ru":"Панко (японские сухари)","en":"Panko breadcrumbs"}','g'),

-- ==================== БОБОВЫЕ ====================
('Нут','legumes','{"ru":"Нут","en":"Chickpeas"}','g'),
('Нут (консервированный)','legumes','{"ru":"Нут (консервированный)","en":"Canned chickpeas"}','g'),
('Чечевица красная','legumes','{"ru":"Чечевица красная","en":"Red lentils"}','g'),
('Чечевица зеленая','legumes','{"ru":"Чечевица зеленая","en":"Green lentils"}','g'),
('Чечевица черная (белуга)','legumes','{"ru":"Чечевица черная (белуга)","en":"Black beluga lentils"}','g'),
('Чечевица французская (пюи)','legumes','{"ru":"Чечевица французская (пюи)","en":"French Puy lentils"}','g'),
('Фасоль белая','legumes','{"ru":"Фасоль белая","en":"White beans"}','g'),
('Фасоль красная','legumes','{"ru":"Фасоль красная","en":"Red kidney beans"}','g'),
('Фасоль черная','legumes','{"ru":"Фасоль черная","en":"Black beans"}','g'),
('Фасоль пинто','legumes','{"ru":"Фасоль пинто","en":"Pinto beans"}','g'),
('Фасоль мунг (маш)','legumes','{"ru":"Фасоль мунг (маш)","en":"Mung beans"}','g'),
('Фасоль адзуки','legumes','{"ru":"Фасоль адзуки","en":"Adzuki beans"}','g'),
('Горох сухой','legumes','{"ru":"Горох сухой","en":"Dried peas"}','g'),
('Горох колотый','legumes','{"ru":"Горох колотый","en":"Split peas"}','g'),
('Чечевица (консервированная)','legumes','{"ru":"Чечевица (консервированная)","en":"Canned lentils"}','g'),
('Соя (бобы)','legumes','{"ru":"Соя (бобы)","en":"Soybeans"}','g'),
('Тофу твердый','legumes','{"ru":"Тофу твердый","en":"Firm tofu"}','g'),
('Тофу шелковый','legumes','{"ru":"Тофу шелковый","en":"Silken tofu"}','g'),
('Темпе','legumes','{"ru":"Темпе","en":"Tempeh"}','g'),

-- ==================== ОРЕХИ И СЕМЕНА ====================
('Грецкий орех','nuts','{"ru":"Грецкий орех","en":"Walnut"}','g'),
('Миндаль','nuts','{"ru":"Миндаль","en":"Almond"}','g'),
('Миндаль жареный','nuts','{"ru":"Миндаль жареный","en":"Roasted almond"}','g'),
('Фундук','nuts','{"ru":"Фундук","en":"Hazelnut"}','g'),
('Фундук жареный','nuts','{"ru":"Фундук жареный","en":"Roasted hazelnut"}','g'),
('Фисташки','nuts','{"ru":"Фисташки","en":"Pistachios"}','g'),
('Фисташки несоленые','nuts','{"ru":"Фисташки несоленые","en":"Unsalted pistachios"}','g'),
('Кешью','nuts','{"ru":"Кешью","en":"Cashew"}','g'),
('Кешью жареный','nuts','{"ru":"Кешью жареный","en":"Roasted cashew"}','g'),
('Кедровый орех','nuts','{"ru":"Кедровый орех","en":"Pine nut"}','g'),
('Пекан','nuts','{"ru":"Пекан","en":"Pecan"}','g'),
('Макадамия','nuts','{"ru":"Макадамия","en":"Macadamia nut"}','g'),
('Бразильский орех','nuts','{"ru":"Бразильский орех","en":"Brazil nut"}','g'),
('Арахис','nuts','{"ru":"Арахис","en":"Peanut"}','g'),
('Арахис жареный','nuts','{"ru":"Арахис жареный","en":"Roasted peanut"}','g'),
('Паста арахисовая','nuts','{"ru":"Паста арахисовая","en":"Peanut butter"}','g'),
('Паста миндальная','nuts','{"ru":"Паста миндальная","en":"Almond butter"}','g'),
('Паста кешью','nuts','{"ru":"Паста кешью","en":"Cashew butter"}','g'),
('Паста из фундука (нутелла-тип)','nuts','{"ru":"Паста из фундука (нутелла-тип)","en":"Hazelnut paste"}','g'),
('Кунжут белый','nuts','{"ru":"Кунжут белый","en":"White sesame seeds"}','g'),
('Кунжут черный','nuts','{"ru":"Кунжут черный","en":"Black sesame seeds"}','g'),
('Тахини (паста кунжутная)','nuts','{"ru":"Тахини (паста кунжутная)","en":"Tahini (sesame paste)"}','g'),
('Семена подсолнечника','nuts','{"ru":"Семена подсолнечника","en":"Sunflower seeds"}','g'),
('Семена тыквы','nuts','{"ru":"Семена тыквы","en":"Pumpkin seeds"}','g'),
('Семена льна','nuts','{"ru":"Семена льна","en":"Flax seeds"}','g'),
('Семена чиа','nuts','{"ru":"Семена чиа","en":"Chia seeds"}','g'),
('Семена мака','nuts','{"ru":"Семена мака","en":"Poppy seeds"}','g'),
('Семена горчицы желтой','spices','{"ru":"Семена горчицы желтой","en":"Yellow mustard seeds"}','g'),
('Семена горчицы черной','spices','{"ru":"Семена горчицы черной","en":"Black mustard seeds"}','g'),
('Семена фенхеля','spices','{"ru":"Семена фенхеля","en":"Fennel seeds"}','g'),
('Семена кориандра','spices','{"ru":"Семена кориандра","en":"Coriander seeds"}','g'),
('Семена тмина','spices','{"ru":"Семена тмина","en":"Caraway seeds"}','g'),
('Семена кумина (зира)','spices','{"ru":"Семена кумина (зира)","en":"Cumin seeds"}','g'),
('Семена аниса','spices','{"ru":"Семена аниса","en":"Anise seeds"}','g'),
('Семена нигеллы (чернушка)','spices','{"ru":"Семена нигеллы (чернушка)","en":"Nigella seeds"}','g'),
('Семена пажитника','spices','{"ru":"Семена пажитника","en":"Fenugreek seeds"}','g'),
('Семена кардамона','spices','{"ru":"Семена кардамона","en":"Cardamom seeds"}','g'),

-- ==================== СПЕЦИИ И ПРЯНОСТИ ====================
('Перец черный горошек','spices','{"ru":"Перец черный горошек","en":"Black peppercorns"}','g'),
('Перец черный молотый','spices','{"ru":"Перец черный молотый","en":"Ground black pepper"}','g'),
('Перец белый горошек','spices','{"ru":"Перец белый горошек","en":"White peppercorns"}','g'),
('Перец белый молотый','spices','{"ru":"Перец белый молотый","en":"Ground white pepper"}','g'),
('Перец розовый горошек','spices','{"ru":"Перец розовый горошек","en":"Pink peppercorns"}','g'),
('Перец зеленый горошек','spices','{"ru":"Перец зеленый горошек","en":"Green peppercorns"}','g'),
('Смесь перцев','spices','{"ru":"Смесь перцев","en":"Mixed peppercorns"}','g'),
('Перец душистый','spices','{"ru":"Перец душистый","en":"Allspice"}','g'),
('Перец кайенский','spices','{"ru":"Перец кайенский","en":"Cayenne pepper"}','g'),
('Паприка сладкая','spices','{"ru":"Паприка сладкая","en":"Sweet paprika"}','g'),
('Паприка копченая','spices','{"ru":"Паприка копченая","en":"Smoked paprika"}','g'),
('Паприка острая','spices','{"ru":"Паприка острая","en":"Hot paprika"}','g'),
('Куркума молотая','spices','{"ru":"Куркума молотая","en":"Ground turmeric"}','g'),
('Кориандр молотый','spices','{"ru":"Кориандр молотый","en":"Ground coriander"}','g'),
('Кумин молотый (зира)','spices','{"ru":"Кумин молотый (зира)","en":"Ground cumin"}','g'),
('Тмин молотый','spices','{"ru":"Тмин молотый","en":"Ground caraway"}','g'),
('Кардамон молотый','spices','{"ru":"Кардамон молотый","en":"Ground cardamom"}','g'),
('Кардамон зеленый (стручки)','spices','{"ru":"Кардамон зеленый (стручки)","en":"Green cardamom pods"}','g'),
('Кардамон черный','spices','{"ru":"Кардамон черный","en":"Black cardamom"}','g'),
('Корица молотая','spices','{"ru":"Корица молотая","en":"Ground cinnamon"}','g'),
('Корица (палочки)','spices','{"ru":"Корица (палочки)","en":"Cinnamon sticks"}','g'),
('Мускатный орех молотый','spices','{"ru":"Мускатный орех молотый","en":"Ground nutmeg"}','g'),
('Мускатный орех (целый)','spices','{"ru":"Мускатный орех (целый)","en":"Whole nutmeg"}','g'),
('Мускатный цвет (мэйс)','spices','{"ru":"Мускатный цвет (мэйс)","en":"Mace"}','g'),
('Гвоздика молотая','spices','{"ru":"Гвоздика молотая","en":"Ground cloves"}','g'),
('Гвоздика (целая)','spices','{"ru":"Гвоздика (целая)","en":"Whole cloves"}','g'),
('Анис звездчатый (бадьян)','spices','{"ru":"Анис звездчатый (бадьян)","en":"Star anise"}','g'),
('Имбирь молотый','spices','{"ru":"Имбирь молотый","en":"Ground ginger"}','g'),
('Шафран','spices','{"ru":"Шафран","en":"Saffron"}','g'),
('Сумах','spices','{"ru":"Сумах","en":"Sumac"}','g'),
('Зерберет (эфиопская смесь)','spices','{"ru":"Зерберет (эфиопская смесь)","en":"Berbere spice blend"}','g'),
('Рас-эль-ханут','spices','{"ru":"Рас-эль-ханут","en":"Ras el hanout"}','g'),
('Гарам масала','spices','{"ru":"Гарам масала","en":"Garam masala"}','g'),
('Карри порошок','spices','{"ru":"Карри порошок","en":"Curry powder"}','g'),
('Карри паста красная','spices','{"ru":"Карри паста красная","en":"Red curry paste"}','g'),
('Карри паста зеленая','spices','{"ru":"Карри паста зеленая","en":"Green curry paste"}','g'),
('Карри паста желтая','spices','{"ru":"Карри паста желтая","en":"Yellow curry paste"}','g'),
('Смесь 5 специй (китайская)','spices','{"ru":"Смесь 5 специй (китайская)","en":"Five spice powder"}','g'),
('Смесь для глинтвейна','spices','{"ru":"Смесь для глинтвейна","en":"Mulled wine spice blend"}','g'),
('Смесь прованских трав','spices','{"ru":"Смесь прованских трав","en":"Herbes de Provence"}','g'),
('Итальянские травы (смесь)','spices','{"ru":"Итальянские травы (смесь)","en":"Italian herb blend"}','g'),
('Хмели-сунели','spices','{"ru":"Хмели-сунели","en":"Khmeli-suneli spice blend"}','g'),
('Смесь для шашлыка','spices','{"ru":"Смесь для шашлыка","en":"Shashlik spice blend"}','g'),
('Аджика сухая','spices','{"ru":"Аджика сухая","en":"Dry adjika spice"}','g'),
('Порошок чесночный','spices','{"ru":"Порошок чесночный","en":"Garlic powder"}','g'),
('Порошок луковый','spices','{"ru":"Порошок луковый","en":"Onion powder"}','g'),
('Хлопья чесночные','spices','{"ru":"Хлопья чесночные","en":"Garlic flakes"}','g'),

-- ==================== СВЕЖИЕ ТРАВЫ ====================
('Петрушка (зелень)','spices','{"ru":"Петрушка (зелень)","en":"Fresh parsley"}','g'),
('Укроп','spices','{"ru":"Укроп","en":"Fresh dill"}','g'),
('Базилик зеленый','spices','{"ru":"Базилик зеленый","en":"Green basil"}','g'),
('Базилик фиолетовый','spices','{"ru":"Базилик фиолетовый","en":"Purple basil"}','g'),
('Кинза (кориандр)','spices','{"ru":"Кинза (кориандр)","en":"Fresh cilantro"}','g'),
('Тархун (эстрагон)','spices','{"ru":"Тархун (эстрагон)","en":"Tarragon"}','g'),
('Розмарин','spices','{"ru":"Розмарин","en":"Fresh rosemary"}','g'),
('Тимьян','spices','{"ru":"Тимьян","en":"Fresh thyme"}','g'),
('Орегано свежий','spices','{"ru":"Орегано свежий","en":"Fresh oregano"}','g'),
('Орегано сушеный','spices','{"ru":"Орегано сушеный","en":"Dried oregano"}','g'),
('Мята свежая','spices','{"ru":"Мята свежая","en":"Fresh mint"}','g'),
('Мята сухая','spices','{"ru":"Мята сухая","en":"Dried mint"}','g'),
('Мелисса','spices','{"ru":"Мелисса","en":"Lemon balm"}','g'),
('Шалфей свежий','spices','{"ru":"Шалфей свежий","en":"Fresh sage"}','g'),
('Шалфей сухой','spices','{"ru":"Шалфей сухой","en":"Dried sage"}','g'),
('Майоран свежий','spices','{"ru":"Майоран свежий","en":"Fresh marjoram"}','g'),
('Майоран сухой','spices','{"ru":"Майоран сухой","en":"Dried marjoram"}','g'),
('Чабрец','spices','{"ru":"Чабрец","en":"Wild thyme"}','g'),
('Лавровый лист','spices','{"ru":"Лавровый лист","en":"Bay leaf"}','g'),
('Лимонная трава (лемонграсс)','spices','{"ru":"Лимонная трава (лемонграсс)","en":"Lemongrass"}','g'),
('Листья лайма кафрского','spices','{"ru":"Листья лайма кафрского","en":"Kaffir lime leaves"}','g'),
('Листья карри','spices','{"ru":"Листья карри","en":"Curry leaves"}','g'),
('Пандан (листья)','spices','{"ru":"Пандан (листья)","en":"Pandan leaves"}','g'),
('Черемша','spices','{"ru":"Черемша","en":"Wild garlic (ramsons)"}','g'),
('Сельдерей (зелень)','spices','{"ru":"Сельдерей (зелень)","en":"Celery leaves"}','g'),
('Фенхель (зелень)','spices','{"ru":"Фенхель (зелень)","en":"Fennel fronds"}','g'),

-- ==================== МАСЛА ====================
('Масло оливковое Extra Virgin','oils','{"ru":"Масло оливковое Extra Virgin","en":"Extra virgin olive oil"}','ml'),
('Масло оливковое рафинированное','oils','{"ru":"Масло оливковое рафинированное","en":"Refined olive oil"}','ml'),
('Масло подсолнечное рафинированное','oils','{"ru":"Масло подсолнечное рафинированное","en":"Refined sunflower oil"}','ml'),
('Масло подсолнечное нерафинированное','oils','{"ru":"Масло подсолнечное нерафинированное","en":"Unrefined sunflower oil"}','ml'),
('Масло рапсовое','oils','{"ru":"Масло рапсовое","en":"Canola oil"}','ml'),
('Масло кукурузное','oils','{"ru":"Масло кукурузное","en":"Corn oil"}','ml'),
('Масло льняное','oils','{"ru":"Масло льняное","en":"Flaxseed oil"}','ml'),
('Масло кунжутное темное','oils','{"ru":"Масло кунжутное темное","en":"Dark sesame oil"}','ml'),
('Масло кунжутное светлое','oils','{"ru":"Масло кунжутное светлое","en":"Light sesame oil"}','ml'),
('Масло кокосовое рафинированное','oils','{"ru":"Масло кокосовое рафинированное","en":"Refined coconut oil"}','ml'),
('Масло кокосовое нерафинированное','oils','{"ru":"Масло кокосовое нерафинированное","en":"Virgin coconut oil"}','ml'),
('Масло авокадо','oils','{"ru":"Масло авокадо","en":"Avocado oil"}','ml'),
('Масло грецкого ореха','oils','{"ru":"Масло грецкого ореха","en":"Walnut oil"}','ml'),
('Масло арахисовое','oils','{"ru":"Масло арахисовое","en":"Peanut oil"}','ml'),
('Масло виноградных косточек','oils','{"ru":"Масло виноградных косточек","en":"Grapeseed oil"}','ml'),
('Масло тыквенных семечек','oils','{"ru":"Масло тыквенных семечек","en":"Pumpkin seed oil"}','ml'),
('Масло трюфельное','oils','{"ru":"Масло трюфельное","en":"Truffle oil"}','ml'),
('Масло чили','oils','{"ru":"Масло чили","en":"Chili oil"}','ml'),

-- ==================== УКСУСЫ ====================
('Уксус яблочный','pantry','{"ru":"Уксус яблочный","en":"Apple cider vinegar"}','ml'),
('Уксус винный белый','pantry','{"ru":"Уксус винный белый","en":"White wine vinegar"}','ml'),
('Уксус винный красный','pantry','{"ru":"Уксус винный красный","en":"Red wine vinegar"}','ml'),
('Уксус бальзамический','pantry','{"ru":"Уксус бальзамический","en":"Balsamic vinegar"}','ml'),
('Уксус бальзамический белый','pantry','{"ru":"Уксус бальзамический белый","en":"White balsamic vinegar"}','ml'),
('Уксус рисовый','pantry','{"ru":"Уксус рисовый","en":"Rice vinegar"}','ml'),
('Уксус рисовый черный','pantry','{"ru":"Уксус рисовый черный","en":"Black rice vinegar"}','ml'),
('Уксус хересный','pantry','{"ru":"Уксус хересный","en":"Sherry vinegar"}','ml'),
('Уксус солодовый','pantry','{"ru":"Уксус солодовый","en":"Malt vinegar"}','ml'),
('Уксус столовый 9%','pantry','{"ru":"Уксус столовый 9%","en":"Table vinegar 9%"}','ml'),

-- ==================== СОУСЫ И ПАСТЫ ====================
('Соевый соус (темный)','pantry','{"ru":"Соевый соус (темный)","en":"Dark soy sauce"}','ml'),
('Соевый соус (светлый)','pantry','{"ru":"Соевый соус (светлый)","en":"Light soy sauce"}','ml'),
('Соевый соус (тамари)','pantry','{"ru":"Соевый соус (тамари)","en":"Tamari soy sauce"}','ml'),
('Кокосовый амино','pantry','{"ru":"Кокосовый амино","en":"Coconut aminos"}','ml'),
('Соус устричный','pantry','{"ru":"Соус устричный","en":"Oyster sauce"}','ml'),
('Соус рыбный','pantry','{"ru":"Соус рыбный","en":"Fish sauce"}','ml'),
('Соус терияки','pantry','{"ru":"Соус терияки","en":"Teriyaki sauce"}','ml'),
('Соус хойсин','pantry','{"ru":"Соус хойсин","en":"Hoisin sauce"}','ml'),
('Соус понзу','pantry','{"ru":"Соус понзу","en":"Ponzu sauce"}','ml'),
('Соус ворчестер','pantry','{"ru":"Соус ворчестер","en":"Worcestershire sauce"}','ml'),
('Соус Табаско','pantry','{"ru":"Соус Табаско","en":"Tabasco sauce"}','ml'),
('Соус Шрирача','pantry','{"ru":"Соус Шрирача","en":"Sriracha sauce"}','ml'),
('Соус Харисса','pantry','{"ru":"Соус Харисса","en":"Harissa sauce"}','g'),
('Соус Гочуджан','pantry','{"ru":"Соус Гочуджан","en":"Gochujang sauce"}','g'),
('Паста томатная','pantry','{"ru":"Паста томатная","en":"Tomato paste"}','g'),
('Паста томатная двойная','pantry','{"ru":"Паста томатная двойная","en":"Double tomato paste"}','g'),
('Паста тапенад из оливок','pantry','{"ru":"Паста тапенад из оливок","en":"Olive tapenade"}','g'),
('Паста мисо белая','pantry','{"ru":"Паста мисо белая","en":"White miso paste"}','g'),
('Паста мисо красная','pantry','{"ru":"Паста мисо красная","en":"Red miso paste"}','g'),
('Паста мисо темная','pantry','{"ru":"Паста мисо темная","en":"Dark miso paste"}','g'),
('Паста анчоусная','pantry','{"ru":"Паста анчоусная","en":"Anchovy paste"}','g'),
('Горчица дижонская','pantry','{"ru":"Горчица дижонская","en":"Dijon mustard"}','g'),
('Горчица русская','pantry','{"ru":"Горчица русская","en":"Russian mustard"}','g'),
('Горчица зернистая','pantry','{"ru":"Горчица зернистая","en":"Whole grain mustard"}','g'),
('Горчица американская','pantry','{"ru":"Горчица американская","en":"American yellow mustard"}','g'),
('Майонез классический','pantry','{"ru":"Майонез классический","en":"Classic mayonnaise"}','g'),
('Кетчуп томатный','pantry','{"ru":"Кетчуп томатный","en":"Tomato ketchup"}','g'),
('Хумус','pantry','{"ru":"Хумус","en":"Hummus"}','g'),
('Баба-гануш','pantry','{"ru":"Баба-гануш","en":"Baba ganoush"}','g'),
('Дзадзики','pantry','{"ru":"Дзадзики","en":"Tzatziki"}','g'),
('Соус тартар','pantry','{"ru":"Соус тартар","en":"Tartar sauce"}','g'),
('Соус цезарь','pantry','{"ru":"Соус цезарь","en":"Caesar dressing"}','g'),
('Соус ранч','pantry','{"ru":"Соус ранч","en":"Ranch dressing"}','g'),
('Соус песто зеленый','pantry','{"ru":"Соус песто зеленый","en":"Green pesto sauce"}','g'),
('Соус песто красный','pantry','{"ru":"Соус песто красный","en":"Red pesto sauce"}','g'),
('Соус болоньезе (готовый)','pantry','{"ru":"Соус болоньезе (готовый)","en":"Bolognese sauce (ready)"}','g'),
('Соус барбекю','pantry','{"ru":"Соус барбекю","en":"BBQ sauce"}','g'),
('Соус Биск (из раков/лобстеров)','pantry','{"ru":"Соус Биск (из раков/лобстеров)","en":"Bisque sauce"}','ml'),

-- ==================== САХАР И ПОДСЛАСТИТЕЛИ ====================
('Сахар белый','pantry','{"ru":"Сахар белый","en":"White sugar"}','g'),
('Сахар коричневый (тростниковый)','pantry','{"ru":"Сахар коричневый (тростниковый)","en":"Brown cane sugar"}','g'),
('Сахар мусковадо темный','pantry','{"ru":"Сахар мусковадо темный","en":"Dark muscovado sugar"}','g'),
('Сахар демерара','pantry','{"ru":"Сахар демерара","en":"Demerara sugar"}','g'),
('Сахар пудра','pantry','{"ru":"Сахар пудра","en":"Powdered sugar (icing sugar)"}','g'),
('Сахар инвертный','pantry','{"ru":"Сахар инвертный","en":"Invert sugar"}','g'),
('Сироп глюкозы','pantry','{"ru":"Сироп глюкозы","en":"Glucose syrup"}','g'),
('Мед цветочный','pantry','{"ru":"Мед цветочный","en":"Floral honey"}','g'),
('Мед гречишный','pantry','{"ru":"Мед гречишный","en":"Buckwheat honey"}','g'),
('Мед акациевый','pantry','{"ru":"Мед акациевый","en":"Acacia honey"}','g'),
('Патока темная','pantry','{"ru":"Патока темная","en":"Dark molasses"}','g'),
('Патока светлая','pantry','{"ru":"Патока светлая","en":"Light corn syrup"}','g'),
('Кленовый сироп','pantry','{"ru":"Кленовый сироп","en":"Maple syrup"}','ml'),
('Агавовый сироп','pantry','{"ru":"Агавовый сироп","en":"Agave syrup"}','ml'),
('Сироп топинамбура','pantry','{"ru":"Сироп топинамбура","en":"Jerusalem artichoke syrup"}','ml'),
('Стевия','pantry','{"ru":"Стевия","en":"Stevia"}','g'),
('Эритрит','pantry','{"ru":"Эритрит","en":"Erythritol"}','g'),

-- ==================== СОЛЬ ====================
('Соль поваренная','spices','{"ru":"Соль поваренная","en":"Table salt"}','g'),
('Соль морская крупная','spices','{"ru":"Соль морская крупная","en":"Coarse sea salt"}','g'),
('Соль морская мелкая','spices','{"ru":"Соль морская мелкая","en":"Fine sea salt"}','g'),
('Соль розовая гималайская','spices','{"ru":"Соль розовая гималайская","en":"Pink Himalayan salt"}','g'),
('Соль черная (кала намак)','spices','{"ru":"Соль черная (кала намак)","en":"Black salt (kala namak)"}','g'),
('Соль копченая','spices','{"ru":"Соль копченая","en":"Smoked salt"}','g'),
('Флёр де сель','spices','{"ru":"Флёр де сель","en":"Fleur de sel"}','g'),
('Соль нитритная','spices','{"ru":"Соль нитритная","en":"Nitrite salt"}','g'),

-- ==================== ПАСТА И ЛАПША ====================
('Паста спагетти','grains','{"ru":"Паста спагетти","en":"Spaghetti pasta"}','g'),
('Паста пенне','grains','{"ru":"Паста пенне","en":"Penne pasta"}','g'),
('Паста фарфалле','grains','{"ru":"Паста фарфалле","en":"Farfalle pasta"}','g'),
('Паста фузилли','grains','{"ru":"Паста фузилли","en":"Fusilli pasta"}','g'),
('Паста ригатони','grains','{"ru":"Паста ригатони","en":"Rigatoni pasta"}','g'),
('Паста тальятелле','grains','{"ru":"Паста тальятелле","en":"Tagliatelle pasta"}','g'),
('Паста феттучини','grains','{"ru":"Паста феттучини","en":"Fettuccine pasta"}','g'),
('Паста папарделле','grains','{"ru":"Паста папарделле","en":"Pappardelle pasta"}','g'),
('Паста лазанья (листы)','grains','{"ru":"Паста лазанья (листы)","en":"Lasagna sheets"}','g'),
('Паста каннеллони','grains','{"ru":"Паста каннеллони","en":"Cannelloni pasta"}','g'),
('Паста орзо','grains','{"ru":"Паста орзо","en":"Orzo pasta"}','g'),
('Паста конкилье','grains','{"ru":"Паста конкилье","en":"Conchiglie pasta"}','g'),
('Паста лингвини','grains','{"ru":"Паста лингвини","en":"Linguine pasta"}','g'),
('Паста букатини','grains','{"ru":"Паста букатини","en":"Bucatini pasta"}','g'),
('Паста тортеллини','grains','{"ru":"Паста тортеллини","en":"Tortellini pasta"}','g'),
('Паста равиоли','grains','{"ru":"Паста равиоли","en":"Ravioli pasta"}','g'),
('Лапша рисовая широкая','grains','{"ru":"Лапша рисовая широкая","en":"Wide rice noodles"}','g'),
('Лапша рисовая тонкая (вермишель)','grains','{"ru":"Лапша рисовая тонкая (вермишель)","en":"Rice vermicelli"}','g'),
('Лапша гречневая (соба)','grains','{"ru":"Лапша гречневая (соба)","en":"Soba noodles"}','g'),
('Лапша пшеничная (удон)','grains','{"ru":"Лапша пшеничная (удон)","en":"Udon noodles"}','g'),
('Лапша яичная','grains','{"ru":"Лапша яичная","en":"Egg noodles"}','g'),
('Лапша стеклянная (фунчоза)','grains','{"ru":"Лапша стеклянная (фунчоза)","en":"Glass noodles (funchoza)"}','g'),
('Лапша рамен (сухая)','grains','{"ru":"Лапша рамен (сухая)","en":"Dry ramen noodles"}','g'),
('Ньокки','grains','{"ru":"Ньокки","en":"Gnocchi"}','g'),
('Кускус (крупный)','grains','{"ru":"Кускус (крупный)","en":"Large couscous (maftoul)"}','g'),

-- ==================== ХЛЕБ И ВЫПЕЧКА ====================
('Хлеб белый пшеничный','bakery','{"ru":"Хлеб белый пшеничный","en":"White wheat bread"}','g'),
('Хлеб ржаной','bakery','{"ru":"Хлеб ржаной","en":"Rye bread"}','g'),
('Хлеб бородинский','bakery','{"ru":"Хлеб бородинский","en":"Borodinsky bread"}','g'),
('Хлеб цельнозерновой','bakery','{"ru":"Хлеб цельнозерновой","en":"Whole grain bread"}','g'),
('Хлеб тостовый','bakery','{"ru":"Хлеб тостовый","en":"Toast bread"}','g'),
('Чиабатта','bakery','{"ru":"Чиабатта","en":"Ciabatta"}','g'),
('Фокачча','bakery','{"ru":"Фокачча","en":"Focaccia"}','g'),
('Багет французский','bakery','{"ru":"Багет французский","en":"French baguette"}','g'),
('Бриошь','bakery','{"ru":"Бриошь","en":"Brioche"}','g'),
('Питта','bakery','{"ru":"Питта","en":"Pita bread"}','g'),
('Лаваш тонкий','bakery','{"ru":"Лаваш тонкий","en":"Thin lavash"}','g'),
('Наан','bakery','{"ru":"Наан","en":"Naan bread"}','g'),
('Тортилья пшеничная','bakery','{"ru":"Тортилья пшеничная","en":"Wheat tortilla"}','g'),
('Тортилья кукурузная','bakery','{"ru":"Тортилья кукурузная","en":"Corn tortilla"}','g'),
('Крекер несоленый','bakery','{"ru":"Крекер несоленый","en":"Unsalted cracker"}','g'),
('Хлебцы ржаные','bakery','{"ru":"Хлебцы ржаные","en":"Rye crispbread"}','g'),

-- ==================== КОНСЕРВЫ ====================
('Томаты в собственном соку','pantry','{"ru":"Томаты в собственном соку","en":"Canned tomatoes in juice"}','g'),
('Томаты протертые (пассата)','pantry','{"ru":"Томаты протертые (пассата)","en":"Passata (crushed tomatoes)"}','g'),
('Фасоль белая консервированная','pantry','{"ru":"Фасоль белая консервированная","en":"Canned white beans"}','g'),
('Фасоль красная консервированная','pantry','{"ru":"Фасоль красная консервированная","en":"Canned red beans"}','g'),
('Горошек зеленый консервированный','pantry','{"ru":"Горошек зеленый консервированный","en":"Canned green peas"}','g'),
('Кукуруза консервированная','pantry','{"ru":"Кукуруза консервированная","en":"Canned corn"}','g'),
('Оливки консервированные (зеленые)','pantry','{"ru":"Оливки консервированные (зеленые)","en":"Canned green olives"}','g'),
('Артишоки консервированные','pantry','{"ru":"Артишоки консервированные","en":"Canned artichokes"}','g'),
('Тунец консервированный в масле','pantry','{"ru":"Тунец консервированный в масле","en":"Canned tuna in oil"}','g'),
('Тунец консервированный в соку','pantry','{"ru":"Тунец консервированный в соку","en":"Canned tuna in water"}','g'),
('Сардины консервированные','pantry','{"ru":"Сардины консервированные","en":"Canned sardines"}','g'),
('Лосось консервированный','pantry','{"ru":"Лосось консервированный","en":"Canned salmon"}','g'),

-- ==================== АЛКОГОЛЬ ДЛЯ КУЛИНАРИИ ====================
('Вино белое сухое (для готовки)','beverages','{"ru":"Вино белое сухое (для готовки)","en":"Dry white wine (for cooking)"}','ml'),
('Вино красное сухое (для готовки)','beverages','{"ru":"Вино красное сухое (для готовки)","en":"Dry red wine (for cooking)"}','ml'),
('Херес сухой','beverages','{"ru":"Херес сухой","en":"Dry sherry"}','ml'),
('Марсала','beverages','{"ru":"Марсала","en":"Marsala wine"}','ml'),
('Мирин','beverages','{"ru":"Мирин","en":"Mirin"}','ml'),
('Саке','beverages','{"ru":"Саке","en":"Sake"}','ml'),
('Коньяк (для готовки)','beverages','{"ru":"Коньяк (для готовки)","en":"Brandy (for cooking)"}','ml'),
('Ром темный','beverages','{"ru":"Ром темный","en":"Dark rum"}','ml'),
('Ром светлый','beverages','{"ru":"Ром светлый","en":"Light rum"}','ml'),
('Ликер Grand Marnier','beverages','{"ru":"Ликер Grand Marnier","en":"Grand Marnier liqueur"}','ml'),
('Ликер Амаретто','beverages','{"ru":"Ликер Амаретто","en":"Amaretto liqueur"}','ml'),
('Ликер Кофейный (Kahlua)','beverages','{"ru":"Ликер Кофейный (Kahlua)","en":"Coffee liqueur (Kahlua)"}','ml'),
('Портвейн','beverages','{"ru":"Портвейн","en":"Port wine"}','ml'),
('Пиво светлое (для готовки)','beverages','{"ru":"Пиво светлое (для готовки)","en":"Light beer (for cooking)"}','ml'),
('Пиво темное (для готовки)','beverages','{"ru":"Пиво темное (для готовки)","en":"Dark beer (for cooking)"}','ml'),

-- ==================== БЕЗАЛКОГОЛЬНЫЕ НАПИТКИ ====================
('Вода питьевая','beverages','{"ru":"Вода питьевая","en":"Drinking water"}','ml'),
('Вода газированная','beverages','{"ru":"Вода газированная","en":"Sparkling water"}','ml'),
('Бульон куриный','beverages','{"ru":"Бульон куриный","en":"Chicken broth"}','ml'),
('Бульон говяжий','beverages','{"ru":"Бульон говяжий","en":"Beef broth"}','ml'),
('Бульон овощной','beverages','{"ru":"Бульон овощной","en":"Vegetable broth"}','ml'),
('Бульон рыбный','beverages','{"ru":"Бульон рыбный","en":"Fish stock"}','ml'),
('Фумет (рыбный бульон)','beverages','{"ru":"Фумет (рыбный бульон)","en":"Fish fumet"}','ml'),
('Дашибульон (даши)','beverages','{"ru":"Дашибульон (даши)","en":"Dashi stock"}','ml'),
('Молоко кокосовое','beverages','{"ru":"Молоко кокосовое","en":"Coconut milk"}','ml'),
('Сок апельсиновый свежевыжатый','beverages','{"ru":"Сок апельсиновый свежевыжатый","en":"Freshly squeezed orange juice"}','ml'),
('Сок лимонный свежевыжатый','beverages','{"ru":"Сок лимонный свежевыжатый","en":"Freshly squeezed lemon juice"}','ml'),
('Сок лаймовый свежевыжатый','beverages','{"ru":"Сок лаймовый свежевыжатый","en":"Freshly squeezed lime juice"}','ml'),
('Сок томатный','beverages','{"ru":"Сок томатный","en":"Tomato juice"}','ml'),
('Сок гранатовый','beverages','{"ru":"Сок гранатовый","en":"Pomegranate juice"}','ml'),
('Кофе эспрессо','beverages','{"ru":"Кофе эспрессо","en":"Espresso coffee"}','ml'),
('Кофе молотый','beverages','{"ru":"Кофе молотый","en":"Ground coffee"}','g'),
('Кофе растворимый','beverages','{"ru":"Кофе растворимый","en":"Instant coffee"}','g'),
('Чай черный (листовой)','beverages','{"ru":"Чай черный (листовой)","en":"Black tea (loose leaf)"}','g'),
('Чай зеленый (листовой)','beverages','{"ru":"Чай зеленый (листовой)","en":"Green tea (loose leaf)"}','g'),
('Чай матча (порошок)','beverages','{"ru":"Чай матча (порошок)","en":"Matcha tea powder"}','g'),

-- ==================== ШОКОЛАД И КАКАО ====================
('Шоколад темный 70%','pantry','{"ru":"Шоколад темный 70%","en":"Dark chocolate 70%"}','g'),
('Шоколад темный 85%','pantry','{"ru":"Шоколад темный 85%","en":"Dark chocolate 85%"}','g'),
('Шоколад молочный','pantry','{"ru":"Шоколад молочный","en":"Milk chocolate"}','g'),
('Шоколад белый','pantry','{"ru":"Шоколад белый","en":"White chocolate"}','g'),
('Шоколад рубиновый','pantry','{"ru":"Шоколад рубиновый","en":"Ruby chocolate"}','g'),
('Шоколад горький 99%','pantry','{"ru":"Шоколад горький 99%","en":"Bitter chocolate 99%"}','g'),
('Какао-порошок натуральный','pantry','{"ru":"Какао-порошок натуральный","en":"Natural cocoa powder"}','g'),
('Какао-порошок алкализованный','pantry','{"ru":"Какао-порошок алкализованный","en":"Alkalized cocoa powder"}','g'),
('Какао-масло','pantry','{"ru":"Какао-масло","en":"Cocoa butter"}','g'),
('Какао-крупка','pantry','{"ru":"Какао-крупка","en":"Cacao nibs"}','g'),
('Шоколадные капли (темные)','pantry','{"ru":"Шоколадные капли (темные)","en":"Dark chocolate chips"}','g'),
('Шоколадные капли (белые)','pantry','{"ru":"Шоколадные капли (белые)","en":"White chocolate chips"}','g'),
('Нутелла','pantry','{"ru":"Нутелла","en":"Nutella"}','g'),
('Пралине (паста)','pantry','{"ru":"Пралине (паста)","en":"Praline paste"}','g'),
('Джандуйя','pantry','{"ru":"Джандуйя","en":"Gianduja"}','g'),

-- ==================== ЖЕЛИРУЮЩИЕ И ЭМУЛЬГАТОРЫ ====================
('Каррагинан','bakery','{"ru":"Каррагинан","en":"Carrageenan"}','g'),
('Метилцеллюлоза','bakery','{"ru":"Метилцеллюлоза","en":"Methylcellulose"}','g'),
('Лецитин соевый','bakery','{"ru":"Лецитин соевый","en":"Soy lecithin"}','g'),
('Моно- и диглицериды','bakery','{"ru":"Моно- и диглицериды","en":"Mono and diglycerides"}','g'),
('Инулин','bakery','{"ru":"Инулин","en":"Inulin"}','g'),

-- ==================== НОРИ И ВОДОРОСЛИ ====================
('Нори (листы для суши)','seafood','{"ru":"Нори (листы для суши)","en":"Nori sheets (for sushi)"}','g'),
('Вакаме (морская капуста)','seafood','{"ru":"Вакаме (морская капуста)","en":"Wakame seaweed"}','g'),
('Комбу','seafood','{"ru":"Комбу","en":"Kombu seaweed"}','g'),
('Хийки','seafood','{"ru":"Хийки","en":"Hijiki seaweed"}','g'),
('Фукус (морской виноград)','seafood','{"ru":"Фукус (морской виноград)","en":"Sea grapes (umibudo)"}','g'),
('Морская капуста маринованная','seafood','{"ru":"Морская капуста маринованная","en":"Pickled seaweed"}','g'),
('Агар (из водорослей)','bakery','{"ru":"Агар (из водорослей)","en":"Agar (seaweed-based)"}','g'),
('Спирулина','pantry','{"ru":"Спирулина","en":"Spirulina"}','g'),

-- ==================== ФЕРМЕНТИРОВАННЫЕ ПРОДУКТЫ ====================
('Кимчи','pantry','{"ru":"Кимчи","en":"Kimchi"}','g'),
('Квашеная капуста','pantry','{"ru":"Квашеная капуста","en":"Sauerkraut"}','g'),
('Соленые огурцы','pantry','{"ru":"Соленые огурцы","en":"Pickled cucumbers"}','g'),
('Маринованные огурцы','pantry','{"ru":"Маринованные огурцы","en":"Marinated cucumbers"}','g'),
('Каперберри','pantry','{"ru":"Каперберри","en":"Caperberries"}','g'),
('Оливки маринованные с травами','pantry','{"ru":"Оливки маринованные с травами","en":"Herb marinated olives"}','g'),
('Маринованный имбирь (гари)','pantry','{"ru":"Маринованный имбирь (гари)","en":"Pickled ginger (gari)"}','g'),
('Соленые лимоны','pantry','{"ru":"Соленые лимоны","en":"Preserved lemons"}','g'),
('Вустерская паста','pantry','{"ru":"Вустерская паста","en":"Worcestershire paste"}','g'),
('Мисо (суп-основа)','pantry','{"ru":"Мисо (суп-основа)","en":"Miso soup base"}','g'),
('Натто','pantry','{"ru":"Натто","en":"Natto"}','g'),

-- ==================== СНЭКИ И ПРОЧЕЕ ====================
('Чипсы картофельные','misc','{"ru":"Чипсы картофельные","en":"Potato chips"}','g'),
('Попкорн (зерна)','misc','{"ru":"Попкорн (зерна)","en":"Popcorn kernels"}','g'),
('Мюсли','misc','{"ru":"Мюсли","en":"Muesli"}','g'),
('Гранола','misc','{"ru":"Гранола","en":"Granola"}','g'),
('Протеиновый порошок ванильный','misc','{"ru":"Протеиновый порошок ванильный","en":"Vanilla protein powder"}','g'),
('Протеиновый порошок шоколадный','misc','{"ru":"Протеиновый порошок шоколадный","en":"Chocolate protein powder"}','g'),

-- ==================== АЗИАТСКИЕ ПРОДУКТЫ ====================
('Соус Pon Zu','pantry','{"ru":"Соус Pon Zu","en":"Pon Zu sauce"}','ml'),
('Юзу сок','pantry','{"ru":"Юзу сок","en":"Yuzu juice"}','ml'),
('Тонкацу соус','pantry','{"ru":"Тонкацу соус","en":"Tonkatsu sauce"}','ml'),
('Соус Kewpie (японский майонез)','pantry','{"ru":"Соус Kewpie (японский майонез)","en":"Kewpie mayonnaise"}','g'),
('Рисовая бумага (для роллов)','pantry','{"ru":"Рисовая бумага (для роллов)","en":"Rice paper (for rolls)"}','g'),
('Тофу жареный (абурааге)','legumes','{"ru":"Тофу жареный (абурааге)","en":"Fried tofu (aburage)"}','g'),
('Юба (пленка соевого молока)','legumes','{"ru":"Юба (пленка соевого молока)","en":"Yuba (tofu skin)"}','g'),
('Гочукару (хлопья корейского чили)','spices','{"ru":"Гочукару (хлопья корейского чили)","en":"Gochugaru (Korean chili flakes)"}','g'),
('Дашимото (порошок даши)','pantry','{"ru":"Дашимото (порошок даши)","en":"Dashi powder"}','g'),
('Бонито (стружка тунца)','seafood','{"ru":"Бонито (стружка тунца)","en":"Bonito flakes (katsuobushi)"}','g'),
('Сакура эби (сушеные креветки)','seafood','{"ru":"Сакура эби (сушеные креветки)","en":"Dried sakura shrimp"}','g'),
('Паста юдзу-косё','spices','{"ru":"Паста юдзу-косё","en":"Yuzu kosho paste"}','g'),
('Кочуджан (корейская паста)','pantry','{"ru":"Кочуджан (корейская паста)","en":"Gochujang paste"}','g'),
('Доенджан (корейская мисо)','pantry','{"ru":"Доенджан (корейская мисо)","en":"Doenjang paste"}','g'),
('Паста карри Массаман','spices','{"ru":"Паста карри Массаман","en":"Massaman curry paste"}','g'),
('Паста Nam Prik Pao','spices','{"ru":"Паста Nam Prik Pao","en":"Nam Prik Pao paste"}','g'),
('Галангал молотый','spices','{"ru":"Галангал молотый","en":"Ground galangal"}','g'),

-- ==================== МЯСНЫЕ ДЕЛИКАТЕСЫ ====================
('Прошутто крудо','meat','{"ru":"Прошутто крудо","en":"Prosciutto crudo"}','g'),
('Прошутто котто','meat','{"ru":"Прошутто котто","en":"Prosciutto cotto"}','g'),
('Панчетта','meat','{"ru":"Панчетта","en":"Pancetta"}','g'),
('Гуанчале','meat','{"ru":"Гуанчале","en":"Guanciale"}','g'),
('Мортаделла','meat','{"ru":"Мортаделла","en":"Mortadella"}','g'),
('Брезаола','meat','{"ru":"Брезаола","en":"Bresaola"}','g'),
('Коппа','meat','{"ru":"Коппа","en":"Coppa (cured pork neck)"}','g'),
('Хамон серрано','meat','{"ru":"Хамон серрано","en":"Jamon serrano"}','g'),
('Хамон иберико','meat','{"ru":"Хамон иберико","en":"Jamon iberico"}','g'),
('Хорватская колбаса куленова','meat','{"ru":"Хорватская колбаса куленова","en":"Kulen sausage"}','g'),
('Чоризо (сырокопченая)','meat','{"ru":"Чоризо (сырокопченая)","en":"Chorizo (dry-cured)"}','g'),
('Чоризо (свежая)','meat','{"ru":"Чоризо (свежая)","en":"Fresh chorizo sausage"}','g'),
('Салями','meat','{"ru":"Салями","en":"Salami"}','g'),
('Пепперони','meat','{"ru":"Пепперони","en":"Pepperoni"}','g'),
('Сервелат','meat','{"ru":"Сервелат","en":"Cervelat sausage"}','g'),
('Колбаса охотничья','meat','{"ru":"Колбаса охотничья","en":"Hunting sausage"}','g'),
('Колбаски баварские (вайсвурст)','meat','{"ru":"Колбаски баварские (вайсвурст)","en":"Bavarian white sausage"}','g'),
('Сосиски куриные','meat','{"ru":"Сосиски куриные","en":"Chicken sausages"}','g'),
('Сосиски говяжьи','meat','{"ru":"Сосиски говяжьи","en":"Beef hot dogs"}','g'),
('Котлеты (полуфабрикат)','meat','{"ru":"Котлеты (полуфабрикат)","en":"Meat patties (semi-finished)"}','g'),
('Люля-кебаб (полуфабрикат)','meat','{"ru":"Люля-кебаб (полуфабрикат)","en":"Lula kebab (semi-finished)"}','g')

) as v(name, category, names, unit)
where not exists (
  select 1 from products p where lower(p.name) = lower(v.name)
);
