-- Журнал сеансов системной техподдержки (вход/выход) для владельца заведения.

CREATE TABLE IF NOT EXISTS public.support_access_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  establishment_id uuid NOT NULL REFERENCES public.establishments(id) ON DELETE CASCADE,
  support_operator_login text NOT NULL,
  account_login text NOT NULL,
  pin_code text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.support_access_audit_log IS
  'Журнал входов/выходов техподдержки в режим поддержки по заведению.';

CREATE INDEX IF NOT EXISTS idx_support_access_audit_est_started
  ON public.support_access_audit_log(establishment_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_support_access_audit_active
  ON public.support_access_audit_log(establishment_id)
  WHERE ended_at IS NULL;

ALTER TABLE public.support_access_audit_log ENABLE ROW LEVEL SECURITY;

-- Владельцы видят журнал только своего текущего заведения.
CREATE POLICY support_access_audit_owner_select
ON public.support_access_audit_log
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.employees e
    WHERE e.id = auth.uid()
      AND e.establishment_id = support_access_audit_log.establishment_id
      AND e.is_active = true
      AND 'owner' = ANY(e.roles)
  )
);
