-- DISABLED: Удаляла всех кроме stassser — ломала реальных пользователей.
-- rebrikov.st@gmail.com и др. были в auth.users, но удалены из employees.
-- Оставлено как no-op; для очистки — запускать вручную с осторожностью.
-- Оригинал:
-- UPDATE establishments SET owner_id = NULL WHERE owner_id IN (...);
-- DELETE FROM password_reset_tokens WHERE ...;
-- DELETE FROM employees WHERE LOWER(TRIM(email)) != 'stassser@gmail.com';