-- Единый журнал действий доступа техподдержки:
-- owner_enabled_access / owner_disabled_access / support_login / support_logout.

CREATE TABLE IF NOT EXISTS public.support_access_event_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  establishment_id uuid NOT NULL REFERENCES public.establishments(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (
    event_type IN (
      'owner_enabled_access',
      'owner_disabled_access',
      'support_login',
      'support_logout'
    )
  ),
  support_operator_login text,
  account_login text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_support_access_event_est_time
  ON public.support_access_event_log(establishment_id, created_at DESC);

ALTER TABLE public.support_access_event_log ENABLE ROW LEVEL SECURITY;

-- Владелец видит журнал только своего заведения.
CREATE POLICY support_access_event_owner_select
ON public.support_access_event_log
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.employees e
    WHERE e.id = auth.uid()
      AND e.establishment_id = support_access_event_log.establishment_id
      AND e.is_active = true
      AND 'owner' = ANY(e.roles)
  )
);

-- Владелец может писать только события включения/выключения доступа своего заведения.
CREATE POLICY support_access_event_owner_insert
ON public.support_access_event_log
FOR INSERT
TO authenticated
WITH CHECK (
  event_type IN ('owner_enabled_access', 'owner_disabled_access')
  AND EXISTS (
    SELECT 1
    FROM public.employees e
    WHERE e.id = auth.uid()
      AND e.establishment_id = support_access_event_log.establishment_id
      AND e.is_active = true
      AND 'owner' = ANY(e.roles)
  )
);
