#!/usr/bin/env python3
"""
Четвёртая партия: продукты для достижения 3000.
Фокус: разные сорта основных продуктов, региональные специалитеты,
полуфабрикаты, готовые соусы, кулинарные полуфабрикаты.
"""
import json

EXTRA4 = [
    # ─── Мясо полуфабрикаты и разделка ───────────────────────────────────────
    {"name": "Котлетное мясо говяжье", "en": "Ground Beef Patty Meat", "category": "meat", "unit": "g", "calories": 250, "protein": 17.0, "fat": 20.0, "carbs": 0.0},
    {"name": "Фарш говяжий 80/20", "en": "Beef Mince 80/20", "category": "meat", "unit": "g", "calories": 250, "protein": 17.0, "fat": 20.0, "carbs": 0.0},
    {"name": "Фарш свиной", "en": "Pork Ground Mince", "category": "meat", "unit": "g", "calories": 263, "protein": 16.9, "fat": 21.5, "carbs": 0.0},
    {"name": "Фарш смешанный говядина-свинина", "en": "Mixed Beef Pork Mince", "category": "meat", "unit": "g", "calories": 241, "protein": 17.0, "fat": 19.0, "carbs": 0.0},
    {"name": "Фарш куриный", "en": "Chicken Ground Mince", "category": "poultry", "unit": "g", "calories": 143, "protein": 17.0, "fat": 8.0, "carbs": 0.0},
    {"name": "Фарш из индейки", "en": "Turkey Ground Mince", "category": "poultry", "unit": "g", "calories": 170, "protein": 22.0, "fat": 9.0, "carbs": 0.0},
    {"name": "Фарш бараний", "en": "Lamb Ground Mince", "category": "meat", "unit": "g", "calories": 235, "protein": 17.0, "fat": 18.0, "carbs": 0.0},
    {"name": "Куриная грудка без кожи без кости", "en": "Skinless Boneless Chicken Breast", "category": "poultry", "unit": "g", "calories": 165, "protein": 31.0, "fat": 3.6, "carbs": 0.0},
    {"name": "Куриное бедро без кожи без кости", "en": "Skinless Boneless Chicken Thigh", "category": "poultry", "unit": "g", "calories": 209, "protein": 26.0, "fat": 10.9, "carbs": 0.0},
    {"name": "Куриное филе малое", "en": "Chicken Tender Mini Fillet", "category": "poultry", "unit": "g", "calories": 120, "protein": 24.5, "fat": 2.5, "carbs": 0.0},
    {"name": "Стейк из говядины мраморный", "en": "Marbled Wagyu Beef Steak", "category": "meat", "unit": "g", "calories": 350, "protein": 22.0, "fat": 28.5, "carbs": 0.0},
    {"name": "Антрекот говяжий", "en": "Beef Entrecote Rib Steak", "category": "meat", "unit": "g", "calories": 220, "protein": 26.0, "fat": 12.5, "carbs": 0.0},
    {"name": "Ростбиф говяжий", "en": "Beef Roast Beef Cut", "category": "meat", "unit": "g", "calories": 175, "protein": 26.0, "fat": 7.5, "carbs": 0.0},
    {"name": "Мясо для гуляша говяжье", "en": "Beef Goulash Stew Cut", "category": "meat", "unit": "g", "calories": 200, "protein": 22.0, "fat": 11.5, "carbs": 0.0},
    {"name": "Грудинка говяжья копчёная", "en": "Smoked Beef Brisket BBQ", "category": "meat", "unit": "g", "calories": 238, "protein": 24.0, "fat": 15.5, "carbs": 0.5},
    {"name": "Свиная корейка на кости", "en": "Pork Chop Bone-in", "category": "meat", "unit": "g", "calories": 231, "protein": 20.0, "fat": 16.0, "carbs": 0.0},
    {"name": "Свиной стейк из лопатки", "en": "Pork Shoulder Blade Steak", "category": "meat", "unit": "g", "calories": 258, "protein": 19.0, "fat": 20.0, "carbs": 0.0},
    {"name": "Рёбра свиные запасные", "en": "Pork Spare Ribs Rack", "category": "meat", "unit": "g", "calories": 312, "protein": 19.0, "fat": 26.0, "carbs": 0.0},
    {"name": "Рёбра говяжьи короткие", "en": "Beef Short Ribs", "category": "meat", "unit": "g", "calories": 295, "protein": 18.0, "fat": 25.0, "carbs": 0.0},

    # ─── Рыба нарезка и переработка ───────────────────────────────────────────
    {"name": "Лосось стейк на кости", "en": "Salmon Steak Bone-in", "category": "fish", "unit": "g", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0.0},
    {"name": "Лосось филе без кожи", "en": "Salmon Fillet Skinless", "category": "fish", "unit": "g", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0.0},
    {"name": "Форель стейк", "en": "Rainbow Trout Steak", "category": "fish", "unit": "g", "calories": 148, "protein": 20.0, "fat": 7.0, "carbs": 0.0},
    {"name": "Треска филе без кожи", "en": "Cod Fillet Skinless", "category": "fish", "unit": "g", "calories": 82, "protein": 18.0, "fat": 0.7, "carbs": 0.0},
    {"name": "Минтай филе замороженное", "en": "Pollock Fillet Frozen", "category": "fish", "unit": "g", "calories": 72, "protein": 17.0, "fat": 0.9, "carbs": 0.0},
    {"name": "Скумбрия солёная", "en": "Salted Mackerel Fish", "category": "fish", "unit": "g", "calories": 221, "protein": 18.0, "fat": 16.5, "carbs": 0.0},
    {"name": "Сельдь малосольная", "en": "Lightly Salted Herring", "category": "fish", "unit": "g", "calories": 145, "protein": 17.5, "fat": 8.5, "carbs": 0.0},
    {"name": "Тунец стейк свежий", "en": "Fresh Bluefin Tuna Steak", "category": "fish", "unit": "g", "calories": 144, "protein": 23.0, "fat": 5.0, "carbs": 0.0},
    {"name": "Лосось копчёный холодного", "en": "Cold Smoked Salmon Sliced", "category": "fish", "unit": "g", "calories": 117, "protein": 18.3, "fat": 4.3, "carbs": 0.0},
    {"name": "Лосось копчёный горячего", "en": "Hot Smoked Salmon Fillet", "category": "fish", "unit": "g", "calories": 162, "protein": 22.0, "fat": 8.0, "carbs": 0.0},
    {"name": "Форель радужная целая", "en": "Whole Rainbow Trout", "category": "fish", "unit": "g", "calories": 148, "protein": 20.0, "fat": 7.0, "carbs": 0.0},
    {"name": "Сом американский catfish", "en": "American Channel Catfish", "category": "fish", "unit": "g", "calories": 95, "protein": 16.4, "fat": 2.8, "carbs": 0.0},
    {"name": "Окунь морской красный", "en": "Red Snapper Ocean Perch", "category": "fish", "unit": "g", "calories": 100, "protein": 20.5, "fat": 1.3, "carbs": 0.0},
    {"name": "Дорада целая свежая", "en": "Whole Fresh Sea Bream", "category": "fish", "unit": "g", "calories": 96, "protein": 18.0, "fat": 2.9, "carbs": 0.0},
    {"name": "Сибас целый свежий", "en": "Whole Fresh Sea Bass Branzino", "category": "fish", "unit": "g", "calories": 97, "protein": 19.0, "fat": 2.0, "carbs": 0.0},

    # ─── Морепродукты различные ───────────────────────────────────────────────
    {"name": "Тигровые креветки очищенные", "en": "Peeled Tiger Prawns", "category": "seafood", "unit": "g", "calories": 100, "protein": 20.0, "fat": 1.5, "carbs": 0.9},
    {"name": "Королевские креветки в панцире", "en": "Shell-on King Prawns Raw", "category": "seafood", "unit": "g", "calories": 83, "protein": 18.0, "fat": 0.9, "carbs": 0.0},
    {"name": "Мини-крабы шанхайские", "en": "Shanghai Hairy Mini Crab", "category": "seafood", "unit": "g", "calories": 103, "protein": 17.5, "fat": 2.6, "carbs": 2.3},
    {"name": "Мидии в раковинах", "en": "Live Mussels in Shell", "category": "seafood", "unit": "g", "calories": 86, "protein": 12.0, "fat": 2.7, "carbs": 3.7},
    {"name": "Устрицы на льду", "en": "Fresh Oysters on Ice", "category": "seafood", "unit": "g", "calories": 68, "protein": 7.0, "fat": 2.5, "carbs": 3.9},
    {"name": "Морской гребешок в раковине", "en": "Scallop in Shell Half", "category": "seafood", "unit": "g", "calories": 69, "protein": 13.0, "fat": 0.5, "carbs": 2.4},
    {"name": "Мидии в соусе маринара", "en": "Mussels Marinara Cooked", "category": "seafood", "unit": "g", "calories": 120, "protein": 12.5, "fat": 5.5, "carbs": 4.8},
    {"name": "Кальмар кольца", "en": "Squid Rings Cleaned", "category": "seafood", "unit": "g", "calories": 92, "protein": 18.0, "fat": 1.4, "carbs": 2.0},
    {"name": "Осьминог щупальца", "en": "Octopus Tentacles", "category": "seafood", "unit": "g", "calories": 164, "protein": 30.0, "fat": 2.1, "carbs": 4.4},
    {"name": "Лангустин очищенный", "en": "Cleaned Norway Lobster", "category": "seafood", "unit": "g", "calories": 90, "protein": 19.0, "fat": 1.0, "carbs": 0.0},

    # ─── Сырые яйца и яичные продукты ────────────────────────────────────────
    {"name": "Яйцо куриное C0", "en": "Chicken Egg Size XL C0", "category": "eggs", "unit": "g", "calories": 157, "protein": 12.7, "fat": 11.5, "carbs": 0.7},
    {"name": "Яйцо куриное C1", "en": "Chicken Egg Size L C1", "category": "eggs", "unit": "g", "calories": 157, "protein": 12.7, "fat": 11.5, "carbs": 0.7},
    {"name": "Яйцо куриное C2", "en": "Chicken Egg Size M C2", "category": "eggs", "unit": "g", "calories": 157, "protein": 12.7, "fat": 11.5, "carbs": 0.7},
    {"name": "Яйцо деревенское домашнее", "en": "Free Range Farm Egg", "category": "eggs", "unit": "g", "calories": 160, "protein": 12.5, "fat": 12.0, "carbs": 0.7},
    {"name": "Яйцо органическое", "en": "Organic Pasture-Raised Egg", "category": "eggs", "unit": "g", "calories": 160, "protein": 12.5, "fat": 12.0, "carbs": 0.7},
    {"name": "Перепелиные яйца варёные", "en": "Hard Boiled Quail Eggs", "category": "eggs", "unit": "g", "calories": 168, "protein": 13.1, "fat": 11.1, "carbs": 0.6},
    {"name": "Меланж яичный пастеризованный", "en": "Pasteurized Liquid Egg Blend", "category": "eggs", "unit": "g", "calories": 159, "protein": 12.7, "fat": 11.5, "carbs": 0.7},
    {"name": "Желток яичный пастеризованный", "en": "Pasteurized Liquid Egg Yolk", "category": "eggs", "unit": "g", "calories": 339, "protein": 16.4, "fat": 29.8, "carbs": 1.1},
    {"name": "Белок яичный пастеризованный", "en": "Pasteurized Liquid Egg White", "category": "eggs", "unit": "g", "calories": 52, "protein": 10.9, "fat": 0.2, "carbs": 0.7},

    # ─── Молочные продукты расширение ────────────────────────────────────────
    {"name": "Сыр гауда молодой", "en": "Young Gouda Cheese 4 Week", "category": "dairy", "unit": "g", "calories": 356, "protein": 25.0, "fat": 27.4, "carbs": 2.2},
    {"name": "Сыр гауда выдержанный", "en": "Aged Gouda Cheese 12 Month", "category": "dairy", "unit": "g", "calories": 395, "protein": 27.0, "fat": 31.7, "carbs": 3.0},
    {"name": "Сыр эдам классический", "en": "Classic Edam Ball Cheese", "category": "dairy", "unit": "g", "calories": 357, "protein": 25.0, "fat": 27.8, "carbs": 1.4},
    {"name": "Сыр чеддер белый", "en": "White Cheddar Cheese", "category": "dairy", "unit": "g", "calories": 403, "protein": 25.0, "fat": 33.1, "carbs": 1.3},
    {"name": "Сыр чеддер выдержанный", "en": "Aged Sharp Cheddar Cheese", "category": "dairy", "unit": "g", "calories": 409, "protein": 24.9, "fat": 33.8, "carbs": 1.3},
    {"name": "Сыр моцарелла бочонок", "en": "Fresh Mozzarella Ball Fior", "category": "dairy", "unit": "g", "calories": 280, "protein": 17.0, "fat": 22.0, "carbs": 2.2},
    {"name": "Сыр страчателла", "en": "Stracciatella Fresh Cream Cheese", "category": "dairy", "unit": "g", "calories": 345, "protein": 10.8, "fat": 32.5, "carbs": 2.7},
    {"name": "Сыр буррата", "en": "Burrata Fresh Mozzarella Cream", "category": "dairy", "unit": "g", "calories": 330, "protein": 13.0, "fat": 29.0, "carbs": 3.0},
    {"name": "Сыр скаморца", "en": "Scamorza Smoked Spun Cheese", "category": "dairy", "unit": "g", "calories": 334, "protein": 25.0, "fat": 25.5, "carbs": 1.0},
    {"name": "Сыр рикотта свежая", "en": "Fresh Whole Milk Ricotta", "category": "dairy", "unit": "g", "calories": 174, "protein": 11.0, "fat": 13.0, "carbs": 3.0},
    {"name": "Сыр творожный типа филадельфия", "en": "Philadelphia Style Cream Cheese", "category": "dairy", "unit": "g", "calories": 350, "protein": 6.0, "fat": 33.0, "carbs": 4.0},
    {"name": "Масло топлёное русское", "en": "Russian Clarified Butter Topljoye", "category": "dairy", "unit": "g", "calories": 887, "protein": 0.3, "fat": 99.0, "carbs": 0.0},
    {"name": "Сметана 30%", "en": "Rich Sour Cream 30% Fat", "category": "dairy", "unit": "g", "calories": 294, "protein": 2.4, "fat": 30.0, "carbs": 3.1},
    {"name": "Сливки взбитые 35%", "en": "Double Cream 35% Whipping", "category": "dairy", "unit": "g", "calories": 352, "protein": 2.1, "fat": 36.0, "carbs": 3.0},
    {"name": "Молоко безлактозное", "en": "Lactose Free Cow Milk", "category": "dairy", "unit": "g", "calories": 47, "protein": 3.2, "fat": 1.5, "carbs": 5.1},
    {"name": "Творог зернёный", "en": "Granular Curd Cottage Cheese", "category": "dairy", "unit": "g", "calories": 105, "protein": 12.0, "fat": 5.0, "carbs": 2.5},

    # ─── Хлеб и выпечка расширение ────────────────────────────────────────────
    {"name": "Хлеб ржаной бородинский", "en": "Russian Borodino Dark Rye Bread", "category": "bakery", "unit": "g", "calories": 207, "protein": 6.8, "fat": 1.3, "carbs": 40.7},
    {"name": "Хлеб финский ржаной", "en": "Finnish Rye Crispbread", "category": "bakery", "unit": "g", "calories": 310, "protein": 9.0, "fat": 1.5, "carbs": 66.0},
    {"name": "Хлеб многозерновой", "en": "Multigrain Seeded Bread", "category": "bakery", "unit": "g", "calories": 251, "protein": 10.5, "fat": 4.5, "carbs": 42.0},
    {"name": "Хлеб с семенами чиа", "en": "Chia Seed Health Bread", "category": "bakery", "unit": "g", "calories": 268, "protein": 10.0, "fat": 7.0, "carbs": 42.0},
    {"name": "Батон нарезной", "en": "Sliced White Loaf Bread", "category": "bakery", "unit": "g", "calories": 264, "protein": 8.1, "fat": 3.0, "carbs": 50.5},
    {"name": "Лепёшка тандырная", "en": "Tandoor Flatbread Lepyoshka", "category": "bakery", "unit": "g", "calories": 298, "protein": 7.5, "fat": 5.5, "carbs": 57.0},
    {"name": "Лаваш тонкий армянский", "en": "Armenian Thin Lavash Sheet", "category": "bakery", "unit": "g", "calories": 276, "protein": 8.1, "fat": 1.1, "carbs": 57.1},
    {"name": "Лаваш толстый грузинский", "en": "Georgian Thick Puri Bread", "category": "bakery", "unit": "g", "calories": 250, "protein": 8.0, "fat": 1.5, "carbs": 51.0},
    {"name": "Маца иудейская", "en": "Matzo Jewish Unleavened Bread", "category": "bakery", "unit": "g", "calories": 395, "protein": 10.0, "fat": 1.3, "carbs": 84.0},
    {"name": "Питта греческая", "en": "Greek Pita Pocket Bread", "category": "bakery", "unit": "g", "calories": 275, "protein": 9.0, "fat": 1.2, "carbs": 56.0},
    {"name": "Маффин американский", "en": "American Blueberry Muffin", "category": "bakery", "unit": "g", "calories": 377, "protein": 5.0, "fat": 14.0, "carbs": 59.0},
    {"name": "Панетоне рождественский", "en": "Italian Panettone Christmas", "category": "bakery", "unit": "g", "calories": 350, "protein": 7.2, "fat": 11.0, "carbs": 55.0},
    {"name": "Стрюдель яблочный", "en": "Austrian Apple Strudel Pastry", "category": "bakery", "unit": "g", "calories": 213, "protein": 4.0, "fat": 8.5, "carbs": 33.0},
    {"name": "Эклер заварной", "en": "Classic Cream Eclair Pastry", "category": "bakery", "unit": "g", "calories": 262, "protein": 6.0, "fat": 13.0, "carbs": 30.0},

    # ─── Десерты и сладкие соусы ─────────────────────────────────────────────
    {"name": "Мороженое шоколадное", "en": "Chocolate Ice Cream", "category": "sweets", "unit": "g", "calories": 216, "protein": 3.8, "fat": 11.0, "carbs": 28.0},
    {"name": "Мороженое клубничное", "en": "Strawberry Ice Cream", "category": "sweets", "unit": "g", "calories": 192, "protein": 3.2, "fat": 8.5, "carbs": 28.0},
    {"name": "Мороженое фисташковое", "en": "Pistachio Gelato", "category": "sweets", "unit": "g", "calories": 220, "protein": 4.5, "fat": 11.5, "carbs": 27.0},
    {"name": "Джелато ванильное", "en": "Vanilla Italian Gelato", "category": "sweets", "unit": "g", "calories": 188, "protein": 4.0, "fat": 8.0, "carbs": 27.0},
    {"name": "Парфе клубничное", "en": "Strawberry Parfait Frozen", "category": "sweets", "unit": "g", "calories": 180, "protein": 3.0, "fat": 9.0, "carbs": 24.0},
    {"name": "Торт бисквитный основа", "en": "Sponge Cake Base Layer", "category": "sweets", "unit": "g", "calories": 350, "protein": 7.5, "fat": 10.0, "carbs": 58.0},
    {"name": "Торт Прага шоколадный", "en": "Prague Chocolate Cake", "category": "sweets", "unit": "g", "calories": 420, "protein": 5.5, "fat": 22.0, "carbs": 52.0},
    {"name": "Чизкейк нью-йоркский", "en": "New York Cheesecake Classic", "category": "sweets", "unit": "g", "calories": 315, "protein": 5.5, "fat": 22.0, "carbs": 25.0},
    {"name": "Тирамису итальянский", "en": "Italian Tiramisu Dessert", "category": "sweets", "unit": "g", "calories": 310, "protein": 5.0, "fat": 20.0, "carbs": 28.0},
    {"name": "Панна котта", "en": "Panna Cotta Italian Cream", "category": "sweets", "unit": "g", "calories": 210, "protein": 3.5, "fat": 15.0, "carbs": 16.5},
    {"name": "Буш де Ноэль", "en": "Buche de Noel Yule Log", "category": "sweets", "unit": "g", "calories": 380, "protein": 5.5, "fat": 19.5, "carbs": 48.0},
    {"name": "Опера торт французский", "en": "Opera French Coffee Cake", "category": "sweets", "unit": "g", "calories": 395, "protein": 6.0, "fat": 22.0, "carbs": 46.0},
    {"name": "Сахарный сироп 2:1", "en": "Simple Syrup 2 to 1 Sugar", "category": "sweets", "unit": "g", "calories": 252, "protein": 0.0, "fat": 0.0, "carbs": 63.0},
    {"name": "Соус шоколадный тёплый", "en": "Warm Chocolate Fudge Sauce", "category": "sweets", "unit": "g", "calories": 350, "protein": 3.5, "fat": 15.0, "carbs": 55.0},
    {"name": "Соус карамельный сливочный", "en": "Salted Caramel Butterscotch Sauce", "category": "sweets", "unit": "g", "calories": 340, "protein": 2.5, "fat": 12.0, "carbs": 57.0},
    {"name": "Соус малиновый кули", "en": "Raspberry Coulis Sauce", "category": "sweets", "unit": "g", "calories": 85, "protein": 1.0, "fat": 0.3, "carbs": 22.0},
    {"name": "Соус клубничный кули", "en": "Strawberry Coulis Sauce", "category": "sweets", "unit": "g", "calories": 75, "protein": 0.7, "fat": 0.2, "carbs": 19.5},
    {"name": "Соус манговый кули", "en": "Mango Tropical Coulis", "category": "sweets", "unit": "g", "calories": 95, "protein": 0.8, "fat": 0.4, "carbs": 24.0},

    # ─── Напитки горячие ─────────────────────────────────────────────────────
    {"name": "Кофе эспрессо порция", "en": "Single Espresso Shot", "category": "beverages", "unit": "g", "calories": 2, "protein": 0.3, "fat": 0.0, "carbs": 0.3},
    {"name": "Кофе американо", "en": "Americano Black Coffee", "category": "beverages", "unit": "g", "calories": 5, "protein": 0.3, "fat": 0.0, "carbs": 0.6},
    {"name": "Кофе капучино молоко", "en": "Cappuccino Milk Foam Coffee", "category": "beverages", "unit": "g", "calories": 50, "protein": 2.5, "fat": 2.5, "carbs": 4.5},
    {"name": "Кофе латте молоко", "en": "Latte Milk Coffee Drink", "category": "beverages", "unit": "g", "calories": 60, "protein": 3.0, "fat": 2.8, "carbs": 6.0},
    {"name": "Какао с молоком", "en": "Cocoa Hot Milk Drink", "category": "beverages", "unit": "g", "calories": 90, "protein": 3.0, "fat": 4.0, "carbs": 11.0},
    {"name": "Сироп ванильный для кофе", "en": "Vanilla Coffee Flavoring Syrup", "category": "beverages", "unit": "g", "calories": 280, "protein": 0.0, "fat": 0.0, "carbs": 70.0},
    {"name": "Сироп карамельный для кофе", "en": "Caramel Coffee Syrup", "category": "beverages", "unit": "g", "calories": 300, "protein": 0.0, "fat": 0.0, "carbs": 75.0},
    {"name": "Сироп лесной орех", "en": "Hazelnut Coffee Syrup", "category": "beverages", "unit": "g", "calories": 280, "protein": 0.0, "fat": 0.0, "carbs": 70.0},
    {"name": "Молоко кокосовое для лате", "en": "Barista Coconut Milk Coffee", "category": "beverages", "unit": "g", "calories": 45, "protein": 0.3, "fat": 4.0, "carbs": 2.5},
    {"name": "Молоко овсяное для лате", "en": "Barista Oat Milk Coffee", "category": "beverages", "unit": "g", "calories": 50, "protein": 1.0, "fat": 1.5, "carbs": 7.5},

    # ─── Дополнительные соусы и заправки ─────────────────────────────────────
    {"name": "Соус долмио томатный", "en": "Tomato Basil Pasta Sauce", "category": "sauces", "unit": "g", "calories": 52, "protein": 1.8, "fat": 1.0, "carbs": 9.3},
    {"name": "Соус карнарозо итальянский", "en": "Italian Arrabbiata Spicy Sauce", "category": "sauces", "unit": "g", "calories": 68, "protein": 2.2, "fat": 2.0, "carbs": 11.0},
    {"name": "Сальса вердэ зелёная", "en": "Italian Salsa Verde Green", "category": "sauces", "unit": "g", "calories": 134, "protein": 1.5, "fat": 13.0, "carbs": 3.5},
    {"name": "Соус ромеско каталанский", "en": "Catalan Romesco Sauce", "category": "sauces", "unit": "g", "calories": 198, "protein": 3.5, "fat": 16.5, "carbs": 11.0},
    {"name": "Соус питтсбург", "en": "Pittsburgh Steak Sauce", "category": "sauces", "unit": "g", "calories": 52, "protein": 0.8, "fat": 0.2, "carbs": 12.5},
    {"name": "Соус хреновина", "en": "Khrenovina Russian Horseradish", "category": "sauces", "unit": "g", "calories": 65, "protein": 1.8, "fat": 1.5, "carbs": 13.0},
    {"name": "Соус чесночный белый", "en": "White Garlic Cream Sauce", "category": "sauces", "unit": "g", "calories": 145, "protein": 2.5, "fat": 12.0, "carbs": 8.0},
    {"name": "Соус сливочный с грибами", "en": "Creamy Mushroom Sauce", "category": "sauces", "unit": "g", "calories": 98, "protein": 2.0, "fat": 8.0, "carbs": 5.5},
    {"name": "Соус демигляс тёмный", "en": "Brown Demi Glace Sauce", "category": "sauces", "unit": "g", "calories": 40, "protein": 3.0, "fat": 1.5, "carbs": 4.5},
    {"name": "Соус велюте белый", "en": "White Veloute Sauce Base", "category": "sauces", "unit": "g", "calories": 75, "protein": 3.5, "fat": 4.0, "carbs": 6.5},
    {"name": "Соус субиз луковый", "en": "Soubise Onion Cream Sauce", "category": "sauces", "unit": "g", "calories": 88, "protein": 2.5, "fat": 5.0, "carbs": 9.0},
    {"name": "Соус меньер масляный", "en": "Meuniere Brown Butter Sauce", "category": "sauces", "unit": "g", "calories": 717, "protein": 0.9, "fat": 81.0, "carbs": 0.4},
    {"name": "Соус борнез", "en": "Bearnaise French Butter Sauce", "category": "sauces", "unit": "g", "calories": 391, "protein": 4.5, "fat": 40.0, "carbs": 2.5},
    {"name": "Соус шорон томатный борнез", "en": "Choron Tomato Bearnaise", "category": "sauces", "unit": "g", "calories": 350, "protein": 3.5, "fat": 35.0, "carbs": 5.0},
    {"name": "Соус малтез апельсиновый голандез", "en": "Maltaise Orange Hollandaise", "category": "sauces", "unit": "g", "calories": 420, "protein": 3.0, "fat": 44.0, "carbs": 4.0},
    {"name": "Заправка итальянская vinaigrette", "en": "Italian Herb Vinaigrette", "category": "sauces", "unit": "g", "calories": 380, "protein": 0.4, "fat": 41.0, "carbs": 5.0},
    {"name": "Заправка греческая", "en": "Greek Oregano Salad Dressing", "category": "sauces", "unit": "g", "calories": 320, "protein": 0.5, "fat": 33.5, "carbs": 5.5},
    {"name": "Заправка азиатская кунжутная", "en": "Asian Sesame Ginger Dressing", "category": "sauces", "unit": "g", "calories": 245, "protein": 2.0, "fat": 20.0, "carbs": 15.0},
    {"name": "Заправка тысяча островов", "en": "Thousand Island Dressing", "category": "sauces", "unit": "g", "calories": 282, "protein": 1.0, "fat": 27.5, "carbs": 10.0},

    # ─── Специи экзотические ─────────────────────────────────────────────────
    {"name": "Барбарис ягоды для плова", "en": "Barberry Zereshk Berries Dried", "category": "spices", "unit": "g", "calories": 65, "protein": 1.0, "fat": 1.5, "carbs": 15.0},
    {"name": "Гранатовые зёрна сушёные", "en": "Anardana Dried Pomegranate Seeds", "category": "spices", "unit": "g", "calories": 346, "protein": 2.7, "fat": 1.2, "carbs": 84.6},
    {"name": "Семена горчицы жёлтые", "en": "Yellow Mustard Seeds Whole", "category": "spices", "unit": "g", "calories": 508, "protein": 26.1, "fat": 36.2, "carbs": 28.1},
    {"name": "Семена горчицы чёрные", "en": "Black Brown Mustard Seeds", "category": "spices", "unit": "g", "calories": 469, "protein": 26.1, "fat": 28.8, "carbs": 28.1},
    {"name": "Семена нигеллы чернушка", "en": "Nigella Kalonji Black Seeds", "category": "spices", "unit": "g", "calories": 375, "protein": 17.8, "fat": 22.3, "carbs": 44.2},
    {"name": "Ажгон карамельная зира", "en": "Ajwain Carom Seeds Spice", "category": "spices", "unit": "g", "calories": 305, "protein": 15.9, "fat": 25.0, "carbs": 43.0},
    {"name": "Перец малагетта", "en": "Grains of Paradise Melegueta", "category": "spices", "unit": "g", "calories": 305, "protein": 12.0, "fat": 8.0, "carbs": 55.0},
    {"name": "Листья карри свежие", "en": "Fresh Curry Leaves Indian", "category": "spices", "unit": "g", "calories": 108, "protein": 6.1, "fat": 1.0, "carbs": 18.7},
    {"name": "Листья пандан свежие", "en": "Fresh Pandan Leaves Thai", "category": "spices", "unit": "g", "calories": 32, "protein": 2.0, "fat": 0.7, "carbs": 7.3},
    {"name": "Чернослив для тушения", "en": "Prune for Meat Braising", "category": "spices", "unit": "g", "calories": 240, "protein": 2.2, "fat": 0.4, "carbs": 63.9},
    {"name": "Барбарис иранский сушёный", "en": "Iranian Zereshk Sour Barberry", "category": "spices", "unit": "g", "calories": 65, "protein": 1.0, "fat": 1.5, "carbs": 15.0},
    {"name": "Сумак ягоды молотые", "en": "Ground Sumac Berry Powder", "category": "spices", "unit": "g", "calories": 279, "protein": 5.0, "fat": 5.0, "carbs": 59.0},
    {"name": "Лепестки розы сушёные", "en": "Dried Rose Petal Culinary", "category": "spices", "unit": "g", "calories": 35, "protein": 1.0, "fat": 0.2, "carbs": 10.0},
    {"name": "Цветки шафрана иранского", "en": "Iranian Premium Saffron", "category": "spices", "unit": "g", "calories": 310, "protein": 11.4, "fat": 5.9, "carbs": 65.4},

    # ─── Готовые смеси и заготовки ────────────────────────────────────────────
    {"name": "Смесь для панировки темпура", "en": "Tempura Frying Batter Mix", "category": "grains", "unit": "g", "calories": 332, "protein": 8.0, "fat": 0.8, "carbs": 73.0},
    {"name": "Мясо маринованное для шашлыка", "en": "Marinated Shashlik Meat", "category": "meat", "unit": "g", "calories": 195, "protein": 18.0, "fat": 12.5, "carbs": 2.5},
    {"name": "Курица маринованная гриль", "en": "Marinated Grill Chicken", "category": "poultry", "unit": "g", "calories": 185, "protein": 23.0, "fat": 9.0, "carbs": 3.0},
    {"name": "Овощи замороженные смесь", "en": "Frozen Mixed Vegetables", "category": "vegetables", "unit": "g", "calories": 65, "protein": 3.5, "fat": 0.4, "carbs": 13.0},
    {"name": "Томаты черри замороженные", "en": "Frozen Cherry Tomatoes", "category": "vegetables", "unit": "g", "calories": 18, "protein": 0.9, "fat": 0.2, "carbs": 3.9},
    {"name": "Горошек замороженный", "en": "Frozen Petit Pois Garden Peas", "category": "vegetables", "unit": "g", "calories": 77, "protein": 5.4, "fat": 0.4, "carbs": 13.5},
    {"name": "Кукуруза замороженная", "en": "Frozen Sweet Corn Kernels", "category": "vegetables", "unit": "g", "calories": 83, "protein": 3.2, "fat": 1.2, "carbs": 17.5},
    {"name": "Фасоль стручковая замороженная", "en": "Frozen Fine Green Beans", "category": "vegetables", "unit": "g", "calories": 31, "protein": 1.8, "fat": 0.1, "carbs": 7.0},
    {"name": "Брокколи замороженная", "en": "Frozen Broccoli Florets", "category": "vegetables", "unit": "g", "calories": 34, "protein": 2.8, "fat": 0.4, "carbs": 7.2},
    {"name": "Шпинат замороженный", "en": "Frozen Leaf Spinach", "category": "vegetables", "unit": "g", "calories": 23, "protein": 2.9, "fat": 0.4, "carbs": 3.6},
    {"name": "Грибы замороженные", "en": "Frozen Forest Mushrooms", "category": "vegetables", "unit": "g", "calories": 22, "protein": 3.1, "fat": 0.3, "carbs": 3.3},
    {"name": "Ягоды замороженные ассорти", "en": "Frozen Mixed Forest Berries", "category": "fruits", "unit": "g", "calories": 45, "protein": 0.7, "fat": 0.4, "carbs": 10.8},
    {"name": "Малина замороженная", "en": "Frozen Raspberry", "category": "fruits", "unit": "g", "calories": 52, "protein": 1.2, "fat": 0.7, "carbs": 11.9},
    {"name": "Черника замороженная", "en": "Frozen Wild Blueberry", "category": "fruits", "unit": "g", "calories": 44, "protein": 1.1, "fat": 0.5, "carbs": 9.6},
    {"name": "Вишня замороженная без косточки", "en": "Frozen Pitted Cherry", "category": "fruits", "unit": "g", "calories": 50, "protein": 1.0, "fat": 0.3, "carbs": 12.2},
    {"name": "Клубника замороженная", "en": "Frozen Sliced Strawberry", "category": "fruits", "unit": "g", "calories": 32, "protein": 0.7, "fat": 0.3, "carbs": 7.7},
]

def main():
    print(f"Всего продуктов четвёртой партии: {len(EXTRA4)}")
    with open("extra_products4.json", "w", encoding="utf-8") as f:
        json.dump(EXTRA4, f, ensure_ascii=False, indent=2)
    print("Сохранено в extra_products4.json")

if __name__ == "__main__":
    main()
