#!/usr/bin/env python3
"""
Генерирует extra_products.json — дополнительные продукты которых нет в world_products.json.
Охватывает специализированные кулинарные ингредиенты, региональные продукты,
полуфабрикаты, добавки и профессиональные ингредиенты для ресторанной кухни.
"""
import json

EXTRA_PRODUCTS = [
    # ─── Мясо расширенный ───────────────────────────────────────────────────
    {"name": "Говяжья лопатка", "en": "Beef Shoulder", "category": "meat", "unit": "g", "calories": 175, "protein": 22.0, "fat": 9.5, "carbs": 0.0},
    {"name": "Говяжья голяшка", "en": "Beef Shank", "category": "meat", "unit": "g", "calories": 148, "protein": 24.0, "fat": 4.8, "carbs": 0.0},
    {"name": "Говяжья пашина", "en": "Beef Flank", "category": "meat", "unit": "g", "calories": 192, "protein": 27.0, "fat": 9.0, "carbs": 0.0},
    {"name": "Говяжья лопаточная часть", "en": "Beef Blade", "category": "meat", "unit": "g", "calories": 180, "protein": 21.0, "fat": 10.0, "carbs": 0.0},
    {"name": "Говяжий стейк стриплоин", "en": "Beef Strip Loin", "category": "meat", "unit": "g", "calories": 207, "protein": 27.0, "fat": 11.0, "carbs": 0.0},
    {"name": "Говяжий стейк тибон", "en": "Beef T-Bone", "category": "meat", "unit": "g", "calories": 242, "protein": 26.0, "fat": 15.0, "carbs": 0.0},
    {"name": "Говяжий стейк денвер", "en": "Beef Denver Steak", "category": "meat", "unit": "g", "calories": 185, "protein": 25.0, "fat": 9.0, "carbs": 0.0},
    {"name": "Говяжий стейк флэт-айрон", "en": "Beef Flat Iron Steak", "category": "meat", "unit": "g", "calories": 190, "protein": 27.0, "fat": 9.5, "carbs": 0.0},
    {"name": "Говяжий стейк мачете", "en": "Beef Skirt Steak", "category": "meat", "unit": "g", "calories": 218, "protein": 27.0, "fat": 12.0, "carbs": 0.0},
    {"name": "Говяжий стейк хэнгер", "en": "Beef Hanger Steak", "category": "meat", "unit": "g", "calories": 204, "protein": 28.0, "fat": 10.0, "carbs": 0.0},
    {"name": "Говяжий стейк чак-ролл", "en": "Beef Chuck Roll", "category": "meat", "unit": "g", "calories": 195, "protein": 24.0, "fat": 11.0, "carbs": 0.0},
    {"name": "Свиная рулька", "en": "Pork Knuckle", "category": "meat", "unit": "g", "calories": 280, "protein": 20.0, "fat": 22.0, "carbs": 0.0},
    {"name": "Свиная голова", "en": "Pork Head", "category": "meat", "unit": "g", "calories": 215, "protein": 19.0, "fat": 15.0, "carbs": 0.0},
    {"name": "Свиная уха", "en": "Pork Ear", "category": "meat", "unit": "g", "calories": 185, "protein": 21.0, "fat": 12.0, "carbs": 0.0},
    {"name": "Свиные ножки", "en": "Pork Trotters", "category": "meat", "unit": "g", "calories": 200, "protein": 16.0, "fat": 15.0, "carbs": 0.0},
    {"name": "Свиной хвост", "en": "Pork Tail", "category": "meat", "unit": "g", "calories": 310, "protein": 18.0, "fat": 27.0, "carbs": 0.0},
    {"name": "Свиная кровь", "en": "Pork Blood", "category": "meat", "unit": "g", "calories": 70, "protein": 17.0, "fat": 0.2, "carbs": 0.0},
    {"name": "Баранья грудинка", "en": "Lamb Breast", "category": "meat", "unit": "g", "calories": 295, "protein": 24.0, "fat": 22.0, "carbs": 0.0},
    {"name": "Баранья голяшка", "en": "Lamb Shank", "category": "meat", "unit": "g", "calories": 170, "protein": 23.0, "fat": 9.0, "carbs": 0.0},
    {"name": "Бараньи почки", "en": "Lamb Kidney", "category": "meat", "unit": "g", "calories": 97, "protein": 17.0, "fat": 3.0, "carbs": 0.8},
    {"name": "Телячья печень", "en": "Veal Liver", "category": "meat", "unit": "g", "calories": 140, "protein": 20.0, "fat": 5.0, "carbs": 4.0},
    {"name": "Телячья вилочковая железа", "en": "Veal Sweetbread", "category": "meat", "unit": "g", "calories": 110, "protein": 21.0, "fat": 2.5, "carbs": 0.0},
    {"name": "Телячьи мозги", "en": "Veal Brain", "category": "meat", "unit": "g", "calories": 143, "protein": 11.0, "fat": 11.0, "carbs": 0.8},
    {"name": "Говяжья щека", "en": "Beef Cheek", "category": "meat", "unit": "g", "calories": 165, "protein": 23.0, "fat": 8.0, "carbs": 0.0},
    {"name": "Говяжья диафрагма", "en": "Beef Diaphragm", "category": "meat", "unit": "g", "calories": 198, "protein": 27.0, "fat": 10.0, "carbs": 0.0},

    # ─── Птица расширенная ──────────────────────────────────────────────────
    {"name": "Куриная спинка", "en": "Chicken Back", "category": "poultry", "unit": "g", "calories": 170, "protein": 19.0, "fat": 11.0, "carbs": 0.0},
    {"name": "Куриная шея", "en": "Chicken Neck", "category": "poultry", "unit": "g", "calories": 185, "protein": 18.0, "fat": 12.0, "carbs": 0.0},
    {"name": "Куриные сердца", "en": "Chicken Hearts", "category": "poultry", "unit": "g", "calories": 159, "protein": 26.0, "fat": 5.0, "carbs": 0.6},
    {"name": "Куриные желудки", "en": "Chicken Gizzards", "category": "poultry", "unit": "g", "calories": 94, "protein": 18.0, "fat": 2.0, "carbs": 0.0},
    {"name": "Куриный фарш", "en": "Ground Chicken", "category": "poultry", "unit": "g", "calories": 143, "protein": 17.0, "fat": 8.0, "carbs": 0.0},
    {"name": "Утиные ножки", "en": "Duck Legs", "category": "poultry", "unit": "g", "calories": 217, "protein": 26.0, "fat": 13.0, "carbs": 0.0},
    {"name": "Утиная печень", "en": "Duck Liver", "category": "poultry", "unit": "g", "calories": 136, "protein": 19.0, "fat": 4.6, "carbs": 4.4},
    {"name": "Индюшиное бедро", "en": "Turkey Thigh Meat", "category": "poultry", "unit": "g", "calories": 170, "protein": 22.0, "fat": 9.0, "carbs": 0.0},
    {"name": "Индюшиные крылья", "en": "Turkey Wings", "category": "poultry", "unit": "g", "calories": 220, "protein": 24.0, "fat": 13.0, "carbs": 0.0},
    {"name": "Гусиные ножки", "en": "Goose Legs", "category": "poultry", "unit": "g", "calories": 274, "protein": 25.0, "fat": 19.0, "carbs": 0.0},
    {"name": "Перепелиные ножки", "en": "Quail Legs", "category": "poultry", "unit": "g", "calories": 192, "protein": 22.0, "fat": 11.0, "carbs": 0.0},

    # ─── Рыба расширенная ───────────────────────────────────────────────────
    {"name": "Сёмга", "en": "Sockey Salmon Whole", "category": "fish", "unit": "g", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0.0},
    {"name": "Рыба-меч", "en": "Swordfish Steak", "category": "fish", "unit": "g", "calories": 121, "protein": 20.0, "fat": 4.0, "carbs": 0.0},
    {"name": "Дорадо", "en": "Sea Bream", "category": "fish", "unit": "g", "calories": 96, "protein": 18.0, "fat": 2.9, "carbs": 0.0},
    {"name": "Сибас", "en": "European Sea Bass", "category": "fish", "unit": "g", "calories": 97, "protein": 19.0, "fat": 2.0, "carbs": 0.0},
    {"name": "Дальневосточная камбала", "en": "Far East Flounder", "category": "fish", "unit": "g", "calories": 83, "protein": 16.0, "fat": 1.8, "carbs": 0.0},
    {"name": "Судак", "en": "Zander Fish", "category": "fish", "unit": "g", "calories": 83, "protein": 18.0, "fat": 0.8, "carbs": 0.0},
    {"name": "Пикша", "en": "Haddock Fillet", "category": "fish", "unit": "g", "calories": 74, "protein": 17.0, "fat": 0.5, "carbs": 0.0},
    {"name": "Путассу", "en": "Blue Whiting", "category": "fish", "unit": "g", "calories": 72, "protein": 17.0, "fat": 0.9, "carbs": 0.0},
    {"name": "Сайра", "en": "Pacific Saury", "category": "fish", "unit": "g", "calories": 262, "protein": 18.0, "fat": 21.0, "carbs": 0.0},
    {"name": "Волжская сельдь", "en": "Volga Herring", "category": "fish", "unit": "g", "calories": 145, "protein": 19.0, "fat": 8.0, "carbs": 0.0},
    {"name": "Белый амур", "en": "Grass Carp", "category": "fish", "unit": "g", "calories": 135, "protein": 18.0, "fat": 5.9, "carbs": 0.0},
    {"name": "Карась", "en": "Crucian Carp", "category": "fish", "unit": "g", "calories": 87, "protein": 18.0, "fat": 1.8, "carbs": 0.0},
    {"name": "Угорь речной", "en": "River Eel", "category": "fish", "unit": "g", "calories": 261, "protein": 18.0, "fat": 20.0, "carbs": 0.0},
    {"name": "Налим", "en": "Burbot Fish", "category": "fish", "unit": "g", "calories": 82, "protein": 18.0, "fat": 0.8, "carbs": 0.0},
    {"name": "Хек", "en": "European Hake", "category": "fish", "unit": "g", "calories": 86, "protein": 17.0, "fat": 2.2, "carbs": 0.0},
    {"name": "Рыба-тилапия нильская", "en": "Nile Tilapia", "category": "fish", "unit": "g", "calories": 96, "protein": 20.0, "fat": 2.0, "carbs": 0.0},
    {"name": "Пангасиус", "en": "Pangasius", "category": "fish", "unit": "g", "calories": 89, "protein": 13.0, "fat": 3.5, "carbs": 0.0},
    {"name": "Телапия красная", "en": "Red Tilapia", "category": "fish", "unit": "g", "calories": 96, "protein": 20.0, "fat": 1.9, "carbs": 0.0},
    {"name": "Рыба-меч стейк", "en": "Swordfish Fillet", "category": "fish", "unit": "g", "calories": 144, "protein": 23.0, "fat": 5.0, "carbs": 0.0},
    {"name": "Ставрида", "en": "Horse Mackerel", "category": "fish", "unit": "g", "calories": 114, "protein": 18.0, "fat": 4.5, "carbs": 0.0},

    # ─── Морепродукты ───────────────────────────────────────────────────────
    {"name": "Гребешок морской", "en": "Bay Scallop", "category": "seafood", "unit": "g", "calories": 69, "protein": 13.0, "fat": 0.5, "carbs": 2.4},
    {"name": "Морской гребешок сушёный", "en": "Dried Scallop", "category": "seafood", "unit": "g", "calories": 330, "protein": 63.0, "fat": 1.8, "carbs": 12.0},
    {"name": "Трепанг", "en": "Sea Trepang", "category": "seafood", "unit": "g", "calories": 35, "protein": 7.3, "fat": 0.6, "carbs": 0.0},
    {"name": "Голотурия сушёная", "en": "Dried Sea Cucumber", "category": "seafood", "unit": "g", "calories": 295, "protein": 55.0, "fat": 4.0, "carbs": 5.0},
    {"name": "Мидии варёно-мороженые", "en": "Cooked Frozen Mussels", "category": "seafood", "unit": "g", "calories": 86, "protein": 12.0, "fat": 2.7, "carbs": 3.7},
    {"name": "Устрицы свежие", "en": "Fresh Oysters", "category": "seafood", "unit": "g", "calories": 68, "protein": 7.0, "fat": 2.5, "carbs": 3.9},
    {"name": "Фарш из кальмара", "en": "Squid Mince", "category": "seafood", "unit": "g", "calories": 92, "protein": 18.0, "fat": 1.4, "carbs": 2.0},
    {"name": "Осьминог варёный", "en": "Cooked Octopus", "category": "seafood", "unit": "g", "calories": 164, "protein": 30.0, "fat": 2.1, "carbs": 4.4},
    {"name": "Краб варёный", "en": "Cooked Crab Meat", "category": "seafood", "unit": "g", "calories": 97, "protein": 19.0, "fat": 1.5, "carbs": 0.0},
    {"name": "Лангусты", "en": "Spiny Lobster Tails", "category": "seafood", "unit": "g", "calories": 112, "protein": 24.0, "fat": 1.2, "carbs": 0.0},
    {"name": "Раки речные", "en": "River Crayfish", "category": "seafood", "unit": "g", "calories": 76, "protein": 16.0, "fat": 0.9, "carbs": 0.0},
    {"name": "Морской ёж икра", "en": "Sea Urchin Roe", "category": "seafood", "unit": "g", "calories": 172, "protein": 16.0, "fat": 9.0, "carbs": 5.0},
    {"name": "Сурими", "en": "Surimi", "category": "seafood", "unit": "g", "calories": 99, "protein": 15.0, "fat": 0.9, "carbs": 6.8},
    {"name": "Крабовые палочки", "en": "Crab Sticks", "category": "seafood", "unit": "g", "calories": 95, "protein": 8.0, "fat": 0.4, "carbs": 14.0},
    {"name": "Лосось горбуша", "en": "Pink Salmon Fillet", "category": "seafood", "unit": "g", "calories": 142, "protein": 21.0, "fat": 6.5, "carbs": 0.0},
    {"name": "Паста из морепродуктов", "en": "Seafood Paste", "category": "seafood", "unit": "g", "calories": 95, "protein": 18.0, "fat": 1.5, "carbs": 2.5},

    # ─── Грибы ──────────────────────────────────────────────────────────────
    {"name": "Шампиньоны", "en": "Button Mushroom", "category": "vegetables", "unit": "g", "calories": 22, "protein": 3.1, "fat": 0.3, "carbs": 3.3},
    {"name": "Портобелло", "en": "Portobello Mushroom", "category": "vegetables", "unit": "g", "calories": 22, "protein": 2.1, "fat": 0.4, "carbs": 3.9},
    {"name": "Белые грибы", "en": "Porcini Mushroom", "category": "vegetables", "unit": "g", "calories": 34, "protein": 3.7, "fat": 0.7, "carbs": 3.7},
    {"name": "Лисички", "en": "Chanterelle Mushroom", "category": "vegetables", "unit": "g", "calories": 38, "protein": 1.5, "fat": 0.5, "carbs": 6.9},
    {"name": "Грибы шиитаке", "en": "Shiitake Mushroom", "category": "vegetables", "unit": "g", "calories": 34, "protein": 2.2, "fat": 0.5, "carbs": 6.8},
    {"name": "Грибы эноки", "en": "Enoki Mushroom", "category": "vegetables", "unit": "g", "calories": 37, "protein": 2.7, "fat": 0.3, "carbs": 7.8},
    {"name": "Грибы оистер", "en": "Oyster Mushroom", "category": "vegetables", "unit": "g", "calories": 33, "protein": 3.3, "fat": 0.4, "carbs": 6.1},
    {"name": "Трюфель чёрный", "en": "Black Truffle", "category": "vegetables", "unit": "g", "calories": 92, "protein": 9.5, "fat": 0.5, "carbs": 17.3},
    {"name": "Трюфель белый", "en": "White Truffle", "category": "vegetables", "unit": "g", "calories": 98, "protein": 9.5, "fat": 0.5, "carbs": 17.4},
    {"name": "Сморчки", "en": "Morel Mushroom", "category": "vegetables", "unit": "g", "calories": 31, "protein": 3.1, "fat": 0.6, "carbs": 5.1},
    {"name": "Подберёзовики", "en": "Birch Bolete Mushroom", "category": "vegetables", "unit": "g", "calories": 20, "protein": 2.3, "fat": 0.4, "carbs": 3.7},
    {"name": "Подосиновики", "en": "Orange Cap Boletus", "category": "vegetables", "unit": "g", "calories": 22, "protein": 2.2, "fat": 0.3, "carbs": 3.7},
    {"name": "Маслята", "en": "Butter Mushroom", "category": "vegetables", "unit": "g", "calories": 19, "protein": 2.4, "fat": 0.4, "carbs": 3.2},
    {"name": "Опята", "en": "Honey Mushroom", "category": "vegetables", "unit": "g", "calories": 22, "protein": 2.2, "fat": 1.2, "carbs": 0.5},
    {"name": "Грибы матсутаке", "en": "Matsutake Mushroom", "category": "vegetables", "unit": "g", "calories": 28, "protein": 2.0, "fat": 0.3, "carbs": 5.0},
    {"name": "Грибы мун", "en": "Wood Ear Mushroom", "category": "vegetables", "unit": "g", "calories": 25, "protein": 0.5, "fat": 0.1, "carbs": 7.3},
    {"name": "Сушёные белые грибы", "en": "Dried Porcini", "category": "vegetables", "unit": "g", "calories": 286, "protein": 30.0, "fat": 5.3, "carbs": 31.0},
    {"name": "Трюфельная паста", "en": "Truffle Paste", "category": "sauces", "unit": "g", "calories": 116, "protein": 2.5, "fat": 10.5, "carbs": 4.0},

    # ─── Зерновые и мука расширенная ────────────────────────────────────────
    {"name": "Рис для суши", "en": "Sushi Rice Short Grain", "category": "grains", "unit": "g", "calories": 344, "protein": 7.0, "fat": 0.5, "carbs": 76.0},
    {"name": "Рис жасминовый", "en": "Thai Jasmine Rice", "category": "grains", "unit": "g", "calories": 348, "protein": 7.5, "fat": 0.5, "carbs": 77.0},
    {"name": "Рис чёрный", "en": "Black Rice", "category": "grains", "unit": "g", "calories": 356, "protein": 9.0, "fat": 3.5, "carbs": 71.0},
    {"name": "Рис красный", "en": "Red Rice", "category": "grains", "unit": "g", "calories": 351, "protein": 8.0, "fat": 2.5, "carbs": 72.0},
    {"name": "Паэлья рис", "en": "Paella Rice", "category": "grains", "unit": "g", "calories": 348, "protein": 7.2, "fat": 0.6, "carbs": 76.0},
    {"name": "Ризотто рис арборио", "en": "Arborio Risotto Rice", "category": "grains", "unit": "g", "calories": 351, "protein": 6.0, "fat": 0.5, "carbs": 78.0},
    {"name": "Маш зерновой", "en": "Mung Bean Grain", "category": "grains", "unit": "g", "calories": 347, "protein": 23.9, "fat": 1.2, "carbs": 62.6},
    {"name": "Чечевица зелёная варёная", "en": "Cooked Green Lentils", "category": "legumes", "unit": "g", "calories": 116, "protein": 9.0, "fat": 0.4, "carbs": 20.0},
    {"name": "Нут варёный", "en": "Cooked Chickpeas", "category": "legumes", "unit": "g", "calories": 164, "protein": 8.9, "fat": 2.6, "carbs": 27.0},
    {"name": "Чёрная фасоль варёная", "en": "Cooked Black Beans", "category": "legumes", "unit": "g", "calories": 132, "protein": 8.9, "fat": 0.5, "carbs": 23.7},
    {"name": "Красная фасоль варёная", "en": "Cooked Red Kidney Beans", "category": "legumes", "unit": "g", "calories": 127, "protein": 8.7, "fat": 0.5, "carbs": 22.8},
    {"name": "Соя варёная", "en": "Cooked Soybeans", "category": "legumes", "unit": "g", "calories": 173, "protein": 16.6, "fat": 9.0, "carbs": 9.9},
    {"name": "Паста мисо белая", "en": "White Miso Paste", "category": "sauces", "unit": "g", "calories": 199, "protein": 11.7, "fat": 6.0, "carbs": 25.7},
    {"name": "Паста мисо тёмная", "en": "Dark Miso Paste", "category": "sauces", "unit": "g", "calories": 198, "protein": 12.1, "fat": 6.0, "carbs": 25.4},
    {"name": "Мука тапиоковая", "en": "Cassava Tapioca Flour", "category": "grains", "unit": "g", "calories": 358, "protein": 0.2, "fat": 0.1, "carbs": 88.7},
    {"name": "Мука амарантовая", "en": "Amaranth Flour", "category": "grains", "unit": "g", "calories": 375, "protein": 14.8, "fat": 6.5, "carbs": 65.2},
    {"name": "Мука из нута", "en": "Besan Chickpea Flour", "category": "grains", "unit": "g", "calories": 387, "protein": 22.4, "fat": 6.7, "carbs": 57.8},
    {"name": "Мука из киноа", "en": "Quinoa Flour", "category": "grains", "unit": "g", "calories": 367, "protein": 14.2, "fat": 5.9, "carbs": 64.2},
    {"name": "Мука льняная", "en": "Flaxseed Flour", "category": "grains", "unit": "g", "calories": 392, "protein": 23.1, "fat": 30.2, "carbs": 28.9},
    {"name": "Мука сорго", "en": "Sorghum Flour", "category": "grains", "unit": "g", "calories": 357, "protein": 10.6, "fat": 3.4, "carbs": 73.0},
    {"name": "Мука полбяная", "en": "Spelt Flour", "category": "grains", "unit": "g", "calories": 338, "protein": 14.5, "fat": 2.4, "carbs": 70.2},
    {"name": "Мука ржаная цельнозерновая", "en": "Whole Rye Flour", "category": "grains", "unit": "g", "calories": 335, "protein": 10.9, "fat": 1.7, "carbs": 72.8},
    {"name": "Крупа ячменная", "en": "Pearl Barley Groats", "category": "grains", "unit": "g", "calories": 352, "protein": 9.3, "fat": 1.1, "carbs": 73.7},
    {"name": "Крупа кукурузная", "en": "Corn Grits Dry", "category": "grains", "unit": "g", "calories": 361, "protein": 7.2, "fat": 1.5, "carbs": 75.0},
    {"name": "Хлопья кукурузные", "en": "Cornflakes", "category": "grains", "unit": "g", "calories": 362, "protein": 7.5, "fat": 0.8, "carbs": 83.6},
    {"name": "Хлопья овсяные нежные", "en": "Rolled Oats Fine", "category": "grains", "unit": "g", "calories": 366, "protein": 10.9, "fat": 6.2, "carbs": 63.9},
    {"name": "Хлопья ржаные", "en": "Rye Flakes", "category": "grains", "unit": "g", "calories": 340, "protein": 10.0, "fat": 2.2, "carbs": 70.0},
    {"name": "Мюсли", "en": "Muesli Mix", "category": "grains", "unit": "g", "calories": 363, "protein": 9.6, "fat": 5.5, "carbs": 73.7},
    {"name": "Хлеб для тостов", "en": "Toast Bread", "category": "bakery", "unit": "g", "calories": 263, "protein": 8.3, "fat": 3.2, "carbs": 50.2},
    {"name": "Хлеб бородинский", "en": "Borodino Bread", "category": "bakery", "unit": "g", "calories": 207, "protein": 6.8, "fat": 1.3, "carbs": 40.7},
    {"name": "Хлебцы рисовые", "en": "Rice Cakes", "category": "bakery", "unit": "g", "calories": 382, "protein": 7.9, "fat": 2.4, "carbs": 82.4},
    {"name": "Хлебцы ржаные", "en": "Rye Crispbread", "category": "bakery", "unit": "g", "calories": 336, "protein": 12.4, "fat": 2.1, "carbs": 69.0},
    {"name": "Тортилья кукурузная", "en": "Corn Tortilla Wrap", "category": "bakery", "unit": "g", "calories": 218, "protein": 5.7, "fat": 3.0, "carbs": 44.6},
    {"name": "Тортилья пшеничная", "en": "Wheat Flour Tortilla", "category": "bakery", "unit": "g", "calories": 303, "protein": 8.5, "fat": 6.0, "carbs": 52.3},
    {"name": "Вафли несладкие", "en": "Savory Waffles", "category": "bakery", "unit": "g", "calories": 380, "protein": 9.0, "fat": 13.0, "carbs": 57.0},
    {"name": "Блинная мука", "en": "Pancake Mix Flour", "category": "grains", "unit": "g", "calories": 350, "protein": 8.0, "fat": 2.5, "carbs": 74.0},

    # ─── Молочные расширенные ───────────────────────────────────────────────
    {"name": "Молоко 3.5%", "en": "Full Fat Milk 3.5%", "category": "dairy", "unit": "g", "calories": 64, "protein": 3.2, "fat": 3.5, "carbs": 4.7},
    {"name": "Молоко 1%", "en": "Low Fat Milk 1%", "category": "dairy", "unit": "g", "calories": 42, "protein": 3.4, "fat": 1.0, "carbs": 5.0},
    {"name": "Сливки 10%", "en": "Light Cream 10%", "category": "dairy", "unit": "g", "calories": 119, "protein": 2.8, "fat": 10.0, "carbs": 4.0},
    {"name": "Сливки 20%", "en": "Sour Cream 20%", "category": "dairy", "unit": "g", "calories": 205, "protein": 2.5, "fat": 20.0, "carbs": 3.7},
    {"name": "Сливки 33%", "en": "Heavy Whipping Cream 33%", "category": "dairy", "unit": "g", "calories": 320, "protein": 2.2, "fat": 33.0, "carbs": 3.4},
    {"name": "Сметана 15%", "en": "Sour Cream 15%", "category": "dairy", "unit": "g", "calories": 158, "protein": 2.9, "fat": 15.0, "carbs": 3.6},
    {"name": "Сметана 25%", "en": "Sour Cream 25%", "category": "dairy", "unit": "g", "calories": 248, "protein": 2.6, "fat": 25.0, "carbs": 3.5},
    {"name": "Творог 0%", "en": "Cottage Cheese 0% Fat", "category": "dairy", "unit": "g", "calories": 71, "protein": 16.5, "fat": 0.0, "carbs": 1.3},
    {"name": "Творог 5%", "en": "Cottage Cheese 5%", "category": "dairy", "unit": "g", "calories": 121, "protein": 16.0, "fat": 5.0, "carbs": 1.8},
    {"name": "Творог 9%", "en": "Cottage Cheese 9%", "category": "dairy", "unit": "g", "calories": 159, "protein": 16.7, "fat": 9.0, "carbs": 2.0},
    {"name": "Сыр твёрдый российский", "en": "Russian Hard Cheese", "category": "dairy", "unit": "g", "calories": 360, "protein": 24.0, "fat": 28.0, "carbs": 0.3},
    {"name": "Сыр полутвёрдый голландский", "en": "Dutch Semi-Hard Cheese", "category": "dairy", "unit": "g", "calories": 352, "protein": 26.0, "fat": 27.0, "carbs": 0.0},
    {"name": "Сыр плавленый", "en": "Processed Cheese Spread", "category": "dairy", "unit": "g", "calories": 270, "protein": 14.0, "fat": 23.0, "carbs": 3.0},
    {"name": "Сыр пармезан тёртый", "en": "Grated Parmesan Cheese", "category": "dairy", "unit": "g", "calories": 431, "protein": 38.5, "fat": 29.0, "carbs": 4.1},
    {"name": "Сыр маасдам", "en": "Maasdam Cheese", "category": "dairy", "unit": "g", "calories": 350, "protein": 25.0, "fat": 26.0, "carbs": 0.0},
    {"name": "Сыр тильзитер", "en": "Tilsiter Cheese", "category": "dairy", "unit": "g", "calories": 340, "protein": 28.0, "fat": 26.0, "carbs": 0.0},
    {"name": "Сыр рикотта солёная", "en": "Salted Ricotta Cheese", "category": "dairy", "unit": "g", "calories": 140, "protein": 11.2, "fat": 9.5, "carbs": 3.0},
    {"name": "Мороженое пломбир", "en": "Plombir Ice Cream", "category": "dairy", "unit": "g", "calories": 228, "protein": 3.7, "fat": 12.0, "carbs": 27.5},
    {"name": "Мороженое ванильное", "en": "Vanilla Ice Cream", "category": "dairy", "unit": "g", "calories": 207, "protein": 3.5, "fat": 11.0, "carbs": 23.6},
    {"name": "Сорбет", "en": "Fruit Sorbet", "category": "dairy", "unit": "g", "calories": 97, "protein": 0.3, "fat": 0.1, "carbs": 25.0},
    {"name": "Молоко кокосовое консервированное", "en": "Canned Coconut Milk", "category": "dairy", "unit": "g", "calories": 197, "protein": 2.0, "fat": 21.3, "carbs": 2.8},
    {"name": "Йогурт греческий", "en": "Greek Style Yogurt", "category": "dairy", "unit": "g", "calories": 97, "protein": 9.0, "fat": 5.0, "carbs": 3.6},
    {"name": "Йогурт 3.5%", "en": "Natural Yogurt 3.5%", "category": "dairy", "unit": "g", "calories": 68, "protein": 5.0, "fat": 3.5, "carbs": 3.5},
    {"name": "Пахта", "en": "Cultured Buttermilk", "category": "dairy", "unit": "g", "calories": 40, "protein": 3.3, "fat": 0.9, "carbs": 4.8},
    {"name": "Варёное сгущённое молоко", "en": "Boiled Condensed Milk", "category": "dairy", "unit": "g", "calories": 328, "protein": 7.2, "fat": 8.5, "carbs": 56.0},
    {"name": "Топлёное молоко", "en": "Baked Milk", "category": "dairy", "unit": "g", "calories": 75, "protein": 3.0, "fat": 4.0, "carbs": 5.5},
    {"name": "Сыр камамбер", "en": "Camembert French Cheese", "category": "dairy", "unit": "g", "calories": 300, "protein": 20.0, "fat": 24.0, "carbs": 0.5},
    {"name": "Сыр бри французский", "en": "French Brie Cheese", "category": "dairy", "unit": "g", "calories": 334, "protein": 20.7, "fat": 27.7, "carbs": 0.5},

    # ─── Специи и травы расширенные ─────────────────────────────────────────
    {"name": "Перец чёрный молотый", "en": "Ground Black Pepper", "category": "spices", "unit": "g", "calories": 251, "protein": 10.4, "fat": 3.3, "carbs": 63.7},
    {"name": "Перец белый молотый", "en": "Ground White Pepper", "category": "spices", "unit": "g", "calories": 296, "protein": 10.4, "fat": 2.1, "carbs": 68.6},
    {"name": "Перец красный молотый", "en": "Ground Red Chili Pepper", "category": "spices", "unit": "g", "calories": 318, "protein": 12.0, "fat": 17.3, "carbs": 28.7},
    {"name": "Паприка копчёная", "en": "Sweet Smoked Paprika", "category": "spices", "unit": "g", "calories": 282, "protein": 14.1, "fat": 12.9, "carbs": 53.9},
    {"name": "Куркума молотая", "en": "Ground Turmeric", "category": "spices", "unit": "g", "calories": 354, "protein": 7.8, "fat": 9.9, "carbs": 64.9},
    {"name": "Корица молотая", "en": "Ground Cinnamon", "category": "spices", "unit": "g", "calories": 247, "protein": 3.9, "fat": 1.2, "carbs": 80.6},
    {"name": "Зира молотая", "en": "Ground Cumin", "category": "spices", "unit": "g", "calories": 375, "protein": 17.8, "fat": 22.3, "carbs": 44.2},
    {"name": "Кориандр молотый", "en": "Ground Coriander", "category": "spices", "unit": "g", "calories": 298, "protein": 12.4, "fat": 17.8, "carbs": 54.9},
    {"name": "Мускатный орех молотый", "en": "Ground Nutmeg", "category": "spices", "unit": "g", "calories": 525, "protein": 5.8, "fat": 36.3, "carbs": 49.3},
    {"name": "Гвоздика молотая", "en": "Ground Cloves", "category": "spices", "unit": "g", "calories": 274, "protein": 5.9, "fat": 13.0, "carbs": 65.5},
    {"name": "Кардамон молотый", "en": "Ground Cardamom", "category": "spices", "unit": "g", "calories": 311, "protein": 10.8, "fat": 6.7, "carbs": 68.5},
    {"name": "Смесь 5 специй", "en": "Chinese Five Spice Blend", "category": "spices", "unit": "g", "calories": 311, "protein": 7.0, "fat": 6.0, "carbs": 70.0},
    {"name": "Хмели-сунели", "en": "Khmeli Suneli Blend", "category": "spices", "unit": "g", "calories": 290, "protein": 9.0, "fat": 8.0, "carbs": 50.0},
    {"name": "Аджика сухая", "en": "Dry Adjika Blend", "category": "spices", "unit": "g", "calories": 270, "protein": 11.0, "fat": 10.0, "carbs": 45.0},
    {"name": "Чили молотый", "en": "Ground Chili Powder", "category": "spices", "unit": "g", "calories": 282, "protein": 13.5, "fat": 14.3, "carbs": 49.7},
    {"name": "Сумах молотый", "en": "Ground Sumac", "category": "spices", "unit": "g", "calories": 279, "protein": 5.0, "fat": 5.0, "carbs": 59.0},
    {"name": "Заатар смесь", "en": "Zaatar Herb Blend", "category": "spices", "unit": "g", "calories": 276, "protein": 8.5, "fat": 9.3, "carbs": 44.0},
    {"name": "Ваниль стручки", "en": "Vanilla Pods", "category": "spices", "unit": "g", "calories": 288, "protein": 0.1, "fat": 0.1, "carbs": 12.7},
    {"name": "Шафран нити", "en": "Saffron Threads", "category": "spices", "unit": "g", "calories": 310, "protein": 11.4, "fat": 5.9, "carbs": 65.4},
    {"name": "Анис звёздчатый целый", "en": "Whole Star Anise", "category": "spices", "unit": "g", "calories": 337, "protein": 17.6, "fat": 15.9, "carbs": 50.0},
    {"name": "Пажитник молотый", "en": "Ground Fenugreek", "category": "spices", "unit": "g", "calories": 323, "protein": 23.0, "fat": 6.4, "carbs": 58.4},
    {"name": "Бадьян", "en": "Badyan Star Anise", "category": "spices", "unit": "g", "calories": 337, "protein": 17.6, "fat": 15.9, "carbs": 50.0},
    {"name": "Майоран сушёный", "en": "Dried Marjoram Herb", "category": "spices", "unit": "g", "calories": 271, "protein": 12.7, "fat": 7.0, "carbs": 60.6},
    {"name": "Розмарин сушёный", "en": "Dried Rosemary Herb", "category": "spices", "unit": "g", "calories": 331, "protein": 4.9, "fat": 15.2, "carbs": 64.1},
    {"name": "Орегано сушёный", "en": "Dried Oregano Herb", "category": "spices", "unit": "g", "calories": 265, "protein": 9.0, "fat": 4.3, "carbs": 68.9},
    {"name": "Тимьян сушёный", "en": "Dried Thyme Herb", "category": "spices", "unit": "g", "calories": 276, "protein": 9.1, "fat": 7.4, "carbs": 63.9},
    {"name": "Эстрагон сушёный", "en": "Dried Tarragon Herb", "category": "spices", "unit": "g", "calories": 295, "protein": 22.8, "fat": 7.2, "carbs": 50.2},
    {"name": "Базилик сушёный", "en": "Dried Basil Herb", "category": "spices", "unit": "g", "calories": 233, "protein": 22.9, "fat": 4.0, "carbs": 47.8},
    {"name": "Петрушка сушёная", "en": "Dried Parsley Herb", "category": "spices", "unit": "g", "calories": 292, "protein": 26.7, "fat": 5.5, "carbs": 50.6},
    {"name": "Укроп сушёный", "en": "Dried Dill Herb", "category": "spices", "unit": "g", "calories": 253, "protein": 19.9, "fat": 4.4, "carbs": 55.8},
    {"name": "Кинза сушёная", "en": "Dried Cilantro Herb", "category": "spices", "unit": "g", "calories": 279, "protein": 21.9, "fat": 4.8, "carbs": 52.1},
    {"name": "Мята перечная сушёная", "en": "Dried Peppermint", "category": "spices", "unit": "g", "calories": 285, "protein": 19.9, "fat": 6.0, "carbs": 52.9},
    {"name": "Шалфей сушёный", "en": "Dried Sage Herb", "category": "spices", "unit": "g", "calories": 315, "protein": 10.6, "fat": 12.8, "carbs": 60.7},
    {"name": "Лавровый лист молотый", "en": "Ground Bay Leaf", "category": "spices", "unit": "g", "calories": 313, "protein": 7.6, "fat": 8.4, "carbs": 74.9},

    # ─── Соусы расширенные ──────────────────────────────────────────────────
    {"name": "Соус хойсин", "en": "Chinese Hoisin Sauce", "category": "sauces", "unit": "g", "calories": 220, "protein": 4.0, "fat": 1.0, "carbs": 50.0},
    {"name": "Соус терияки", "en": "Japanese Teriyaki Sauce", "category": "sauces", "unit": "g", "calories": 89, "protein": 5.5, "fat": 0.0, "carbs": 17.3},
    {"name": "Соус понзу", "en": "Japanese Ponzu Sauce", "category": "sauces", "unit": "g", "calories": 52, "protein": 3.6, "fat": 0.1, "carbs": 8.5},
    {"name": "Соус устричный", "en": "Chinese Oyster Sauce", "category": "sauces", "unit": "g", "calories": 89, "protein": 3.4, "fat": 0.3, "carbs": 18.8},
    {"name": "Соус рыбный вьетнамский", "en": "Vietnamese Fish Sauce", "category": "sauces", "unit": "g", "calories": 35, "protein": 5.1, "fat": 0.0, "carbs": 3.6},
    {"name": "Соус соевый тёмный", "en": "Dark Chinese Soy Sauce", "category": "sauces", "unit": "g", "calories": 65, "protein": 4.4, "fat": 0.0, "carbs": 10.0},
    {"name": "Соус соевый светлый", "en": "Light Soy Sauce", "category": "sauces", "unit": "g", "calories": 53, "protein": 8.1, "fat": 0.1, "carbs": 4.9},
    {"name": "Соус чили сладкий", "en": "Sweet Chili Sauce", "category": "sauces", "unit": "g", "calories": 125, "protein": 0.8, "fat": 0.2, "carbs": 30.8},
    {"name": "Соус чили острый", "en": "Hot Chili Sauce", "category": "sauces", "unit": "g", "calories": 55, "protein": 1.4, "fat": 0.6, "carbs": 11.9},
    {"name": "Паста чили", "en": "Chili Paste Sambal", "category": "sauces", "unit": "g", "calories": 90, "protein": 2.5, "fat": 3.0, "carbs": 14.0},
    {"name": "Соус шрирача", "en": "Sriracha Hot Sauce", "category": "sauces", "unit": "g", "calories": 93, "protein": 2.0, "fat": 0.5, "carbs": 20.0},
    {"name": "Соус пад тай", "en": "Pad Thai Sauce", "category": "sauces", "unit": "g", "calories": 135, "protein": 3.0, "fat": 0.5, "carbs": 31.0},
    {"name": "Соус карри зелёный", "en": "Green Curry Paste", "category": "sauces", "unit": "g", "calories": 137, "protein": 2.5, "fat": 8.0, "carbs": 14.0},
    {"name": "Соус карри красный", "en": "Red Curry Paste", "category": "sauces", "unit": "g", "calories": 150, "protein": 3.3, "fat": 10.0, "carbs": 14.5},
    {"name": "Мисо паста красная", "en": "Red Miso Paste", "category": "sauces", "unit": "g", "calories": 186, "protein": 11.8, "fat": 5.5, "carbs": 23.5},
    {"name": "Паста тахини кунжутная", "en": "Sesame Tahini Paste", "category": "sauces", "unit": "g", "calories": 595, "protein": 17.0, "fat": 53.8, "carbs": 21.2},
    {"name": "Уксус бальзамический тёмный", "en": "Dark Balsamic Vinegar", "category": "sauces", "unit": "g", "calories": 88, "protein": 0.5, "fat": 0.0, "carbs": 17.0},
    {"name": "Уксус яблочный 6%", "en": "Apple Cider Vinegar 6%", "category": "sauces", "unit": "g", "calories": 11, "protein": 0.0, "fat": 0.0, "carbs": 0.9},
    {"name": "Уксус винный белый", "en": "White Wine Vinegar Bottle", "category": "sauces", "unit": "g", "calories": 15, "protein": 0.0, "fat": 0.0, "carbs": 0.3},
    {"name": "Соус табаско красный", "en": "Red Tabasco Sauce", "category": "sauces", "unit": "g", "calories": 25, "protein": 0.7, "fat": 0.5, "carbs": 5.0},
    {"name": "Соус вустерский", "en": "Worcestershire Sauce Bottle", "category": "sauces", "unit": "g", "calories": 78, "protein": 1.4, "fat": 0.1, "carbs": 19.5},
    {"name": "Томатная паста 30%", "en": "Tomato Paste 30% Concentrate", "category": "sauces", "unit": "g", "calories": 82, "protein": 4.3, "fat": 0.4, "carbs": 16.8},
    {"name": "Томатный пюре", "en": "Tomato Puree Sauce", "category": "sauces", "unit": "g", "calories": 38, "protein": 1.5, "fat": 0.1, "carbs": 8.1},
    {"name": "Горчица французская зернистая", "en": "Grain French Mustard", "category": "sauces", "unit": "g", "calories": 77, "protein": 3.8, "fat": 4.0, "carbs": 7.0},
    {"name": "Горчица дижонская острая", "en": "Sharp Dijon Mustard Jar", "category": "sauces", "unit": "g", "calories": 66, "protein": 3.8, "fat": 3.6, "carbs": 5.3},
    {"name": "Майонез классический", "en": "Classic Mayonnaise", "category": "sauces", "unit": "g", "calories": 680, "protein": 1.3, "fat": 75.0, "carbs": 2.6},
    {"name": "Майонез оливковый", "en": "Olive Oil Mayonnaise", "category": "sauces", "unit": "g", "calories": 680, "protein": 1.2, "fat": 75.0, "carbs": 2.4},
    {"name": "Майонез лёгкий", "en": "Light Reduced Fat Mayonnaise", "category": "sauces", "unit": "g", "calories": 246, "protein": 1.4, "fat": 25.0, "carbs": 4.0},
    {"name": "Кетчуп томатный классический", "en": "Classic Tomato Ketchup", "category": "sauces", "unit": "g", "calories": 112, "protein": 1.9, "fat": 0.1, "carbs": 26.0},
    {"name": "Соус барбекю", "en": "American BBQ Sauce", "category": "sauces", "unit": "g", "calories": 170, "protein": 1.0, "fat": 0.0, "carbs": 40.0},
    {"name": "Соус айоли", "en": "Aioli Garlic Sauce", "category": "sauces", "unit": "g", "calories": 420, "protein": 1.5, "fat": 45.0, "carbs": 3.0},
    {"name": "Соус тзацики", "en": "Greek Tzatziki Sauce", "category": "sauces", "unit": "g", "calories": 55, "protein": 3.8, "fat": 3.0, "carbs": 3.5},
    {"name": "Соус цезарь", "en": "Caesar Salad Dressing", "category": "sauces", "unit": "g", "calories": 370, "protein": 2.5, "fat": 37.0, "carbs": 8.0},
    {"name": "Соус ранч", "en": "Ranch Dipping Sauce", "category": "sauces", "unit": "g", "calories": 332, "protein": 1.2, "fat": 34.7, "carbs": 4.3},
    {"name": "Дрессинг бальзамический", "en": "Balsamic Glaze Dressing", "category": "sauces", "unit": "g", "calories": 145, "protein": 0.7, "fat": 9.0, "carbs": 16.0},
    {"name": "Паста анчоус", "en": "Anchovy Paste Tube", "category": "sauces", "unit": "g", "calories": 210, "protein": 28.0, "fat": 11.0, "carbs": 0.3},
    {"name": "Томатный соус болоньезе", "en": "Bolognese Tomato Sauce", "category": "sauces", "unit": "g", "calories": 82, "protein": 6.5, "fat": 3.5, "carbs": 7.0},
    {"name": "Соус бешамель", "en": "Classic Bechamel Sauce", "category": "sauces", "unit": "g", "calories": 85, "protein": 3.4, "fat": 5.0, "carbs": 6.8},
    {"name": "Соус голландский", "en": "Hollandaise Butter Sauce", "category": "sauces", "unit": "g", "calories": 475, "protein": 2.0, "fat": 51.0, "carbs": 1.5},
    {"name": "Фермерская заправка", "en": "Farmhouse Herb Dressing", "category": "sauces", "unit": "g", "calories": 200, "protein": 1.0, "fat": 18.0, "carbs": 10.0},

    # ─── Масла расширенные ──────────────────────────────────────────────────
    {"name": "Масло оливковое Extra Virgin", "en": "Extra Virgin Olive Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло оливковое рафинированное", "en": "Refined Olive Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло подсолнечное рафинированное", "en": "Refined Sunflower Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло подсолнечное нерафинированное", "en": "Unrefined Sunflower Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло кукурузное", "en": "Corn Cooking Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло рапсовое", "en": "Rapeseed Canola Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло виноградное", "en": "Grapeseed Cooking Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло арахисовое", "en": "Peanut Cooking Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло кунжутное тёмное", "en": "Roasted Dark Sesame Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло кунжутное светлое", "en": "Light Sesame Oil Cold Pressed", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло льняное", "en": "Cold Pressed Flaxseed Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло кокосовое нерафинированное", "en": "Virgin Coconut Oil", "category": "oils", "unit": "g", "calories": 892, "protein": 0.0, "fat": 99.1, "carbs": 0.0},
    {"name": "Масло авокадо нерафинированное", "en": "Cold Pressed Avocado Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло тыквенных семян", "en": "Styrian Pumpkin Seed Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло ореха грецкого", "en": "Cold Pressed Walnut Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло фундука", "en": "Cold Pressed Hazelnut Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло трюфельное ароматное", "en": "Infused White Truffle Oil", "category": "oils", "unit": "g", "calories": 824, "protein": 0.0, "fat": 92.0, "carbs": 0.5},
    {"name": "Масло сливочное несолёное", "en": "Unsalted Butter Block", "category": "oils", "unit": "g", "calories": 717, "protein": 0.9, "fat": 81.1, "carbs": 0.1},
    {"name": "Масло сливочное солёное", "en": "Salted Butter Block", "category": "oils", "unit": "g", "calories": 717, "protein": 0.9, "fat": 81.1, "carbs": 0.1},
    {"name": "Масло гхи топлёное", "en": "Indian Ghee Clarified Butter", "category": "oils", "unit": "g", "calories": 900, "protein": 0.3, "fat": 99.5, "carbs": 0.0},
    {"name": "Масло конопляное", "en": "Cold Pressed Hemp Seed Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Масло рисовых отрубей", "en": "Rice Bran Cooking Oil", "category": "oils", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Жир говяжий", "en": "Rendered Beef Tallow", "category": "oils", "unit": "g", "calories": 902, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Жир свиной смалец", "en": "Rendered Pork Lard", "category": "oils", "unit": "g", "calories": 902, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Жир утиный", "en": "Rendered Duck Fat Jar", "category": "oils", "unit": "g", "calories": 882, "protein": 0.0, "fat": 99.8, "carbs": 0.0},

    # ─── Орехи расширенные ──────────────────────────────────────────────────
    {"name": "Миндаль бланшированный", "en": "Blanched Almond Nuts", "category": "nuts", "unit": "g", "calories": 579, "protein": 21.2, "fat": 49.9, "carbs": 21.6},
    {"name": "Миндаль молотый", "en": "Ground Almond Meal", "category": "nuts", "unit": "g", "calories": 580, "protein": 21.0, "fat": 50.0, "carbs": 20.4},
    {"name": "Кешью жареный", "en": "Roasted Cashew Nuts", "category": "nuts", "unit": "g", "calories": 553, "protein": 15.3, "fat": 43.9, "carbs": 32.7},
    {"name": "Фисташки очищенные", "en": "Shelled Pistachio Nuts", "category": "nuts", "unit": "g", "calories": 562, "protein": 20.2, "fat": 45.3, "carbs": 27.5},
    {"name": "Фундук жареный", "en": "Roasted Hazelnut Nuts", "category": "nuts", "unit": "g", "calories": 646, "protein": 14.1, "fat": 62.4, "carbs": 17.6},
    {"name": "Грецкие орехи половинки", "en": "Walnut Halves Shelled", "category": "nuts", "unit": "g", "calories": 654, "protein": 15.2, "fat": 65.2, "carbs": 13.7},
    {"name": "Пекан орех", "en": "Pecan Nut Halves", "category": "nuts", "unit": "g", "calories": 691, "protein": 9.2, "fat": 72.0, "carbs": 13.9},
    {"name": "Макадамия орех", "en": "Macadamia Nut Whole", "category": "nuts", "unit": "g", "calories": 718, "protein": 7.9, "fat": 75.8, "carbs": 13.8},
    {"name": "Бразильский орех", "en": "Brazil Nut Shelled", "category": "nuts", "unit": "g", "calories": 656, "protein": 14.3, "fat": 66.4, "carbs": 12.3},
    {"name": "Кедровый орех сибирский", "en": "Siberian Pine Nut", "category": "nuts", "unit": "g", "calories": 673, "protein": 13.7, "fat": 68.4, "carbs": 13.1},
    {"name": "Арахис жареный солёный", "en": "Roasted Salted Peanuts", "category": "nuts", "unit": "g", "calories": 585, "protein": 23.5, "fat": 49.2, "carbs": 21.5},
    {"name": "Арахисовая паста хрустящая", "en": "Crunchy Peanut Butter Jar", "category": "nuts", "unit": "g", "calories": 593, "protein": 22.5, "fat": 51.0, "carbs": 22.3},
    {"name": "Арахисовая паста гладкая", "en": "Smooth Peanut Butter Jar", "category": "nuts", "unit": "g", "calories": 588, "protein": 25.0, "fat": 50.4, "carbs": 20.0},
    {"name": "Миндальная паста", "en": "Almond Butter Smooth", "category": "nuts", "unit": "g", "calories": 614, "protein": 21.0, "fat": 55.0, "carbs": 18.8},
    {"name": "Кунжут чёрный", "en": "Black Sesame Seeds", "category": "nuts", "unit": "g", "calories": 565, "protein": 17.7, "fat": 48.7, "carbs": 23.5},
    {"name": "Кунжут белый", "en": "White Sesame Seeds", "category": "nuts", "unit": "g", "calories": 565, "protein": 17.0, "fat": 48.0, "carbs": 23.0},
    {"name": "Семена подсолнечника очищенные", "en": "Shelled Sunflower Seeds", "category": "nuts", "unit": "g", "calories": 584, "protein": 20.8, "fat": 51.5, "carbs": 20.0},
    {"name": "Семена тыквы очищенные", "en": "Shelled Pumpkin Seeds", "category": "nuts", "unit": "g", "calories": 559, "protein": 30.2, "fat": 49.1, "carbs": 10.7},
    {"name": "Семена льна золотые", "en": "Golden Flax Seeds", "category": "nuts", "unit": "g", "calories": 534, "protein": 18.3, "fat": 42.2, "carbs": 28.9},
    {"name": "Семена чиа чёрные", "en": "Black Chia Seeds", "category": "nuts", "unit": "g", "calories": 486, "protein": 16.5, "fat": 30.7, "carbs": 42.1},
    {"name": "Конопляное семя очищенное", "en": "Hulled Hemp Seeds", "category": "nuts", "unit": "g", "calories": 553, "protein": 31.6, "fat": 48.7, "carbs": 8.7},
    {"name": "Семена мака", "en": "Poppy Seeds Blue", "category": "nuts", "unit": "g", "calories": 525, "protein": 17.9, "fat": 41.6, "carbs": 28.1},
    {"name": "Кокосовая стружка", "en": "Desiccated Coconut Flakes", "category": "nuts", "unit": "g", "calories": 660, "protein": 6.9, "fat": 64.5, "carbs": 23.7},
    {"name": "Кокосовая мука", "en": "Coconut Flour Baking", "category": "nuts", "unit": "g", "calories": 354, "protein": 19.3, "fat": 14.8, "carbs": 57.8},
    {"name": "Кешью паста", "en": "Cashew Nut Butter", "category": "nuts", "unit": "g", "calories": 587, "protein": 15.0, "fat": 49.0, "carbs": 28.0},

    # ─── Сахар и сладкое расширенное ────────────────────────────────────────
    {"name": "Сахар тростниковый коричневый", "en": "Brown Cane Sugar", "category": "sweets", "unit": "g", "calories": 377, "protein": 0.0, "fat": 0.0, "carbs": 97.0},
    {"name": "Сахар белый рафинированный", "en": "White Refined Sugar", "category": "sweets", "unit": "g", "calories": 399, "protein": 0.0, "fat": 0.0, "carbs": 99.8},
    {"name": "Сахарная пудра", "en": "Powdered Confectioners Sugar", "category": "sweets", "unit": "g", "calories": 389, "protein": 0.0, "fat": 0.0, "carbs": 99.6},
    {"name": "Мёд акациевый", "en": "Acacia Honey", "category": "sweets", "unit": "g", "calories": 304, "protein": 0.3, "fat": 0.0, "carbs": 82.4},
    {"name": "Мёд гречишный", "en": "Buckwheat Dark Honey", "category": "sweets", "unit": "g", "calories": 304, "protein": 0.3, "fat": 0.0, "carbs": 82.4},
    {"name": "Мёд цветочный", "en": "Wildflower Honey", "category": "sweets", "unit": "g", "calories": 304, "protein": 0.3, "fat": 0.0, "carbs": 82.4},
    {"name": "Сироп кленовый", "en": "Pure Maple Syrup", "category": "sweets", "unit": "g", "calories": 260, "protein": 0.0, "fat": 0.1, "carbs": 67.0},
    {"name": "Сироп агавовый", "en": "Organic Agave Nectar", "category": "sweets", "unit": "g", "calories": 310, "protein": 0.1, "fat": 0.0, "carbs": 76.0},
    {"name": "Сироп глюкозный", "en": "Glucose Corn Syrup", "category": "sweets", "unit": "g", "calories": 316, "protein": 0.0, "fat": 0.0, "carbs": 79.0},
    {"name": "Патока тёмная", "en": "Blackstrap Molasses", "category": "sweets", "unit": "g", "calories": 290, "protein": 1.5, "fat": 0.1, "carbs": 74.7},
    {"name": "Шоколад горький 70%", "en": "Dark Chocolate 70% Cocoa", "category": "sweets", "unit": "g", "calories": 569, "protein": 6.8, "fat": 40.2, "carbs": 45.2},
    {"name": "Шоколад молочный", "en": "Milk Chocolate Bar", "category": "sweets", "unit": "g", "calories": 535, "protein": 7.7, "fat": 30.4, "carbs": 59.2},
    {"name": "Шоколад белый", "en": "White Chocolate Couverture", "category": "sweets", "unit": "g", "calories": 539, "protein": 5.9, "fat": 32.1, "carbs": 59.2},
    {"name": "Какао-порошок алкализованный", "en": "Alkalized Cocoa Powder", "category": "sweets", "unit": "g", "calories": 228, "protein": 20.0, "fat": 13.7, "carbs": 14.3},
    {"name": "Какао тёртое", "en": "Raw Cacao Paste", "category": "sweets", "unit": "g", "calories": 510, "protein": 13.2, "fat": 53.2, "carbs": 30.2},
    {"name": "Какао масло", "en": "Cocoa Butter Food Grade", "category": "sweets", "unit": "g", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0},
    {"name": "Карамель мягкая", "en": "Soft Caramel Candy", "category": "sweets", "unit": "g", "calories": 382, "protein": 3.2, "fat": 9.2, "carbs": 70.5},
    {"name": "Карамель жидкая", "en": "Liquid Caramel Sauce", "category": "sweets", "unit": "g", "calories": 328, "protein": 2.2, "fat": 8.5, "carbs": 59.0},
    {"name": "Крем карамельный", "en": "Caramel Cream Filling", "category": "sweets", "unit": "g", "calories": 290, "protein": 2.0, "fat": 12.0, "carbs": 43.0},
    {"name": "Желатин листовой", "en": "Sheet Gelatin Leaves", "category": "sweets", "unit": "g", "calories": 335, "protein": 84.4, "fat": 0.1, "carbs": 0.0},
    {"name": "Желатин порошковый", "en": "Powdered Gelatin", "category": "sweets", "unit": "g", "calories": 335, "protein": 84.4, "fat": 0.1, "carbs": 0.0},
    {"name": "Агар-агар порошок", "en": "Agar Agar Powder Vegan", "category": "sweets", "unit": "g", "calories": 26, "protein": 0.5, "fat": 0.0, "carbs": 7.7},
    {"name": "Пектин яблочный", "en": "Apple Pectin Powder", "category": "sweets", "unit": "g", "calories": 160, "protein": 0.0, "fat": 0.0, "carbs": 80.0},
    {"name": "Ксантановая камедь", "en": "Xanthan Gum Powder", "category": "sweets", "unit": "g", "calories": 333, "protein": 0.0, "fat": 0.0, "carbs": 83.3},
    {"name": "Глюкоза декстроза", "en": "Dextrose Glucose Powder", "category": "sweets", "unit": "g", "calories": 363, "protein": 0.0, "fat": 0.0, "carbs": 91.0},
    {"name": "Трегалоза", "en": "Trehalose Sugar", "category": "sweets", "unit": "g", "calories": 375, "protein": 0.0, "fat": 0.0, "carbs": 94.0},
    {"name": "Изомальт", "en": "Isomalt Sugar Substitute", "category": "sweets", "unit": "g", "calories": 200, "protein": 0.0, "fat": 0.0, "carbs": 50.0},
    {"name": "Нугатин", "en": "Nougatine Almond Brittle", "category": "sweets", "unit": "g", "calories": 492, "protein": 6.5, "fat": 27.0, "carbs": 57.0},
    {"name": "Пралине миндальное", "en": "Almond Praline Paste", "category": "sweets", "unit": "g", "calories": 581, "protein": 12.0, "fat": 47.0, "carbs": 32.0},

    # ─── Напитки расширенные ────────────────────────────────────────────────
    {"name": "Кофе в зёрнах арабика", "en": "Arabica Coffee Beans", "category": "beverages", "unit": "g", "calories": 2, "protein": 0.3, "fat": 0.0, "carbs": 0.3},
    {"name": "Кофе в зёрнах робуста", "en": "Robusta Coffee Beans", "category": "beverages", "unit": "g", "calories": 2, "protein": 0.3, "fat": 0.0, "carbs": 0.3},
    {"name": "Кофе молотый", "en": "Ground Coffee Fine", "category": "beverages", "unit": "g", "calories": 2, "protein": 0.3, "fat": 0.0, "carbs": 0.3},
    {"name": "Кофе растворимый", "en": "Instant Soluble Coffee", "category": "beverages", "unit": "g", "calories": 353, "protein": 14.6, "fat": 0.3, "carbs": 76.0},
    {"name": "Чай зелёный листовой", "en": "Loose Leaf Green Tea", "category": "beverages", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Чай чёрный листовой", "en": "Loose Leaf Black Tea", "category": "beverages", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Чай белый листовой", "en": "Loose Leaf White Tea", "category": "beverages", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Чай пуэр", "en": "Aged Pu-erh Tea", "category": "beverages", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Чай матча молотый", "en": "Matcha Green Tea Powder", "category": "beverages", "unit": "g", "calories": 324, "protein": 30.0, "fat": 5.3, "carbs": 37.9},
    {"name": "Куркума латте смесь", "en": "Turmeric Latte Golden Milk Mix", "category": "beverages", "unit": "g", "calories": 360, "protein": 9.0, "fat": 8.0, "carbs": 64.0},
    {"name": "Ромашковый чай сухой", "en": "Chamomile Herbal Tea Dry", "category": "beverages", "unit": "g", "calories": 1, "protein": 0.1, "fat": 0.1, "carbs": 0.3},
    {"name": "Сок лимона свежевыжатый", "en": "Fresh Squeezed Lemon Juice", "category": "beverages", "unit": "g", "calories": 29, "protein": 0.5, "fat": 0.1, "carbs": 9.3},
    {"name": "Сок лайма свежий", "en": "Fresh Squeezed Lime Juice", "category": "beverages", "unit": "g", "calories": 30, "protein": 0.7, "fat": 0.2, "carbs": 10.5},
    {"name": "Сок апельсиновый свежевыжатый", "en": "Fresh Squeezed Orange Juice", "category": "beverages", "unit": "g", "calories": 45, "protein": 0.7, "fat": 0.2, "carbs": 10.4},
    {"name": "Сок грейпфрутовый свежий", "en": "Fresh Grapefruit Juice", "category": "beverages", "unit": "g", "calories": 38, "protein": 0.5, "fat": 0.1, "carbs": 9.2},
    {"name": "Вино белое сухое (для готовки)", "en": "Dry White Wine Cooking", "category": "beverages", "unit": "g", "calories": 82, "protein": 0.1, "fat": 0.0, "carbs": 2.6},
    {"name": "Вино красное сухое (для готовки)", "en": "Dry Red Wine Cooking", "category": "beverages", "unit": "g", "calories": 85, "protein": 0.1, "fat": 0.0, "carbs": 2.6},
    {"name": "Коньяк (для фламбирования)", "en": "Brandy Cognac Cooking", "category": "beverages", "unit": "g", "calories": 237, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Бульон говяжий", "en": "Beef Stock Broth", "category": "beverages", "unit": "g", "calories": 15, "protein": 2.5, "fat": 0.5, "carbs": 0.5},
    {"name": "Бульон куриный", "en": "Chicken Stock Broth", "category": "beverages", "unit": "g", "calories": 15, "protein": 1.5, "fat": 0.5, "carbs": 1.0},
    {"name": "Бульон рыбный", "en": "Fish Stock Fumet", "category": "beverages", "unit": "g", "calories": 13, "protein": 2.0, "fat": 0.3, "carbs": 0.5},
    {"name": "Бульон овощной", "en": "Vegetable Stock Broth", "category": "beverages", "unit": "g", "calories": 7, "protein": 0.3, "fat": 0.0, "carbs": 1.4},

    # ─── Колбасные расширенные ──────────────────────────────────────────────
    {"name": "Ветчина варёная", "en": "Cooked Ham Sliced", "category": "processed_meat", "unit": "g", "calories": 145, "protein": 16.0, "fat": 8.0, "carbs": 1.3},
    {"name": "Ветчина сыровяленая", "en": "Dry Cured Ham Serrano", "category": "processed_meat", "unit": "g", "calories": 160, "protein": 24.5, "fat": 7.0, "carbs": 0.5},
    {"name": "Колбаса варёная докторская", "en": "Boiled Doctors Sausage", "category": "processed_meat", "unit": "g", "calories": 257, "protein": 12.8, "fat": 22.8, "carbs": 1.5},
    {"name": "Колбаса краковская", "en": "Krakow Smoked Sausage", "category": "processed_meat", "unit": "g", "calories": 348, "protein": 16.2, "fat": 30.8, "carbs": 1.4},
    {"name": "Колбаса охотничья", "en": "Hunters Smoked Sausage", "category": "processed_meat", "unit": "g", "calories": 364, "protein": 16.3, "fat": 32.4, "carbs": 0.7},
    {"name": "Колбаса сервелат", "en": "Cervelat Salami Sausage", "category": "processed_meat", "unit": "g", "calories": 461, "protein": 24.0, "fat": 40.5, "carbs": 0.3},
    {"name": "Сосиски молочные", "en": "Milk Frankfurter Sausage", "category": "processed_meat", "unit": "g", "calories": 266, "protein": 11.0, "fat": 23.9, "carbs": 1.6},
    {"name": "Сосиски венские", "en": "Vienna Wiener Sausages", "category": "processed_meat", "unit": "g", "calories": 230, "protein": 11.0, "fat": 19.8, "carbs": 1.9},
    {"name": "Сардельки говяжьи", "en": "Beef Bratwurst Links", "category": "processed_meat", "unit": "g", "calories": 215, "protein": 12.8, "fat": 17.7, "carbs": 1.1},
    {"name": "Бекон копчёный", "en": "Smoked Streaky Bacon", "category": "processed_meat", "unit": "g", "calories": 541, "protein": 17.0, "fat": 52.0, "carbs": 0.7},
    {"name": "Бекон из индейки", "en": "Turkey Rashers Bacon", "category": "processed_meat", "unit": "g", "calories": 218, "protein": 28.0, "fat": 11.5, "carbs": 0.8},
    {"name": "Мортаделла итальянская", "en": "Italian Mortadella Bologna", "category": "processed_meat", "unit": "g", "calories": 311, "protein": 14.1, "fat": 27.4, "carbs": 1.5},
    {"name": "Куриная колбаска", "en": "Chicken Cocktail Sausage", "category": "processed_meat", "unit": "g", "calories": 155, "protein": 18.0, "fat": 8.0, "carbs": 2.5},
    {"name": "Прошутто крудо", "en": "Prosciutto Crudo Leg", "category": "processed_meat", "unit": "g", "calories": 215, "protein": 26.0, "fat": 12.3, "carbs": 0.3},
    {"name": "Панчетта кубиками", "en": "Pancetta Cubed Smoked", "category": "processed_meat", "unit": "g", "calories": 425, "protein": 13.0, "fat": 42.0, "carbs": 0.3},
    {"name": "Лардоны копчёные", "en": "Smoked Lardons Cubed", "category": "processed_meat", "unit": "g", "calories": 541, "protein": 17.0, "fat": 52.0, "carbs": 0.7},
    {"name": "Чоризо пикантное", "en": "Spicy Chorizo Ring", "category": "processed_meat", "unit": "g", "calories": 455, "protein": 24.1, "fat": 38.3, "carbs": 1.9},
    {"name": "Паштет из гусиной печени", "en": "Goose Liver Pate", "category": "processed_meat", "unit": "g", "calories": 462, "protein": 11.4, "fat": 43.8, "carbs": 3.7},
    {"name": "Паштет куриный", "en": "Chicken Liver Pate Spread", "category": "processed_meat", "unit": "g", "calories": 185, "protein": 13.0, "fat": 14.0, "carbs": 2.5},
    {"name": "Паштет мясной", "en": "Country Meat Pate Terrine", "category": "processed_meat", "unit": "g", "calories": 297, "protein": 15.6, "fat": 25.0, "carbs": 3.0},

    # ─── Продукты для профессиональных кухонь ───────────────────────────────
    {"name": "Соль морская крупная", "en": "Coarse Sea Salt", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Соль морская мелкая", "en": "Fine Sea Salt", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Соль малдонская хлопьями", "en": "Maldon Sea Salt Flakes", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Соль гималайская розовая", "en": "Pink Himalayan Salt", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Соль флёр де сель", "en": "Fleur de Sel Premium Salt", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Соль копчёная", "en": "Smoked Applewood Salt", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Разрыхлитель теста", "en": "Baking Powder Aluminum Free", "category": "sweets", "unit": "g", "calories": 53, "protein": 0.1, "fat": 0.1, "carbs": 27.7},
    {"name": "Сода пищевая", "en": "Baking Soda Bicarbonate", "category": "sweets", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Дрожжи сухие активные", "en": "Active Dry Yeast", "category": "bakery", "unit": "g", "calories": 325, "protein": 40.4, "fat": 7.6, "carbs": 41.2},
    {"name": "Дрожжи прессованные", "en": "Fresh Compressed Yeast", "category": "bakery", "unit": "g", "calories": 109, "protein": 12.7, "fat": 2.7, "carbs": 8.2},
    {"name": "Дрожжи инстантные", "en": "Instant Fast Rise Yeast", "category": "bakery", "unit": "g", "calories": 325, "protein": 40.4, "fat": 7.6, "carbs": 41.2},
    {"name": "Крахмал кукурузный", "en": "Cornstarch Thickener", "category": "sweets", "unit": "g", "calories": 381, "protein": 0.3, "fat": 0.1, "carbs": 91.3},
    {"name": "Крахмал картофельный", "en": "Potato Starch Thickener", "category": "sweets", "unit": "g", "calories": 357, "protein": 0.1, "fat": 0.0, "carbs": 85.6},
    {"name": "Крахмал рисовый", "en": "Rice Starch Powder", "category": "sweets", "unit": "g", "calories": 362, "protein": 0.0, "fat": 0.0, "carbs": 91.0},
    {"name": "Мука аррорут", "en": "Arrowroot Starch Powder", "category": "sweets", "unit": "g", "calories": 357, "protein": 0.3, "fat": 0.1, "carbs": 88.1},
    {"name": "Панировочные сухари", "en": "Dried Bread Crumbs Plain", "category": "bakery", "unit": "g", "calories": 370, "protein": 13.0, "fat": 5.0, "carbs": 70.0},
    {"name": "Панко японские сухари", "en": "Japanese Panko Breadcrumbs", "category": "bakery", "unit": "g", "calories": 395, "protein": 11.0, "fat": 3.5, "carbs": 76.0},
    {"name": "Стружка пармезан", "en": "Parmesan Cheese Shavings", "category": "dairy", "unit": "g", "calories": 431, "protein": 38.5, "fat": 29.0, "carbs": 4.1},
    {"name": "Хлопья чеснока", "en": "Garlic Flakes Dried", "category": "spices", "unit": "g", "calories": 362, "protein": 17.6, "fat": 0.6, "carbs": 80.7},
    {"name": "Порошок чеснока", "en": "Garlic Powder Granulated", "category": "spices", "unit": "g", "calories": 362, "protein": 17.6, "fat": 0.6, "carbs": 80.7},
    {"name": "Хлопья лука", "en": "Onion Flakes Dried", "category": "spices", "unit": "g", "calories": 349, "protein": 10.1, "fat": 0.8, "carbs": 82.7},
    {"name": "Порошок лука", "en": "Onion Powder Ground", "category": "spices", "unit": "g", "calories": 349, "protein": 10.1, "fat": 0.8, "carbs": 82.7},
    {"name": "Порошок томата", "en": "Tomato Powder Dehydrated", "category": "spices", "unit": "g", "calories": 333, "protein": 16.7, "fat": 3.3, "carbs": 66.7},
    {"name": "Лимонная кислота", "en": "Citric Acid Powder Food Grade", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Глутамат натрия", "en": "Monosodium Glutamate MSG", "category": "spices", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Гуаровая камедь", "en": "Guar Gum Powder", "category": "sweets", "unit": "g", "calories": 336, "protein": 5.4, "fat": 0.5, "carbs": 86.4},
    {"name": "Каррагинан", "en": "Carrageenan Powder", "category": "sweets", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Лецитин соевый", "en": "Soy Lecithin Powder", "category": "sweets", "unit": "g", "calories": 763, "protein": 3.3, "fat": 97.3, "carbs": 0.0},
    {"name": "Метилцеллюлоза", "en": "Methylcellulose Food Grade", "category": "sweets", "unit": "g", "calories": 0, "protein": 0.0, "fat": 0.0, "carbs": 0.0},
    {"name": "Инулин порошок", "en": "Inulin Dietary Fiber Powder", "category": "sweets", "unit": "g", "calories": 150, "protein": 0.5, "fat": 0.2, "carbs": 70.0},
    {"name": "Мальтодекстрин", "en": "Maltodextrin Powder", "category": "sweets", "unit": "g", "calories": 378, "protein": 0.0, "fat": 0.0, "carbs": 95.0},
    {"name": "Сорбитол", "en": "Sorbitol Sugar Alcohol", "category": "sweets", "unit": "g", "calories": 264, "protein": 0.0, "fat": 0.0, "carbs": 64.0},
    {"name": "Эритритол", "en": "Erythritol Zero Calorie Sweetener", "category": "sweets", "unit": "g", "calories": 20, "protein": 0.0, "fat": 0.0, "carbs": 100.0},
    {"name": "Стевия порошок", "en": "Stevia Leaf Extract Powder", "category": "sweets", "unit": "g", "calories": 3, "protein": 0.0, "fat": 0.0, "carbs": 0.9},

    # ─── Дополнительные овощи ───────────────────────────────────────────────
    {"name": "Помидоры Черри желтые", "en": "Yellow Cherry Tomatoes", "category": "vegetables", "unit": "g", "calories": 27, "protein": 1.0, "fat": 0.3, "carbs": 5.8},
    {"name": "Томаты вяленые в масле", "en": "Sun Dried Tomatoes in Oil", "category": "vegetables", "unit": "g", "calories": 213, "protein": 5.1, "fat": 14.1, "carbs": 19.0},
    {"name": "Острый перец хабанеро", "en": "Habanero Hot Pepper", "category": "vegetables", "unit": "g", "calories": 40, "protein": 1.9, "fat": 0.5, "carbs": 8.8},
    {"name": "Перец халапеньо", "en": "Jalapeno Chili Pepper", "category": "vegetables", "unit": "g", "calories": 27, "protein": 0.9, "fat": 0.4, "carbs": 6.5},
    {"name": "Перец серрано", "en": "Serrano Chili Pepper", "category": "vegetables", "unit": "g", "calories": 32, "protein": 1.7, "fat": 0.5, "carbs": 6.7},
    {"name": "Перец анахейм", "en": "Anaheim Green Pepper", "category": "vegetables", "unit": "g", "calories": 28, "protein": 1.3, "fat": 0.2, "carbs": 5.9},
    {"name": "Перец поблано", "en": "Poblano Dark Green Pepper", "category": "vegetables", "unit": "g", "calories": 20, "protein": 0.9, "fat": 0.2, "carbs": 4.4},
    {"name": "Перец чипотле копчёный", "en": "Chipotle Smoked Pepper", "category": "vegetables", "unit": "g", "calories": 312, "protein": 12.3, "fat": 10.7, "carbs": 54.3},
    {"name": "Репчатый лук обжаренный", "en": "Fried Caramelized Onion", "category": "vegetables", "unit": "g", "calories": 115, "protein": 1.6, "fat": 6.3, "carbs": 15.5},
    {"name": "Лук-шалот жареный", "en": "French Fried Shallots", "category": "vegetables", "unit": "g", "calories": 132, "protein": 2.0, "fat": 7.5, "carbs": 16.0},
    {"name": "Капуста кимчи", "en": "Korean Kimchi", "category": "vegetables", "unit": "g", "calories": 15, "protein": 1.1, "fat": 0.5, "carbs": 2.4},
    {"name": "Квашеная капуста", "en": "Sauerkraut Fermented Cabbage", "category": "vegetables", "unit": "g", "calories": 19, "protein": 0.9, "fat": 0.1, "carbs": 4.3},
    {"name": "Солёные огурцы", "en": "Pickled Cucumbers Gherkins", "category": "vegetables", "unit": "g", "calories": 11, "protein": 0.7, "fat": 0.2, "carbs": 2.2},
    {"name": "Маринованный имбирь", "en": "Pickled Ginger Gari", "category": "vegetables", "unit": "g", "calories": 80, "protein": 0.2, "fat": 0.1, "carbs": 17.0},
    {"name": "Маслины чёрные", "en": "Black Olives Pitted", "category": "vegetables", "unit": "g", "calories": 115, "protein": 0.8, "fat": 10.7, "carbs": 6.3},
    {"name": "Оливки зелёные с косточкой", "en": "Green Olives with Stone", "category": "vegetables", "unit": "g", "calories": 145, "protein": 1.0, "fat": 15.3, "carbs": 3.8},
    {"name": "Каперсы маринованные", "en": "Brined Capers Nonpareil", "category": "vegetables", "unit": "g", "calories": 23, "protein": 2.4, "fat": 0.9, "carbs": 4.9},
    {"name": "Корнишоны маринованные", "en": "Pickled Cornichon Gherkins", "category": "vegetables", "unit": "g", "calories": 9, "protein": 0.5, "fat": 0.1, "carbs": 2.1},
    {"name": "Вакаме водоросли", "en": "Wakame Seaweed Dried", "category": "vegetables", "unit": "g", "calories": 45, "protein": 3.0, "fat": 0.6, "carbs": 9.1},
    {"name": "Нори листы", "en": "Nori Seaweed Sheets", "category": "vegetables", "unit": "g", "calories": 35, "protein": 5.8, "fat": 0.3, "carbs": 5.1},
    {"name": "Ламинария морская капуста", "en": "Kelp Seaweed Salad", "category": "vegetables", "unit": "g", "calories": 43, "protein": 1.7, "fat": 0.6, "carbs": 9.6},
    {"name": "Батат запечённый", "en": "Baked Sweet Potato", "category": "vegetables", "unit": "g", "calories": 90, "protein": 2.0, "fat": 0.1, "carbs": 20.7},
    {"name": "Тыква мускатная", "en": "Butternut Squash Peeled", "category": "vegetables", "unit": "g", "calories": 45, "protein": 1.0, "fat": 0.1, "carbs": 11.7},
    {"name": "Артишоки маринованные", "en": "Marinated Artichoke Hearts", "category": "vegetables", "unit": "g", "calories": 76, "protein": 2.1, "fat": 4.6, "carbs": 7.5},
    {"name": "Водоросли спирулина", "en": "Spirulina Algae Powder", "category": "vegetables", "unit": "g", "calories": 290, "protein": 57.5, "fat": 7.7, "carbs": 23.9},
    {"name": "Хлорелла порошок", "en": "Chlorella Algae Powder", "category": "vegetables", "unit": "g", "calories": 410, "protein": 58.4, "fat": 9.3, "carbs": 23.2},

    # ─── Фрукты расширенные ─────────────────────────────────────────────────
    {"name": "Манго зелёное", "en": "Green Unripe Mango", "category": "fruits", "unit": "g", "calories": 60, "protein": 0.8, "fat": 0.4, "carbs": 15.0},
    {"name": "Папайя зелёная", "en": "Green Papaya Fruit", "category": "fruits", "unit": "g", "calories": 43, "protein": 0.5, "fat": 0.1, "carbs": 11.0},
    {"name": "Банан зелёный", "en": "Unripe Green Banana", "category": "fruits", "unit": "g", "calories": 89, "protein": 1.1, "fat": 0.3, "carbs": 22.8},
    {"name": "Ягоды асаи замороженные", "en": "Frozen Acai Berry Pulp", "category": "fruits", "unit": "g", "calories": 70, "protein": 1.5, "fat": 5.0, "carbs": 4.0},
    {"name": "Ягоды годжи сушёные", "en": "Dried Goji Berry", "category": "fruits", "unit": "g", "calories": 349, "protein": 14.3, "fat": 0.4, "carbs": 82.1},
    {"name": "Облепиха ягоды", "en": "Sea Buckthorn Berries", "category": "fruits", "unit": "g", "calories": 82, "protein": 1.2, "fat": 5.4, "carbs": 9.0},
    {"name": "Ирга", "en": "Serviceberry Saskatoon", "category": "fruits", "unit": "g", "calories": 85, "protein": 0.7, "fat": 1.1, "carbs": 20.3},
    {"name": "Айва свежая", "en": "Fresh Quince Fruit", "category": "fruits", "unit": "g", "calories": 57, "protein": 0.4, "fat": 0.1, "carbs": 15.3},
    {"name": "Арония черноплодная", "en": "Chokeberry Aronia", "category": "fruits", "unit": "g", "calories": 47, "protein": 0.7, "fat": 0.0, "carbs": 12.3},
    {"name": "Брусника", "en": "Lingonberry Nordic", "category": "fruits", "unit": "g", "calories": 46, "protein": 0.7, "fat": 0.5, "carbs": 12.0},
    {"name": "Ежевика лесная", "en": "Wild Forest Blackberry", "category": "fruits", "unit": "g", "calories": 43, "protein": 1.4, "fat": 0.5, "carbs": 9.6},
    {"name": "Черника лесная", "en": "Wild Forest Blueberry", "category": "fruits", "unit": "g", "calories": 44, "protein": 1.1, "fat": 0.5, "carbs": 9.6},
    {"name": "Вишня свежая тёмная", "en": "Dark Sweet Cherry Fresh", "category": "fruits", "unit": "g", "calories": 63, "protein": 1.1, "fat": 0.2, "carbs": 16.0},
    {"name": "Черешня белая", "en": "White Sweet Cherry", "category": "fruits", "unit": "g", "calories": 63, "protein": 1.2, "fat": 0.3, "carbs": 15.8},
    {"name": "Слива красная", "en": "Red Japanese Plum", "category": "fruits", "unit": "g", "calories": 46, "protein": 0.7, "fat": 0.3, "carbs": 11.4},
    {"name": "Нектарин жёлтый", "en": "Yellow Nectarine", "category": "fruits", "unit": "g", "calories": 44, "protein": 1.1, "fat": 0.3, "carbs": 10.6},
    {"name": "Абрикос свежий", "en": "Fresh Apricot Summer", "category": "fruits", "unit": "g", "calories": 48, "protein": 1.4, "fat": 0.4, "carbs": 11.1},
    {"name": "Инжир свежий", "en": "Fresh Fig Fruit", "category": "fruits", "unit": "g", "calories": 74, "protein": 0.8, "fat": 0.3, "carbs": 19.2},
    {"name": "Финик меджуль", "en": "Medjool Date Premium", "category": "fruits", "unit": "g", "calories": 277, "protein": 1.8, "fat": 0.2, "carbs": 75.0},
    {"name": "Сушёный абрикос", "en": "Dried Apricot Halves", "category": "fruits", "unit": "g", "calories": 241, "protein": 3.4, "fat": 0.5, "carbs": 62.6},
    {"name": "Изюм золотой", "en": "Golden Sultan Raisin", "category": "fruits", "unit": "g", "calories": 299, "protein": 3.1, "fat": 0.5, "carbs": 79.2},
    {"name": "Чернослив сушёный", "en": "Dried Prune Plum", "category": "fruits", "unit": "g", "calories": 240, "protein": 2.2, "fat": 0.4, "carbs": 63.9},
    {"name": "Сушёная вишня", "en": "Dried Tart Cherry", "category": "fruits", "unit": "g", "calories": 267, "protein": 1.0, "fat": 0.0, "carbs": 70.0},
    {"name": "Клюква сушёная", "en": "Sweetened Dried Cranberry", "category": "fruits", "unit": "g", "calories": 308, "protein": 0.1, "fat": 1.1, "carbs": 82.4},
    {"name": "Личи свежий", "en": "Fresh Lychee Fruit", "category": "fruits", "unit": "g", "calories": 66, "protein": 0.8, "fat": 0.4, "carbs": 16.5},
    {"name": "Лонган свежий", "en": "Fresh Longan Fruit", "category": "fruits", "unit": "g", "calories": 60, "protein": 1.3, "fat": 0.1, "carbs": 15.1},
    {"name": "Рамбутан", "en": "Rambutan Tropical Fruit", "category": "fruits", "unit": "g", "calories": 82, "protein": 0.7, "fat": 0.2, "carbs": 21.0},
    {"name": "Питахайя красная", "en": "Red Dragon Fruit Pitahaya", "category": "fruits", "unit": "g", "calories": 60, "protein": 1.2, "fat": 0.0, "carbs": 13.0},
    {"name": "Питахайя жёлтая", "en": "Yellow Dragon Fruit", "category": "fruits", "unit": "g", "calories": 60, "protein": 1.4, "fat": 0.0, "carbs": 12.0},
    {"name": "Карамбола свежая", "en": "Star Fruit Carambola", "category": "fruits", "unit": "g", "calories": 31, "protein": 1.0, "fat": 0.3, "carbs": 6.7},
    {"name": "Гуава тропическая", "en": "Tropical Guava Fresh", "category": "fruits", "unit": "g", "calories": 68, "protein": 2.6, "fat": 1.0, "carbs": 14.3},
    {"name": "Маракуйя жёлтая", "en": "Yellow Passion Fruit", "category": "fruits", "unit": "g", "calories": 97, "protein": 2.2, "fat": 0.7, "carbs": 23.4},
    {"name": "Кокос мякоть свежая", "en": "Fresh Coconut Meat", "category": "fruits", "unit": "g", "calories": 354, "protein": 3.3, "fat": 33.5, "carbs": 15.2},
    {"name": "Кокос тёртый свежий", "en": "Fresh Grated Coconut", "category": "fruits", "unit": "g", "calories": 354, "protein": 3.3, "fat": 33.5, "carbs": 15.2},
]

def main():
    print(f"Всего дополнительных продуктов: {len(EXTRA_PRODUCTS)}")
    output = []
    for p in EXTRA_PRODUCTS:
        output.append({
            "name": p["name"],
            "en": p["en"],
            "category": p["category"],
            "unit": p["unit"],
            "calories": p["calories"],
            "protein": p["protein"],
            "fat": p["fat"],
            "carbs": p["carbs"],
        })
    with open("extra_products.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print("Сохранено в extra_products.json")

if __name__ == "__main__":
    main()
