#!/usr/bin/env python3
"""Добавляет ключи PDF шапок HACCP для макетов EU / GB / TR (+ подписи к холодильникам и гигиене)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "assets/translations/localizable.json"


def block_ru() -> dict[str, str]:
    return {
        "haccp_pdf_fridge_layout_eu_note": "Температуры в °C (требования гигиены ЕС, Регламент 852/2004).",
        "haccp_pdf_fridge_layout_gb_note": "Температуры в °C (рекомендации UK по гигиене пищевых продуктов).",
        "haccp_pdf_fridge_layout_tr_note": "Температуры в °C (соответствие правилам Турции по гигиене питания).",
        "haccp_pdf_health_form_caption_layout_eu": "Рекомендуемая форма мониторинга здоровья персонала (ЕС / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Рекомендуемая форма мониторинга здоровья персонала (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Рекомендуемая форма учёта здоровья персонала (Турция)",
        "haccp_warehouse_premises_layout_eu": "Складское помещение",
        "haccp_warehouse_premises_layout_gb": "Склад / помещение",
        "haccp_warehouse_premises_layout_tr": "Складское помещение",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _RU_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _RU_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _RU_TR.items()},
    }


_RU_EU = {
    "pp_no": "№",
    "date": "Дата",
    "employee_fio_long": "Сотрудник",
    "position": "Должность",
    "sign_family_infect": "Нет кишечных инфекций (Д/Н)",
    "sign_skin_resp": "Кожа/дыхание ОК (Д/Н)",
    "exam_outcome": "Допущен / отстранён",
    "med_worker_sign": "Подпись ответственного",
    "room_name_prod": "Помещение",
    "fridge_equipment_name": "Оборудование",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "Т, °C",
    "rel_humidity_pct": "Влажность %",
    "responsible_sign": "Подпись",
    "dish_made_at": "Изготовлено",
    "brakerage_removed_at": "Снято с бракеража",
    "dish_name_ready": "Блюдо",
    "organo_result": "Органолептика",
    "sale_allowed": "К реализации",
    "brakerage_commission_sigs": "Комиссия",
    "portion_weighing": "Порции",
    "note_short": "Прим.",
    "received_at": "Поступило",
    "name": "Наименование",
    "packaging": "Фасовка",
    "manufacturer": "Поставщик",
    "qty_short": "Кол-во",
    "doc_no": "Док.",
    "organo_short": "Орг.",
    "storage_shelf": "Хранение",
    "sale_date": "Реализация",
    "signature": "Подпись",
    "time_start": "Начало",
    "fat_type": "Жир",
    "score_start": "Балл н.",
    "equipment": "Оборудование",
    "product_type": "Продукт",
    "time_end": "Конец",
    "score_end": "Балл к.",
    "carry_kg": "Перенос кг",
    "utilized_kg": "Утилиз. кг",
    "controller": "Контролёр",
    "fio_full": "ФИО",
    "med_book_no": "№ медкнижки",
    "med_book_valid": "Действует до",
    "med_book_receipt": "Выдача",
    "med_book_return": "Возврат",
    "serial_short": "№",
    "med_exam_fio": "ФИО",
    "exam_date": "Осмотр",
    "conclusion": "Заключение",
    "decision": "Решение",
    "object_agent": "Объект / средство",
    "receipt": "Поступление",
    "responsible": "Ответственный",
    "time": "Время",
    "wash_solution": "Моющее",
    "disinfect_solution": "Дезсредство",
    "room": "Помещение",
    "sieve_magnet_no": "№ сита/магнит",
    "condition": "Состояние",
    "cleaning_date": "Очистка",
    "comments": "Коммент.",
}

_RU_GB = dict(_RU_EU)
_RU_GB.update(
    {
        "sign_family_infect": "Нет симптомов ЖКТ (Д/Н)",
        "exam_outcome": "Допущен / отстранён",
        "med_worker_sign": "Подпись ответственного (PIC)",
        "storage_shelf": "Условия / срок",
    }
)

_RU_TR = dict(_RU_EU)
_RU_TR.update(
    {
        "med_worker_sign": "Sorumlu imza",
        "controller": "Kontrol",
    }
)


def block_en() -> dict[str, str]:
    return {
        "haccp_pdf_fridge_layout_eu_note": "Temperatures in °C (EU hygiene rules, Regulation 852/2004).",
        "haccp_pdf_fridge_layout_gb_note": "Temperatures in °C (UK food hygiene guidance).",
        "haccp_pdf_fridge_layout_tr_note": "Temperatures in °C (Turkish food hygiene rules).",
        "haccp_pdf_health_form_caption_layout_eu": "Recommended staff health monitoring form (EU / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Recommended staff health monitoring form (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Recommended staff health monitoring form (Turkey)",
        "haccp_warehouse_premises_layout_eu": "Warehouse / room",
        "haccp_warehouse_premises_layout_gb": "Warehouse room",
        "haccp_warehouse_premises_layout_tr": "Storage area",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _EN_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _EN_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _EN_TR.items()},
    }


_EN_EU = {
    "pp_no": "No.",
    "date": "Date",
    "employee_fio_long": "Employee",
    "position": "Role",
    "sign_family_infect": "No GI symptoms (Y/N)",
    "sign_skin_resp": "Skin/resp. OK (Y/N)",
    "exam_outcome": "Fit / excluded",
    "med_worker_sign": "Responsible sign.",
    "room_name_prod": "Room",
    "fridge_equipment_name": "Equipment",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "T (°C)",
    "rel_humidity_pct": "RH %",
    "responsible_sign": "Sign.",
    "dish_made_at": "Made at",
    "brakerage_removed_at": "Hold-off time",
    "dish_name_ready": "Dish",
    "organo_result": "Sensory",
    "sale_allowed": "Release",
    "brakerage_commission_sigs": "Panel",
    "portion_weighing": "Portions",
    "note_short": "Note",
    "received_at": "Received",
    "name": "Product",
    "packaging": "Pack",
    "manufacturer": "Supplier",
    "qty_short": "Qty",
    "doc_no": "Doc.",
    "organo_short": "Sensory",
    "storage_shelf": "Storage",
    "sale_date": "Sold",
    "signature": "Sign.",
    "time_start": "Start",
    "fat_type": "Oil/fat",
    "score_start": "Score s",
    "equipment": "Fryer",
    "product_type": "Food type",
    "time_end": "End",
    "score_end": "Score e",
    "carry_kg": "Carry kg",
    "utilized_kg": "Disposed kg",
    "controller": "PIC",
    "fio_full": "Name",
    "med_book_no": "Health card #",
    "med_book_valid": "Valid to",
    "med_book_receipt": "Issued",
    "med_book_return": "Returned",
    "serial_short": "No.",
    "med_exam_fio": "Name",
    "exam_date": "Exam",
    "conclusion": "Result",
    "decision": "Decision",
    "object_agent": "Surface / agent",
    "receipt": "Receipt",
    "responsible": "Owner",
    "time": "Time",
    "wash_solution": "Detergent",
    "disinfect_solution": "Disinfectant",
    "room": "Area",
    "sieve_magnet_no": "ID",
    "condition": "OK?",
    "cleaning_date": "Cleaned",
    "comments": "Notes",
}

_EN_GB = dict(_EN_EU)
_EN_GB.update(
    {
        "med_worker_sign": "Responsible person",
        "storage_shelf": "Shelf life",
        "signature": "Initials",
        "responsible_sign": "Initials",
    }
)

_EN_TR = dict(_EN_EU)
_EN_TR.update(
    {
        "controller": "Denetmen",
        "med_worker_sign": "Yetkili imza",
        "responsible": "Sorumlu",
    }
)


def block_es() -> dict[str, str]:
    """EU Spanish — короткие подписи колонок."""
    return {
        "haccp_pdf_fridge_layout_eu_note": "Temperaturas en °C (normativa UE 852/2004).",
        "haccp_pdf_fridge_layout_gb_note": "Temperaturas en °C (guia UK).",
        "haccp_pdf_fridge_layout_tr_note": "Temperaturas en °C (normativa turca).",
        "haccp_pdf_health_form_caption_layout_eu": "Formulario recomendado de salud del personal (UE / APPCC)",
        "haccp_pdf_health_form_caption_layout_gb": "Formulario recomendado de salud del personal (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Formulario recomendado de salud del personal (Turquia)",
        "haccp_warehouse_premises_layout_eu": "Sala de almacen",
        "haccp_warehouse_premises_layout_gb": "Almacen",
        "haccp_warehouse_premises_layout_tr": "Almacen",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _ES_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _ES_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _ES_TR.items()},
    }


_ES_EU = {
    "pp_no": "N.º",
    "date": "Fecha",
    "employee_fio_long": "Empleado",
    "position": "Puesto",
    "sign_family_infect": "Sin sintomas GI (S/N)",
    "sign_skin_resp": "Piel/vias OK (S/N)",
    "exam_outcome": "Apto / excluido",
    "med_worker_sign": "Firma responsable",
    "room_name_prod": "Sala",
    "fridge_equipment_name": "Equipo",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "T (°C)",
    "rel_humidity_pct": "HR %",
    "responsible_sign": "Firma",
    "dish_made_at": "Elaboracion",
    "brakerage_removed_at": "Fin retencion",
    "dish_name_ready": "Plato",
    "organo_result": "Sensorial",
    "sale_allowed": "Salida",
    "brakerage_commission_sigs": "Comision",
    "portion_weighing": "Raciones",
    "note_short": "Nota",
    "received_at": "Recepcion",
    "name": "Nombre",
    "packaging": "Envase",
    "manufacturer": "Proveedor",
    "qty_short": "Cant.",
    "doc_no": "Doc.",
    "organo_short": "Sens.",
    "storage_shelf": "Conservacion",
    "sale_date": "Venta",
    "signature": "Firma",
    "time_start": "Inicio",
    "fat_type": "Grasa",
    "score_start": "Punt. i",
    "equipment": "Freidora",
    "product_type": "Tipo",
    "time_end": "Fin",
    "score_end": "Punt. f",
    "carry_kg": "Arrastre kg",
    "utilized_kg": "Disp. kg",
    "controller": "PIC",
    "fio_full": "Nombre",
    "med_book_no": "N.º carnet",
    "med_book_valid": "Valido hasta",
    "med_book_receipt": "Entrega",
    "med_book_return": "Devolucion",
    "serial_short": "N.º",
    "med_exam_fio": "Nombre",
    "exam_date": "Revision",
    "conclusion": "Resultado",
    "decision": "Decision",
    "object_agent": "Superficie / producto",
    "receipt": "Albaran",
    "responsible": "Responsable",
    "time": "Hora",
    "wash_solution": "Detergente",
    "disinfect_solution": "Desinfectante",
    "room": "Zona",
    "sieve_magnet_no": "ID",
    "condition": "Estado",
    "cleaning_date": "Limpieza",
    "comments": "Notas",
}
_ES_GB = dict(_ES_EU)
_ES_TR = dict(_ES_EU)
_ES_TR.update({"controller": "Denetmen", "med_worker_sign": "Yetkili imza"})


def block_fr() -> dict[str, str]:
    return {
        "haccp_pdf_fridge_layout_eu_note": "Temperatures en °C (reglement UE 852/2004).",
        "haccp_pdf_fridge_layout_gb_note": "Temperatures en °C (guide UK).",
        "haccp_pdf_fridge_layout_tr_note": "Temperatures en °C (regles turques).",
        "haccp_pdf_health_form_caption_layout_eu": "Formulaire sante du personnel recommande (UE / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Formulaire sante du personnel recommande (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Formulaire sante du personnel recommande (Turquie)",
        "haccp_warehouse_premises_layout_eu": "Local / entrepot",
        "haccp_warehouse_premises_layout_gb": "Entrepot",
        "haccp_warehouse_premises_layout_tr": "Zone de stockage",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _FR_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _FR_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _FR_TR.items()},
    }


_FR_EU = {
    "pp_no": "N°",
    "date": "Date",
    "employee_fio_long": "Employe",
    "position": "Poste",
    "sign_family_infect": "Pas signes GI (O/N)",
    "sign_skin_resp": "Peau/voies OK (O/N)",
    "exam_outcome": "Admis / exclu",
    "med_worker_sign": "Signature resp.",
    "room_name_prod": "Salle",
    "fridge_equipment_name": "Equipement",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "T (°C)",
    "rel_humidity_pct": "HR %",
    "responsible_sign": "Sign.",
    "dish_made_at": "Prepare le",
    "brakerage_removed_at": "Fin de detention",
    "dish_name_ready": "Plat",
    "organo_result": "Sensoriel",
    "sale_allowed": "Mise en vente",
    "brakerage_commission_sigs": "Commission",
    "portion_weighing": "Portions",
    "note_short": "Note",
    "received_at": "Reception",
    "name": "Denomination",
    "packaging": "Condit.",
    "manufacturer": "Fournisseur",
    "qty_short": "Qté",
    "doc_no": "Doc.",
    "organo_short": "Sens.",
    "storage_shelf": "Conserv.",
    "sale_date": "Vente",
    "signature": "Sign.",
    "time_start": "Debut",
    "fat_type": "Graisse",
    "score_start": "Score d",
    "equipment": "Friteuse",
    "product_type": "Type",
    "time_end": "Fin",
    "score_end": "Score f",
    "carry_kg": "Report kg",
    "utilized_kg": "Elim. kg",
    "controller": "PIC",
    "fio_full": "Nom",
    "med_book_no": "N° carnet",
    "med_book_valid": "Valide jusquau",
    "med_book_receipt": "Remise",
    "med_book_return": "Retour",
    "serial_short": "N°",
    "med_exam_fio": "Nom",
    "exam_date": "Visite",
    "conclusion": "Conclusion",
    "decision": "Decision",
    "object_agent": "Surface / agent",
    "receipt": "Bon",
    "responsible": "Responsable",
    "time": "Heure",
    "wash_solution": "Lessive",
    "disinfect_solution": "Desinfectant",
    "room": "Zone",
    "sieve_magnet_no": "ID",
    "condition": "Etat",
    "cleaning_date": "Nettoyage",
    "comments": "Remarques",
}
_FR_GB = dict(_FR_EU)
_FR_TR = dict(_FR_EU)
_FR_TR.update({"controller": "Controleur", "med_worker_sign": "Signature autorisee"})


def block_de() -> dict[str, str]:
    return {
        "haccp_pdf_fridge_layout_eu_note": "Temperaturen in °C (EU-Hygiene, VO 852/2004).",
        "haccp_pdf_fridge_layout_gb_note": "Temperaturen in °C (UK-Leitfaden).",
        "haccp_pdf_fridge_layout_tr_note": "Temperaturen in °C (tuerkische Vorschriften).",
        "haccp_pdf_health_form_caption_layout_eu": "Empfohlenes Formular zur Personalgesundheit (EU / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Empfohlenes Formular zur Personalgesundheit (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Empfohlenes Formular zur Personalgesundheit (Tuerkei)",
        "haccp_warehouse_premises_layout_eu": "Lager / Raum",
        "haccp_warehouse_premises_layout_gb": "Lagerraum",
        "haccp_warehouse_premises_layout_tr": "Lagerbereich",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _DE_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _DE_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _DE_TR.items()},
    }


_DE_EU = {
    "pp_no": "Nr.",
    "date": "Datum",
    "employee_fio_long": "Mitarbeiter",
    "position": "Rolle",
    "sign_family_infect": "Keine GI-Symptome (J/N)",
    "sign_skin_resp": "Haut/Atem OK (J/N)",
    "exam_outcome": "Zugelassen / ausgeschlossen",
    "med_worker_sign": "Unterschrift",
    "room_name_prod": "Raum",
    "fridge_equipment_name": "Geraet",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "T (°C)",
    "rel_humidity_pct": "LF %",
    "responsible_sign": "Unt.",
    "dish_made_at": "Herstellung",
    "brakerage_removed_at": "Ende Rueckstellung",
    "dish_name_ready": "Speise",
    "organo_result": "Sensorik",
    "sale_allowed": "Freigabe",
    "brakerage_commission_sigs": "Kommission",
    "portion_weighing": "Portionen",
    "note_short": "Bem.",
    "received_at": "Eingang",
    "name": "Bezeichnung",
    "packaging": "Packung",
    "manufacturer": "Lieferant",
    "qty_short": "Mng.",
    "doc_no": "Dok.",
    "organo_short": "Sens.",
    "storage_shelf": "Lagerung",
    "sale_date": "Verkauf",
    "signature": "Unt.",
    "time_start": "Beginn",
    "fat_type": "Fett",
    "score_start": "Wert A",
    "equipment": "Fritteuse",
    "product_type": "Typ",
    "time_end": "Ende",
    "score_end": "Wert E",
    "carry_kg": "Transfer kg",
    "utilized_kg": "Entsorg. kg",
    "controller": "PK",
    "fio_full": "Name",
    "med_book_no": "Gesundheitsbuch Nr.",
    "med_book_valid": "Gueltig bis",
    "med_book_receipt": "Ausgabe",
    "med_book_return": "Rueckgabe",
    "serial_short": "Nr.",
    "med_exam_fio": "Name",
    "exam_date": "Untersuchung",
    "conclusion": "Ergebnis",
    "decision": "Entscheidung",
    "object_agent": "Flaeche / Mittel",
    "receipt": "Beleg",
    "responsible": "Verantw.",
    "time": "Zeit",
    "wash_solution": "Reiniger",
    "disinfect_solution": "Desinfektionsmittel",
    "room": "Bereich",
    "sieve_magnet_no": "ID",
    "condition": "Zustand",
    "cleaning_date": "Reinigung",
    "comments": "Notizen",
}
_DE_GB = dict(_DE_EU)
_DE_TR = dict(_DE_EU)
_DE_TR.update({"controller": "Kontrolleur"})


def block_it() -> dict[str, str]:
    return {
        "haccp_pdf_fridge_layout_eu_note": "Temperature in °C (UE reg. 852/2004).",
        "haccp_pdf_fridge_layout_gb_note": "Temperature in °C (linee guida UK).",
        "haccp_pdf_fridge_layout_tr_note": "Temperature in °C (norme turche).",
        "haccp_pdf_health_form_caption_layout_eu": "Modello consigliato monitoraggio salute personale (UE / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Modello consigliato monitoraggio salute personale (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Modello consigliato monitoraggio salute personale (Turchia)",
        "haccp_warehouse_premises_layout_eu": "Locale magazzino",
        "haccp_warehouse_premises_layout_gb": "Magazzino",
        "haccp_warehouse_premises_layout_tr": "Area stoccaggio",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _IT_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _IT_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _IT_TR.items()},
    }


_IT_EU = {
    "pp_no": "N.",
    "date": "Data",
    "employee_fio_long": "Dipendente",
    "position": "Ruolo",
    "sign_family_infect": "Nessun segno GI (S/N)",
    "sign_skin_resp": "Pelle/vie OK (S/N)",
    "exam_outcome": "Ammesso / escluso",
    "med_worker_sign": "Firma resp.",
    "room_name_prod": "Locale",
    "fridge_equipment_name": "Attrezzatura",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "T (°C)",
    "rel_humidity_pct": "UR %",
    "responsible_sign": "Firma",
    "dish_made_at": "Preparazione",
    "brakerage_removed_at": "Fine detenzione",
    "dish_name_ready": "Piatto",
    "organo_result": "Sensoriale",
    "sale_allowed": "Rilascio",
    "brakerage_commission_sigs": "Commissione",
    "portion_weighing": "Porzioni",
    "note_short": "Nota",
    "received_at": "Ricezione",
    "name": "Denominazione",
    "packaging": "Confez.",
    "manufacturer": "Fornitore",
    "qty_short": "Qtà",
    "doc_no": "Doc.",
    "organo_short": "Sens.",
    "storage_shelf": "Conservazione",
    "sale_date": "Vendita",
    "signature": "Firma",
    "time_start": "Inizio",
    "fat_type": "Grasso",
    "score_start": "Voto i",
    "equipment": "Friggitrice",
    "product_type": "Tipo",
    "time_end": "Fine",
    "score_end": "Voto f",
    "carry_kg": "Riporto kg",
    "utilized_kg": "Smalt. kg",
    "controller": "RIC",
    "fio_full": "Nome",
    "med_book_no": "N. libretto",
    "med_book_valid": "Valido fino",
    "med_book_receipt": "Consegna",
    "med_book_return": "Restituzione",
    "serial_short": "N.",
    "med_exam_fio": "Nome",
    "exam_date": "Visita",
    "conclusion": "Esito",
    "decision": "Decisione",
    "object_agent": "Superficie / agente",
    "receipt": "Ricevuta",
    "responsible": "Responsabile",
    "time": "Ora",
    "wash_solution": "Detersivo",
    "disinfect_solution": "Disinfettante",
    "room": "Area",
    "sieve_magnet_no": "ID",
    "condition": "Stato",
    "cleaning_date": "Pulizia",
    "comments": "Note",
}
_IT_GB = dict(_IT_EU)
_IT_TR = dict(_IT_EU)
_IT_TR.update({"controller": "Controllore"})


def block_tr_locale() -> dict[str, str]:
    """Турецкий интерфейс — подписи колонок."""
    return {
        "haccp_pdf_fridge_layout_eu_note": "Sicakliklar °C olarak (AB 852/2004 hijyen).",
        "haccp_pdf_fridge_layout_gb_note": "Sicakliklar °C olarak (UK rehberi).",
        "haccp_pdf_fridge_layout_tr_note": "Sicakliklar °C olarak (Turk gida hijyen kurallari).",
        "haccp_pdf_health_form_caption_layout_eu": "Onerilen personel sagligi formu (AB / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Onerilen personel sagligi formu (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Onerilen personel sagligi formu (Turkiye)",
        "haccp_warehouse_premises_layout_eu": "Depo / oda",
        "haccp_warehouse_premises_layout_gb": "Depo alani",
        "haccp_warehouse_premises_layout_tr": "Depolama",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _TR_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _TR_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _TR_TR.items()},
    }


_TR_EU = {
    "pp_no": "No",
    "date": "Tarih",
    "employee_fio_long": "Calisan",
    "position": "Gorev",
    "sign_family_infect": "GI belirtisi yok (E/H)",
    "sign_skin_resp": "Deri/solunum OK (E/H)",
    "exam_outcome": "Uygun / dislandi",
    "med_worker_sign": "Yetkili imza",
    "room_name_prod": "Oda",
    "fridge_equipment_name": "Ekipman",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "T (°C)",
    "rel_humidity_pct": "Nem %",
    "responsible_sign": "Imza",
    "dish_made_at": "Uretim",
    "brakerage_removed_at": "Bekleme sonu",
    "dish_name_ready": "Yemek",
    "organo_result": "Duyusal",
    "sale_allowed": "Sevk",
    "brakerage_commission_sigs": "Komisyon",
    "portion_weighing": "Porsiyon",
    "note_short": "Not",
    "received_at": "Teslim",
    "name": "Ad",
    "packaging": "Ambalaj",
    "manufacturer": "Tedarikci",
    "qty_short": "Mik.",
    "doc_no": "Belge",
    "organo_short": "Duyu",
    "storage_shelf": "Saklama",
    "sale_date": "Satis",
    "signature": "Imza",
    "time_start": "Basla",
    "fat_type": "Yag",
    "score_start": "Puan b",
    "equipment": "Kizartma",
    "product_type": "Tip",
    "time_end": "Bitis",
    "score_end": "Puan s",
    "carry_kg": "Aktar kg",
    "utilized_kg": "Imha kg",
    "controller": "Denetmen",
    "fio_full": "Ad soyad",
    "med_book_no": "Saglik karti no",
    "med_book_valid": "Gecerlilik",
    "med_book_receipt": "Teslim",
    "med_book_return": "Iade",
    "serial_short": "No",
    "med_exam_fio": "Ad soyad",
    "exam_date": "Muayene",
    "conclusion": "Sonuc",
    "decision": "Karar",
    "object_agent": "Yuzey / ajan",
    "receipt": "Teslimat",
    "responsible": "Sorumlu",
    "time": "Saat",
    "wash_solution": "Deterjan",
    "disinfect_solution": "Dezenfektan",
    "room": "Bolge",
    "sieve_magnet_no": "Kimlik",
    "condition": "Durum",
    "cleaning_date": "Temizlik",
    "comments": "Notlar",
}
_TR_GB = dict(_TR_EU)
_TR_TR = dict(_TR_EU)


def block_kk() -> dict[str, str]:
    """Қазақша — техникалық қысқа түрлер."""
    return {
        "haccp_pdf_fridge_layout_eu_note": "Температура °C (ЕО 852/2004 гигиена).",
        "haccp_pdf_fridge_layout_gb_note": "Температура °C (UK нұсқауы).",
        "haccp_pdf_fridge_layout_tr_note": "Температура °C (Түрік ережелері).",
        "haccp_pdf_health_form_caption_layout_eu": "Персонал денсаулығының ұсынылған түрі (ЕО / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Персонал денсаулығының ұсынылған түрі (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Персонал денсаулығының ұсынылған түрі (Түркия)",
        "haccp_warehouse_premises_layout_eu": "Қойма бөлмесі",
        "haccp_warehouse_premises_layout_gb": "Қойма",
        "haccp_warehouse_premises_layout_tr": "Сақтау аймағы",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _KK_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _KK_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _KK_TR.items()},
    }


_KK_EU = dict(_RU_EU)
_KK_GB = dict(_RU_GB)
_KK_TR = dict(_RU_TR)


def block_vi() -> dict[str, str]:
    return {
        "haccp_pdf_fridge_layout_eu_note": "Nhiet do luu bang °C (EU 852/2004).",
        "haccp_pdf_fridge_layout_gb_note": "Nhiet do luu bang °C (huong dan UK).",
        "haccp_pdf_fridge_layout_tr_note": "Nhiet do luu bang °C (quy dinh Tho Nhi Ky).",
        "haccp_pdf_health_form_caption_layout_eu": "Mau giam sat suc khoe nhan vien (EU / HACCP)",
        "haccp_pdf_health_form_caption_layout_gb": "Mau giam sat suc khoe nhan vien (UK)",
        "haccp_pdf_health_form_caption_layout_tr": "Mau giam sat suc khoe nhan vien (Tho Nhi Ky)",
        "haccp_warehouse_premises_layout_eu": "Kho / phong",
        "haccp_warehouse_premises_layout_gb": "Kho",
        "haccp_warehouse_premises_layout_tr": "Khu luu tru",
        **{f"haccp_tbl_{k}_layout_eu": v for k, v in _VI_EU.items()},
        **{f"haccp_tbl_{k}_layout_gb": v for k, v in _VI_GB.items()},
        **{f"haccp_tbl_{k}_layout_tr": v for k, v in _VI_TR.items()},
    }


_VI_EU = {
    "pp_no": "STT",
    "date": "Ngay",
    "employee_fio_long": "Nhan vien",
    "position": "Vai tro",
    "sign_family_infect": "Khong dau hieu tieu hoa (C/K)",
    "sign_skin_resp": "Da/ho hap OK (C/K)",
    "exam_outcome": "Duoc lam / tam dung",
    "med_worker_sign": "Ch ky resp.",
    "room_name_prod": "Phong",
    "fridge_equipment_name": "Thiet bi",
    "temp_celsius": "°C",
    "temp_fahrenheit": "°F",
    "temp_c_label": "T (°C)",
    "rel_humidity_pct": "Do am %",
    "responsible_sign": "Ky ten",
    "dish_made_at": "Che bien",
    "brakerage_removed_at": "Ket thuc giu",
    "dish_name_ready": "Mon",
    "organo_result": "Cam quan",
    "sale_allowed": "Cho ban",
    "brakerage_commission_sigs": "Hoi dong",
    "portion_weighing": "Khau phan",
    "note_short": "Ghi chu",
    "received_at": "Nhan hang",
    "name": "Ten",
    "packaging": "Dong goi",
    "manufacturer": "Nha cung cap",
    "qty_short": "SL",
    "doc_no": "So CT",
    "organo_short": "CQ",
    "storage_shelf": "Bao quan",
    "sale_date": "Ban",
    "signature": "Ky",
    "time_start": "Bat dau",
    "fat_type": "Mo",
    "score_start": "Diem d",
    "equipment": "Chien",
    "product_type": "Loai",
    "time_end": "Ket thuc",
    "score_end": "Diem c",
    "carry_kg": "Chuyen kg",
    "utilized_kg": "Thai kg",
    "controller": "Giam sat",
    "fio_full": "Ho ten",
    "med_book_no": "So the SK",
    "med_book_valid": "Het han",
    "med_book_receipt": "Cap",
    "med_book_return": "Tra",
    "serial_short": "STT",
    "med_exam_fio": "Ho ten",
    "exam_date": "Kham",
    "conclusion": "Ket luan",
    "decision": "Quyet dinh",
    "object_agent": "Be mat / chat",
    "receipt": "Bien nhan",
    "responsible": "Chiu trach nhiem",
    "time": "Gio",
    "wash_solution": "Nuoc rua",
    "disinfect_solution": "Sat khuan",
    "room": "Khu vuc",
    "sieve_magnet_no": "Ma",
    "condition": "Tinh trang",
    "cleaning_date": "Ve sinh",
    "comments": "Ghi chu",
}
_VI_GB = dict(_VI_EU)
_VI_TR = dict(_VI_EU)


def main() -> None:
    with PATH.open(encoding="utf-8") as f:
        data = json.load(f)

    patches = {
        "ru": block_ru(),
        "en": block_en(),
        "es": block_es(),
        "fr": block_fr(),
        "de": block_de(),
        "it": block_it(),
        "tr": block_tr_locale(),
        "kk": block_kk(),
        "vi": block_vi(),
    }

    for lang, keys in patches.items():
        data[lang].update(keys)

    with PATH.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("patched", PATH, "keys per lang:", len(next(iter(patches.values()))))


if __name__ == "__main__":
    main()
